Microsoft.Recognizers.Text.DateTime.Tests/Microsoft.Recognizers.Text.DateTime.Tests.csproj, Microsoft.Recognizers.Text.DateTime.Tests/packages.config
=> Add MSTest.TestAdapter package

Microsoft.Recognizers.Text.Number/NumberRecognizer.cs
Added the French recognizer to NumberRecognizer.cs
=> added French recognizer

Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.csproj, Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.nuspec, Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.csproj, Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.nuspec, Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.csproj, Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.nuspec, Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.csproj, Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.nuspec
Copy the compiled files to the specified folder
=> Copy compiled files into the build/package folder

Microsoft.Recognizers.Resources/CommonDefinitions.ttinclude, Microsoft.Recognizers.Resources/English/DateTimeDefinitions.cs, Microsoft.Recognizers.Text.DateTime.Tests/Chinese/TestDurationChsParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/Chinese/TestDurtationChsExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestTimePeriodParser.cs, Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DurationExtractorChs.cs, Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DurationParserChs.cs, Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimePeriodExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishTimePeriodParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/English/Utilities/EnlighDatetimeUtilityConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs, Microsoft.Recognizers.Text.DateTime/Parsers/ITimePeriodParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimePeriodExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDatePeriodParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishTimePeriodParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Utilities/SpanishDatetimeUtilityConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Utilities/IDateTimeUtilityConfiguration.cs, Patterns/English/English-DateTime.yaml
fix three bugs reported by users.
VSO bug id:
2053 “from 1am to 5pm”
2058 “upcoming month”
2062 "三年半"
=> FixDateTimeBugsFromUser

Microsoft.Recognizers.Resources/English/DateTimeDefinitions.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestTimeExtractor.cs, Patterns/English/English-DateTime.yaml
Fixes cases like "which emails have gotten a reply" from returning 10am
=> Fixing bug where substrings of a word where recognized as a datetime.

Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, Microsoft.Recognizers.Text.DateTime.Tests/Chinese/TestChineseModel.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestEnglishModel.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestTimeParser.cs, Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/MergedDateTimeExtractor.cs, Microsoft.Recognizers.Text.DateTime/DateTimeOptions.cs, Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs, Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimeExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedExtractor.cs, Microsoft.Recognizers.Text.DateTime/Extractors/IMergedExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.csproj, Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimeParser.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs, Patterns/English/English-DateTime.yaml
1. add datetime options for configuration
2. split the from to into two datetime points for DatetimeOptions.SplitFromTo only
3. support the number in text for hour minute (only for the minute be divided by 5)
=> Add datetime options

Microsoft.Recognizers.Text.DateTime.Tests/English/TestDateExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDateParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestSingleCultureDateTimeRecognizer.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestTimeParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestTimePeriodParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/Microsoft.Recognizers.Text.DateTime.Tests.csproj, Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs, Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs, Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs, Microsoft.Recognizers.Text.DateTime/Parsers/FullDateTimeParser.cs, Microsoft.Recognizers.Text/Culture.cs, Microsoft.Recognizers.Text/ModelContainer.cs, Microsoft.Recognizers.Text/Recognizer.cs
- Exposing the creation of single-culture instances, without affecting existing behaviour and APIs;
- Minor cleanup.
=> Exposing the creation of single-culture instances, without affecting existing behaviour.

Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, Microsoft.Recognizers.Text.DateTime.Tests/Chinese/TestDateChsExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDateParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedParser.cs, Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateExtractorChs.cs, Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimePeriodExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateParserConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedExtractor.cs, Microsoft.Recognizers.Text.DateTime/Extractors/IMergedExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedParser.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs, Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateParserConfiguration.cs, Patterns/English/English-DateTime.yaml
=> Fix bugs reported by mercury#5

Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDateTimeParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDateTimePeriodExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestDateTimePeriodParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestEnglishModel.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedExtractor.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedParser.cs, Microsoft.Recognizers.Text.DateTime.Tests/English/TestTimePeriodExtractor.cs, Patterns/English/English-DateTime.yaml
+ separated some unit cases by theme in timex (ongoing).
=> Adding more unit tests from real queries to make sure these don't break.

JavaScript/src/dateTime/baseDate.ts, JavaScript/src/dateTime/baseDuration.ts, JavaScript/src/dateTime/baseHoliday.ts, JavaScript/src/dateTime/baseSet.ts, JavaScript/src/dateTime/english/dateConfiguration.ts, JavaScript/src/dateTime/english/setConfiguration.ts, JavaScript/src/resources/englishDateTime.ts, JavaScript/test/dateExtractor-english.test.js, JavaScript/test/dateParser-english.test.js, JavaScript/test/datePeriodExtractor-english.test.js, JavaScript/test/datePeriodParser-english.test.js, JavaScript/test/dateTime-english.test.js, JavaScript/test/dateTimeParser-english.test.js, JavaScript/test/mergedParser-english.test.js, JavaScript/test/setExtractor-english.test.js, JavaScript/test/setParser-english.test.js, JavaScript/test/timePeriodExtractor-english.test.js, JavaScript/test/timePeriodParser-english.test.js
* Replicate changes from:
- Fix 5 set related bugs reported by Mercury (#80)
- Adding more unit tests from real queries to make sure these don't break (#84)
* Apply feedback from typescript implementation (#83)
=> Replicate date, duration and set fixes on typescript

.NET/Microsoft.Recognizers.Text.sln, .gitignore
Fixing link from VS solution to new relative location of YAML files.
=> Fixing link from VS solution to new relative location of YAML files

.NET/CreateAllPackages.cmd, .NET/Microsoft.Recognizers.Text.DateTime.Tests/English/TestEnglishModel.cs, .NET/buildtools/updateAssemblyInfo.ps1
Fixing build scripts after code move to .NET dir
=> Fixing build scripts after code move to .NET dir

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, JavaScript/src/dateTime/baseDate.ts, JavaScript/src/dateTime/baseHoliday.ts, JavaScript/src/dateTime/english/dateConfiguration.ts, JavaScript/src/dateTime/english/holidayConfiguration.ts, JavaScript/src/number/extractors.ts, JavaScript/src/resources/englishDateTime.ts, JavaScript/src/utilities.ts, JavaScript/test/dateExtractor-english.test.js, JavaScript/test/dateParser-english.test.js, JavaScript/test/datePeriodExtractor-english.test.js, JavaScript/test/dateTimeExtractor-english.test.js, JavaScript/test/holidayExtractor-english.test.js, JavaScript/test/holidayParser-english.test.js, JavaScript/test/mergedParser-english.test.js, JavaScript/test/timeExtractor-english.test.js, JavaScript/test/timeParser-english.test.js, JavaScript/test/timePeriodExtractor-english.test.js, Patterns/English/English-DateTime.yaml
Replicate changes from:
- Fix 3 bugs found from Mercury test data (#86)
- Fix bugs found in Mercury test data (#89)
=> Replicate fixes related to Mercury test data on typescript

.NET/Build.cmd, JavaScript/build.cmd, JavaScript/package.json, build.cmd
- Build All
- Build .NET
- Restore NuGets
- Clean and Build
- Run Tests
- Build TypeScript
- Restore dependencies
- Clean and Build (regexes first, then build code)
- Run Tests
=> Build scripts for .NET and TypeScript

JavaScript/src/dateTime/baseDate.ts, JavaScript/test/dateExtractor-english.test.js, JavaScript/test/mergedParser-english.test.js
Implemented fixes found in master branch (PR#95) for C# into TypeScript/JS version
=> Implemented fixes found in master branch (PR#95)

JavaScript/src/dateTime/baseDate.ts, JavaScript/src/dateTime/baseDatePeriod.ts, JavaScript/src/dateTime/baseMerged.ts, JavaScript/src/dateTime/baseSet.ts, JavaScript/src/number/extractors.ts, JavaScript/src/resources/englishDateTime.ts, JavaScript/test/dateExtractor-english.test.js, JavaScript/test/mergedExtractor-english.test.js, JavaScript/test/mergedParser-english.test.js
Implemented fixes found in master branch (after merge PR #101) into TypeScript/JavaScript
=> PR #101: Apply minor regressions to TypeScript

JavaScript/src/utilities.ts
Bug: Regexes with more than one negative lookbehind resolves different matches than the C# implementation.
Solution: Those regexes are evaluated in two steps, first obtaining the matches without the negative lookbehind and then dropping those that also match with the negative lookbehind groups.
=> Fix negative lookbehind matches on javascript

JavaScript/src/dateTime/baseDate.ts, JavaScript/src/dateTime/baseDatePeriod.ts, JavaScript/src/dateTime/baseDateTimePeriod.ts, JavaScript/src/dateTime/baseMerged.ts, JavaScript/src/dateTime/constants.ts, JavaScript/src/dateTime/english/dateConfiguration.ts, JavaScript/src/dateTime/english/datePeriodConfiguration.ts, JavaScript/src/dateTime/english/dateTimePeriodConfiguration.ts, JavaScript/src/dateTime/english/mergedConfiguration.ts, JavaScript/src/dateTime/english/timeConfiguration.ts, JavaScript/src/dateTime/utilities.ts, JavaScript/src/resources/englishDateTime.ts, JavaScript/test/dateExtractor-english.test.js, JavaScript/test/dateParser-english.test.js, JavaScript/test/datePeriodExtractor-english.test.js, JavaScript/test/datePeriodParser-english.test.js, JavaScript/test/dateTime-english.test.js, JavaScript/test/dateTimePeriodExtractor-english.test.js, JavaScript/test/dateTimePeriodParser-english.test.js, JavaScript/test/mergedExtractor-english.test.js, JavaScript/test/mergedParser-english.test.js, JavaScript/test/setParser-english.test.js, JavaScript/test/timeExtractor-english.test.js, JavaScript/test/timeParser-english.test.js
Replicate changes from
* fix "since" prefix bug (#103)
* fix bugs 0913 (#105)
* fix a preproposition bug (#108)
=> Update javascript with dotNet changes

.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/TestHelpers.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs, .NET/Microsoft.Recognizers.Text.Tests/TestCulture.cs, .NET/Microsoft.Recognizers.Text.Tests/TestWriter.cs, .NET/Microsoft.Recognizers.Text.Tests/TraceListeners.cs, Specs/DateTime/English/DatePeriodExtractor.json
=> Minor changes to remove usage of recent .NET features not supported in VSO build

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/FormatUtil.cs, Patterns/English/English-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/English/MergedParser.json
fix the key not found exception while it is with before/after
add "in advance of" and "prior to" as "before".
=> fix an exception & add synonyms for "before"

.NET/Build.cmd, JavaScript/build.cmd, Specs/README.md
Edits to Specs/README.md; adding troubleshooting section.
Minor edits to build script to "organize" output.
=> Edits to Specs/README.md

.NET/Microsoft.Recognizers.Text.sln
French-DateTime.yaml was not checked into solution
=> Solution check in

JavaScript/recognizers-date-time/src/dateTime/baseMerged.ts, JavaScript/recognizers-number/src/number/extractors.ts, JavaScript/recognizers-number/src/number/portuguese/extractors.ts, JavaScript/recognizers-number/src/number/portuguese/parserConfiguration.ts, JavaScript/test/runner-datetime.js
- Fix when to call HolidayParser from MergedParser
- Fix references for case-sensitive file systems
=> JavaScript - Misc fixes

JavaScript/samples/README.md, JavaScript/samples/botbuilder/.env, JavaScript/samples/botbuilder/.vscode/launch.json, JavaScript/samples/botbuilder/helpers.js, JavaScript/samples/botbuilder/index.js, JavaScript/samples/botbuilder/package-lock.json, JavaScript/samples/botbuilder/package.json, JavaScript/samples/simple-console/.vscode/launch.json
A sample demonstrating how the Recognizers can be used with a BotBuilder Bot to parse user input. The bot provides a basic experience for ordering roses, it starts by asking the amount of roses and then asks for a delivery date and time.
=> JavaScript - BotBuilder Sample

.NET/Microsoft.Recognizers.Text.sln, .NET/Samples/BotBuilder/App_Start/WebApiConfig.cs, .NET/Samples/BotBuilder/BotBuilderRecognizerBot.csproj, .NET/Samples/BotBuilder/Controllers/MessagesController.cs, .NET/Samples/BotBuilder/Dialogs/DeliveryPrompt.cs, .NET/Samples/BotBuilder/Dialogs/QuantityPrompt.cs, .NET/Samples/BotBuilder/Dialogs/RootDialog.cs, .NET/Samples/BotBuilder/Global.asax, .NET/Samples/BotBuilder/Global.asax.cs, .NET/Samples/BotBuilder/Properties/AssemblyInfo.cs, .NET/Samples/BotBuilder/Web.Debug.config, .NET/Samples/BotBuilder/Web.Release.config, .NET/Samples/BotBuilder/Web.config, .NET/Samples/BotBuilder/default.htm, .NET/Samples/BotBuilder/packages.config, .NET/Samples/README.md, JavaScript/samples/README.md
A sample demonstrating how the Recognizers can be used with a BotBuilder Bot to parse user input. The bot provides a basic experience for ordering roses, it starts by asking the amount of roses and then asks for a delivery date and time.
Uses Custom Prompts to validate user input and return entity using proper types.
=> .NET - BotBuilder Sample

.NET/Build.cmd, .NET/Samples/BotBuilder/BotBuilderRecognizerBot.csproj
- **Fixed** .NET Sample BotBuilderRecognizerBot (file not found).
- **Updated** build.cmd file to run tests with VsTest.Console.
=> Fix and Update .NET build

appveyor.yml
The PR includes the AppVeyor configuration for building the JavaScript project and running its tests. 
If the build process or a tests fail, the whole build is marked as faulty.
It currently can
- Run CI master branch on each new commit
- Run CI on each new Pull Request (requires manual configuration on GitHub Project)
=> CI Configuration for AppVeyor (JavaScript)

.NET/README.md, JavaScript/README.md
C# and JavaScript README with high-level usage and minimal API documentation
=> Platform's README

JavaScript/README.md
- Packages description updates
- Manual build instructions update
- Fix to code and samples path
=> JavaScript - README Fixes

JavaScript/recognizers-date-time/src/dateTime/baseMerged.ts, JavaScript/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts, JavaScript/recognizers-date-time/src/dateTime/english/mergedConfiguration.ts, JavaScript/recognizers-date-time/src/dateTime/french/mergedConfiguration.ts, JavaScript/recognizers-date-time/src/dateTime/spanish/mergedConfiguration.ts
Applied changes to:
- baseMerged.ts
- english/mergedConfiguration.ts
- french/mergedConfiguration.ts
- spanish/mergedConfiguration.ts
- chinese/mergedConfiguration.ts
=> Ported changes in PR #168 to JS/TypeScript

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/ITimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/ITimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishTimePeriodParserConfiguration.cs, Specs/DateTime/English/DateTimePeriodExtractor.json, Specs/DateTime/English/DateTimePeriodParser.json, Specs/DateTime/English/TimePeriodExtractor.json, Specs/DateTime/English/TimePeriodParser.json
support the case like 2015-09-23 1p.m. to 4, extract "4" as end time of the time period.
=> Support ending number as part of time period

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimePeriodExtractor.json, Specs/DateTime/English/MergedParser.json, Specs/DateTime/English/TimePeriodExtractor.json, Specs/DateTime/English/TimePeriodParser.json
extract morning as "TMO" without date info
=> extract morning as "TMO" without date info

JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts, JavaScript/packages/recognizers-date-time/src/dateTime/baseDateTime.ts, JavaScript/packages/recognizers-date-time/src/dateTime/baseDateTimePeriod.ts, JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateTimePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/dateTimeRecognizer.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/dateTimeConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/dateTimePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/dateTimePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/dateTimePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/recognizers-text-date-time.ts, JavaScript/packages/recognizers-number/src/utilities.ts, Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DatePeriodParser.json, Specs/DateTime/English/DateTimeExtractor.json, Specs/DateTime/English/DateTimeParser.json, Specs/DateTime/English/DateTimePeriodExtractor.json, Specs/DateTime/English/DateTimePeriodParser.json
Port to JS - "Add support for the requirements of users and some improvements" (from #191)
=> Port changes in PR #191 to JS/TypeScript

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs, Specs/DateTime/English/MergedExtractor.json
Re-creating from PR 250 (https://github.com/Microsoft/Recognizers-Text/pull/250) as I can't push the fix to that branch.
=> Fixing long merge regression introduced in last release

.NET/Microsoft.Recognizers.Definitions/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Models/DateTimeModel.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeParser.cs, .NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/AbstractNumberWithUnitModel.cs, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/DateTime/Portuguese/DateExtractor.json
Enabling PT in timex & adding try catches.
Issue #11.
=> Enabling Portuguese in DateTime recognizers.

.NET/Build.cmd, .NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDatePeriodParserConfiguration.cs, Patterns/English/English-DateTime.yaml, Patterns/French/French-DateTime.yaml, Patterns/German/German-DateTime.yaml, Patterns/Portuguese/Portuguese-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/English/DateExtractor.json, Specs/DateTime/English/DateParser.json, Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DatePeriodParser.json
=> Fix conflicts in PR 254 (Extend year number)

.NET/Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.nuspec, .NET/Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.nuspec, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.nuspec, .NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.nuspec
Updating descriptions, requireLicenseAcceptance, and copyright.
=> Updating .nuspec files for consistency and new requirements

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DatePeriodExtractorChs.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs, Patterns/Chinese/Chinese-DateTime.yaml, Specs/DateTime/Chinese/DatePeriodExtractor.json, Specs/DateTime/Chinese/DatePeriodParser.json
=> Support Chinese written decades

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs, Patterns/Chinese/Chinese-DateTime.yaml, Specs/DateTime/Chinese/DateExtractor.json, Specs/DateTime/Chinese/DateParser.json, Specs/DateTime/Chinese/DatePeriodExtractor.json, Specs/DateTime/Chinese/DatePeriodParser.json
=> Support year before 1900 in Chinese

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateParser.cs, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts, Patterns/Chinese/Chinese-DateTime.yaml, Specs/DateTime/Chinese/DateExtractor.json, Specs/DateTime/Chinese/DateParser.json
=> Support "3 days from now" and "3 days before today" in Chinese date extraction

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs, Patterns/Chinese/Chinese-DateTime.yaml, Specs/DateTime/Chinese/DateExtractor.json, Specs/DateTime/Chinese/DateParser.json
=> Extend weekday extraction in Chinese

.NET/Microsoft.Recognizers.Definitions/English/NumbersDefinitions.cs, JavaScript/packages/recognizers-number/src/resources/englishNumeric.ts, Patterns/English/English-Numbers.yaml, Specs/Number/English/NumberModel.json, Specs/Number/English/OrdinalModel.json
=> fix bug ”a first” is wrongly recognized as a fraction number

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateExtractorConfiguration.cs, JavaScript/packages/recognizers-date-time/src/dateTime/baseDate.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/frenchDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts, Patterns/English/English-DateTime.yaml, Patterns/French/French-DateTime.yaml, Patterns/German/German-DateTime.yaml, Patterns/Portuguese/Portuguese-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DatePeriodParser.json
=> Fix incorrect daterange resolution

.NET/Microsoft.Recognizers.Definitions/BasePhoneNumbers.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Microsoft.Recognizers.Text.DataDrivenTests.csproj, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Sequence/TestSequence_English.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/TestHelpers.cs, .NET/Microsoft.Recognizers.Text.Sequence/Constants.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/PhoneNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/PhoneNumberParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/Extractors/BasePhoneNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/Extractors/BaseSequenceExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/AbstractSequenceModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Parsers/BaseSequenceParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/SequenceRecognizer.cs, .NET/Samples/SimpleConsole/Program.cs, .NET/Samples/SimpleConsole/SimpleConsole.csproj, JavaScript/test/runner-sequence.js, JavaScript/test/runner.js, Patterns/Base-PhoneNumbers.yaml, Specs/Sequence/English/PhoneNumberModel.json
Github issue: https://github.com/Microsoft/Recognizers-Text/issues/310
- Add extractor and parser for phone numbers, with simple parser output.
- Add tests for normal phone number patterns in Brazil, UK, Germany,
Chile and Argentina, also some invalid tests.
- Modify SimpleConsole to support phone number recognize in it.
=> Support basic/typical phone number recognition

.NET/Microsoft.Recognizers.Definitions.Common/Microsoft.Recognizers.Definitions.Common.csproj, .NET/Microsoft.Recognizers.Definitions/Microsoft.Recognizers.Definitions.csproj, .NET/Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.csproj, .NET/Microsoft.Recognizers.Text.Sequence/Microsoft.Recognizers.Text.Sequence.csproj, .NET/Samples/SimpleConsole/SimpleConsole.csproj
- Cleanup;
- A little more robust, but this needs a better solution later.
=> Moving post build to robocopy 

.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/FormatUtil.cs, Specs/DateTime/English/DateTimeModelCalendarMode.json
=> Fix WeekOf timex to ISO week number.

JavaScript/packages/recognizers-date-time/src/dateTime/chinese/timePeriodConfiguration.ts
Change the ChineseTimePeriodParser Parse return type to be consistent with others.
=> Change the ChineseTimePeriodParser Parse return type

JavaScript/lerna.json, JavaScript/packages/recognizers-date-time/package.json, JavaScript/packages/recognizers-number-with-unit/package.json, JavaScript/packages/recognizers-number/package.json, JavaScript/packages/recognizers-options/package.json, JavaScript/packages/recognizers-text-suite/package.json, JavaScript/packages/recognizers-text/package.json
RC version bump for NPM packages 32
=> RC version bump for NPM packages 32

README.md
Add entry points to C# and JavaScript repository in main README
=> Add links to C# and JavaScript in main README

.NET/CreateAllPackages.cmd, .NET/Microsoft.Recognizers.Text.Choice/ChoiceOptions.cs, .NET/Microsoft.Recognizers.Text.Choice/ChoiceRecognizer.cs, .NET/Microsoft.Recognizers.Text.Choice/Config/IChoiceParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Choice/CreatePackage.cmd, .NET/Microsoft.Recognizers.Text.Choice/English/Extractors/EnglishBooleanExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.Choice/Extractors/ChoiceExtractor.cs, .NET/Microsoft.Recognizers.Text.Choice/Extractors/IChoiceExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.Choice/Microsoft.Recognizers.Text.Choice.csproj, .NET/Microsoft.Recognizers.Text.Choice/Microsoft.Recognizers.Text.Choice.nuspec, .NET/Microsoft.Recognizers.Text.Choice/Models/BooleanModel.cs, .NET/Microsoft.Recognizers.Text.Choice/Models/ChoiceModel.cs, .NET/Microsoft.Recognizers.Text.Choice/Parsers/ChoiceParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
- Adding nuget package spec and create scripts;
- Adding netstandard2.0 target;
- Renaming ChoiceRecognizerOptions.cs to match class name;
- Very minor cleanup.
=> Assets to create Choice nuget package and target netstandard2.0

.NET/Microsoft.Recognizers.Text.Choice/Properties/AssemblyInfo.cs, JavaScript/lerna.json, JavaScript/packages/recognizers-choice/package.json, JavaScript/packages/recognizers-date-time/package.json, JavaScript/packages/recognizers-number-with-unit/package.json, JavaScript/packages/recognizers-number/package.json, JavaScript/packages/recognizers-sequence/package.json, JavaScript/packages/recognizers-text-suite/package.json, JavaScript/packages/recognizers-text/package.json
- Adding missing assemblyInfo.cs to Choice project as required for code signing process;
- Bumping NPM package versions to 1.0.0 as this will be the first public release of the packages.
=> Packaging changes for nuget and NPM

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestDecimalAndThousandsSeparators.cs, .NET/Microsoft.Recognizers.Text.Number/English/Extractors/NumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/English/Parsers/EnglishNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/French/Parsers/FrenchNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/German/Parsers/GermanNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/INumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Portuguese/Parsers/PortugueseNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Spanish/Parsers/SpanishNumberParserConfiguration.cs, JavaScript/packages/recognizers-number/src/number/english/extractors.ts, JavaScript/packages/recognizers-number/src/number/english/parserConfiguration.ts, JavaScript/packages/recognizers-number/src/number/extractors.ts, JavaScript/packages/recognizers-number/src/number/french/parserConfiguration.ts, JavaScript/packages/recognizers-number/src/number/parsers.ts, JavaScript/packages/recognizers-number/src/number/portuguese/parserConfiguration.ts, JavaScript/packages/recognizers-number/src/number/spanish/parserConfiguration.ts, JavaScript/packages/recognizers-number/src/resources/frenchNumeric.ts, JavaScript/packages/recognizers-number/src/resources/portugueseNumeric.ts, JavaScript/packages/recognizers-number/src/resources/spanishNumeric.ts, Specs/Number/English/NumberModel.json, Specs/Number/English/NumberRangeModel.json, Specs/Number/English/PercentModel.json
=> Support negative written numbers in English

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DatePeriodParser.json
=> Support year's quarters in format Q[1-4]

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoiceRecognizerInitialization.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_Japanese.cs, Specs/Choice/Japanese/BooleanModel.json
Progress
1.add TestChoice_Japanese.cs
=> Adding the Japanese test cases for choice

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs, Specs/DateTime/English/TimePeriodParser.json
GitHub issue https://github.com/Microsoft/Recognizers-Text/issues/386
=> Fix 4:00 - 5:00 pm interpreted as 4am to 5pm

JavaScript/packages/recognizers-date-time/src/dateTime/baseTimePeriod.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/timePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/timePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/timePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/timePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts, Specs/DateTime/English/TimePeriodExtractor.json, Specs/DateTime/English/TimePeriodParser.json
GitHub issue #386
And port missing TimePeriod functionality from .NET to JavaScript port.
=> Fix bug #386 in TypeScript and port missing TimePeriod features from .NET port

.NET/Microsoft.Recognizers.Text.Choice/Microsoft.Recognizers.Text.Choice.nuspec, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs, .NET/Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.csproj, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.csproj, .NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.nuspec, JavaScript/packages/recognizers-choice/package.json, JavaScript/packages/recognizers-date-time/package.json, JavaScript/packages/recognizers-number-with-unit/package.json, JavaScript/packages/recognizers-number/package.json, JavaScript/packages/recognizers-sequence/package.json, JavaScript/packages/recognizers-text-suite/package.json, JavaScript/packages/recognizers-text/package.json
- Moving dependency declarations to the correct project and nuget base package;
- Fixing package descriptions and keywords for nuget and npm.
=> Fixes to package declarations

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedParser.cs, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
- Removing "Debug" tag from tests;
- Minor formatting changes.
=> Adding more test cases to 'May' filter

.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.sln
Temp solution until the proper fix is in place for the problem from PR #400.
=> Removing DataTypes C# port from solution as workaround for build break

JavaScript/packages/recognizers-number/src/number/chinese/parsers.ts, Specs/Number/Chinese/NumberModel.json
=> [JS] Fix Chinese negative number issue in "负\d+" format. - From #362

Python/build.cmd, Python/libraries/recognizers-number/recognizers_number/number/chinese/__init__.py, Python/libraries/recognizers-number/setup.py, Python/libraries/recognizers-text/setup.py, appveyor.yml
**Changelog:**
- Include Python on continuous integration process.
- Minor tweaks for PyPI release.
=> [Python] Include Python on continuous integration process

.NET/Microsoft.Recognizers.Text.Choice/Extractors/ChoiceExtractor.cs, .NET/Microsoft.Recognizers.Text.Choice/Utilities/UnicodeUtils.cs
Moved the ` Letters()`  and ` IsEmoji()` methods from ChoiceExtractor to a static class within 
the Microsoft.Recognizers.Text.Choice project.
=> Move unicode methods in a separate Utilities.UnicodeUtils

Python/README.md, Python/libraries/recognizers-number/MANIFEST.in, Python/libraries/recognizers-number/README.rst, Python/libraries/recognizers-number/setup.py, Python/samples/README.md, Python/samples/simple_console/requirements.txt
Applied feedback to Python Recognizers:
- Update readme to rst files and include the content as package description
- Update manual build steps to include local package installation
- Update API Documentation section to show the result objects
- Update Integration tips messaging for external uses with no background
- Update sample's requirements.txt to install project dependencies
=> [Python] Apply Recognizers feedback

.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimeAltParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimeAltParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeAltParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimeAltParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimeAltParserConfiguration.cs, Specs/DateTime/English/DateTimeModelExtendedTypes.json
=> Support "period or next" in English

.NET/Microsoft.Recognizers.Definitions/Chinese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/French/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Portuguese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Spanish/NumbersDefinitions.cs, JavaScript/packages/recognizers-number/src/resources/chineseNumeric.ts, JavaScript/packages/recognizers-number/src/resources/frenchNumeric.ts, JavaScript/packages/recognizers-number/src/resources/portugueseNumeric.ts, JavaScript/packages/recognizers-number/src/resources/spanishNumeric.ts, Patterns/Chinese/Chinese-Numbers.yaml, Patterns/French/French-Numbers.yaml, Patterns/Portuguese/Portuguese-Numbers.yaml, Patterns/Spanish/Spanish-Numbers.yaml, Specs/NumberWithUnit/Chinese/AgeModel.json, Specs/NumberWithUnit/English/AgeModel.json, Specs/NumberWithUnit/French/AgeModel.json, Specs/NumberWithUnit/French/DimensionModel.json, Specs/NumberWithUnit/German/AgeModel.json, Specs/NumberWithUnit/Portuguese/AgeModel.json, Specs/NumberWithUnit/Portuguese/DimensionModel.json, Specs/NumberWithUnit/Spanish/AgeModel.json, Specs/NumberWithUnit/Spanish/DimensionModel.json
GitHub issue #426 
- revise regexes
- add tests
- fix `NumbersWithDozen2Suffix` in `Portuguese/NumbersDefinitions.cs`
=> Fix number range wrongly recognized as negative number.

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs, Specs/DateTime/English/DateTimeModel.json
GitHub issue #425 
- add tests
=> Fixed bug when extracting multi-DatePeriod

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DatePeriodParser.json
=> Fix date range recognition error in English

.NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberRangeExtractor.cs, Specs/Number/English/NumberRangeModel.json
Partial fix for GitHub issue #441 
Fraction side of fix in a following PR.
=> Fix fraction number wrongly recognized in number range model

.NET/Microsoft.Recognizers.Text.Number/English/Parsers/EnglishNumberParserConfiguration.cs, JavaScript/packages/recognizers-number/src/number/english/parserConfiguration.ts, Python/libraries/recognizers-number/recognizers_number/number/english/parsers.py, Specs/Number/English/NumberModel.json
=> Support fraction numbers with dash in English

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimeAltExtractorConfiguration.cs, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelExtendedTypes.json
GitHub issue #454
- add tests
- minor: fix "July 1st, 17" extracted from "I'll go back July 1st, 17th times."
=> Support basic list of alternative DateTimes

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs, JavaScript/packages/recognizers-date-time/src/dateTime/baseDateTimePeriod.ts, Specs/DateTime/English/DateTimePeriodParser.json
=> Fix cases like "monday 8 to 9" returns a null resolution

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DatePeriodParser.json
=> Support "YYYY MM" in English DateTime

.NET/Microsoft.Recognizers.Definitions/BasePhoneNumbers.cs, .NET/Microsoft.Recognizers.Text.Sequence/Constants.cs, .NET/Microsoft.Recognizers.Text.Sequence/Extractors/BasePhoneNumberExtractor.cs, JavaScript/packages/recognizers-sequence/src/resources/basePhoneNumbers.ts, JavaScript/packages/recognizers-sequence/src/sequence/constants.ts, JavaScript/packages/recognizers-sequence/src/sequence/extractors.ts, Patterns/Base-PhoneNumbers.yaml, Specs/Sequence/English/PhoneNumberModel.json
=> Fix several cases wrongly recognized as phonenumber

.NET/Microsoft.Recognizers.Definitions/BaseURL.cs, JavaScript/packages/recognizers-sequence/src/resources/baseURL.ts, Patterns/Base-URL.yaml, Specs/Sequence/English/URLModel.json
=> Fix URL extraction error

.NET/Microsoft.Recognizers.Definitions/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/French/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/German/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Portuguese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Spanish/NumbersDefinitions.cs, JavaScript/packages/recognizers-number/src/resources/englishNumeric.ts, JavaScript/packages/recognizers-number/src/resources/frenchNumeric.ts, JavaScript/packages/recognizers-number/src/resources/portugueseNumeric.ts, JavaScript/packages/recognizers-number/src/resources/spanishNumeric.ts, Patterns/English/English-Numbers.yaml, Patterns/French/French-Numbers.yaml, Patterns/German/German-Numbers.yaml, Patterns/Italian/Italian-Numbers.yaml, Patterns/Portuguese/Portuguese-Numbers.yaml, Patterns/Spanish/Spanish-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/french_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/portuguese_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/spanish_numeric.py, Specs/Number/Chinese/PercentModel.json, Specs/Number/English/PercentModel.json, Specs/Number/French/PercentModel.json, Specs/Number/German/PercentModel.json, Specs/Number/Spanish/PercentModel.json
=> Fix percentage wrongly extracted in URL

.NET/Microsoft.Recognizers.Definitions/BasePhoneNumbers.cs, JavaScript/packages/recognizers-sequence/src/resources/basePhoneNumbers.ts, Patterns/Base-PhoneNumbers.yaml, Specs/Sequence/English/PhoneNumberModel.json
- add tests in http://formvalidation.io/validators/phone/
- fix phone number extraction for cases like "010-6228-8559" and " 010-62288559"
=> Better support phone number extraction

.NET/Microsoft.Recognizers.Text.Number/English/Extractors/DoubleExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/English/Extractors/IntegerExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/French/Extractors/DoubleExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/French/Extractors/IntegerExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/German/Extractors/DoubleExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/German/Extractors/IntegerExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, .NET/Microsoft.Recognizers.Text.Number/Portuguese/Extractors/DoubleExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Portuguese/Extractors/IntegerExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Spanish/Extractors/DoubleExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Spanish/Extractors/IntegerExtractor.cs, JavaScript/packages/recognizers-number/src/number/english/extractors.ts, JavaScript/packages/recognizers-number/src/number/french/extractors.ts, JavaScript/packages/recognizers-number/src/number/models.ts, JavaScript/packages/recognizers-number/src/number/portuguese/extractors.ts, JavaScript/packages/recognizers-number/src/number/spanish/extractors.ts, Python/libraries/recognizers-number/recognizers_number/number/english/extractors.py, Python/libraries/recognizers-number/recognizers_number/number/french/extractors.py, Python/libraries/recognizers-number/recognizers_number/number/models.py, Python/libraries/recognizers-number/recognizers_number/number/parsers.py, Python/libraries/recognizers-number/recognizers_number/number/portuguese/extractors.py, Specs/Number/English/NumberModel.json, Specs/Number/French/NumberModel.json, Specs/Number/German/NumberModel.json, Specs/Number/Portuguese/NumberModel.json, Specs/Number/Spanish/NumberModel.json
=> Support no break space as thousand mark in number

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimeExtractorConfiguration.cs, JavaScript/packages/recognizers-date-time/src/dateTime/english/timeConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/timeConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/timeConfiguration.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/frenchDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts, Patterns/English/English-DateTime.yaml, Patterns/French/French-DateTime.yaml, Patterns/German/German-DateTime.yaml, Patterns/Italian/Italian-DateTime.yaml, Patterns/Portuguese/Portuguese-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/English/TimeParser.json, Specs/DateTime/French/TimeParser.json, Specs/DateTime/German/TimeParser.json, Specs/DateTime/Portuguese/TimeParser.json, Specs/DateTime/Spanish/TimeParser.json
=> Fix "HH h MM" or "HHhMM" time format not extracted

JavaScript/packages/recognizers-number/src/number/parsers.ts, Python/libraries/recognizers-number/recognizers_number/number/parsers.py, Specs/Number/English/NumberModel.json
=> Fix number zero missing resolution in JavaScript and Python

JavaScript/packages/recognizers-choice/package.json, JavaScript/packages/recognizers-number-with-unit/package.json, JavaScript/packages/recognizers-number/package.json, JavaScript/packages/recognizers-sequence/package.json
=> Add missing tsconfig.json references

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs, JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts, Patterns/Chinese/Chinese-DateTime.yaml, Specs/DateTime/Chinese/DatePeriodExtractor.json, Specs/DateTime/Chinese/DatePeriodParser.json
#475 
"比 较 一 下 2009年"
"近 三 年"
"2009 年 到 2010 年"
=> Enhance recognition of Chinese datetime with spaces

.NET/Microsoft.Recognizers.Definitions/English/NumbersDefinitions.cs, JavaScript/packages/recognizers-number/src/resources/englishNumeric.ts, Patterns/English/English-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py, Specs/DateTime/English/DateExtractor.json, Specs/DateTime/English/DateParser.json, Specs/Number/English/NumberRangeModel.json
- minor fix grammer issues in test cases
- add tests
=> Extend EqualRegex in English

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/BaseMergedUnitExtractor.cs, Specs/NumberWithUnit/English/CurrencyModel.json
=> Improve the process of merging compound unit

.NET/Microsoft.Recognizers.Definitions/BasePhoneNumbers.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Microsoft.Recognizers.Text.DataDrivenTests.csproj, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Sequence/TestSequence_Portuguese.cs, .NET/Microsoft.Recognizers.Text.Sequence/Constants.cs, .NET/Microsoft.Recognizers.Text.Sequence/Extractors/BasePhoneNumberExtractor.cs, JavaScript/packages/recognizers-sequence/src/resources/basePhoneNumbers.ts, JavaScript/packages/recognizers-sequence/src/sequence/constants.ts, JavaScript/packages/recognizers-sequence/src/sequence/extractors.ts, Patterns/Base-PhoneNumbers.yaml, Specs/Sequence/English/PhoneNumberModel.json, Specs/Sequence/Portuguese/PhoneNumberModel.json
GitHub issue #540
- enable tests that currently supported
- enable tests for sequence in Portuguese
=> Revise phone number regex

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DatePeriodParser.json
=> Support "Later in the year" in English

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchCommonDateTimeParserConfiguration.cs, JavaScript/packages/recognizers-date-time/src/dateTime/french/baseConfiguration.ts, Specs/DateTime/French/DateParser.json
=> Fix ordinal date isn't recognized in French

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelCalendarMode.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/DateTimeModelExtendedTypes.json
When processing DateTimeAlt (ExtendedTypes), the check for connector should be more strict.
=> Fix bug for ComplexCalendar

.NET/Microsoft.Recognizers.Definitions/Chinese/NumbersDefinitions.cs, JavaScript/packages/recognizers-number/src/resources/chineseNumeric.ts, Patterns/Chinese/Chinese-Numbers.yaml, Specs/Number/Chinese/PercentModel.json
=> Fix Chinese NegativeNumberTermsRegexNum

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/AgoLaterUtil.cs, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/frenchDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateExtractor.json, Specs/DateTime/English/DateParser.json, Specs/DateTime/English/MergedExtractor.json, Specs/DateTime/English/MergedParser.json
=> Support cases like "two weeks from / after / before today"

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimeZoneExtractorConfiguration.cs
Fix test failed in the timezone string matcher, change the property implemented
=> Fix test failed in the TimeZone String Matcher

.NET/Microsoft.Recognizers.Definitions/BaseMention.cs, .NET/Microsoft.Recognizers.Definitions/BasePhoneNumbers.cs, .NET/Microsoft.Recognizers.Text.Sequence/Extractors/BasePhoneNumberExtractor.cs, JavaScript/packages/recognizers-sequence/src/resources/baseMention.ts, JavaScript/packages/recognizers-sequence/src/resources/basePhoneNumbers.ts, JavaScript/packages/recognizers-sequence/src/sequence/extractors.ts, Patterns/Base-Mention.yaml, Patterns/Base-PhoneNumbers.yaml, Specs/DateTime/English/DateParser.json, Specs/DateTime/English/DateTimeModel.json, Specs/Sequence/English/MentionModel.json
=> Revise mention extractor

Python/README.md, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/date_time_recognizer.py, Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/number_with_unit_recognizer.py, Python/libraries/recognizers-number/recognizers_number/number/__init__.py, Python/libraries/recognizers-number/recognizers_number/number/number_recognizer.py, Python/libraries/recognizers-suite/MANIFEST.in, Python/libraries/recognizers-suite/README.rst, Python/libraries/recognizers-suite/recognizers_suite/__init__.py, Python/libraries/recognizers-suite/setup.cfg, Python/libraries/recognizers-suite/setup.py, Python/samples/README.md, Python/samples/simple_console/requirements.txt, Python/samples/simple_console/sample.py, Python/tests/test_runner_datetime.py, Python/tests/test_runner_number.py, Python/tests/test_runner_number_with_unit.py
This pull-request depends on #616 
This PR includes Recognizer's Suite package ported to python.
=> [Python] Port Recognizer's Suite to Python

Python/build.cmd, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_dateperiod.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/constants.py, Python/tests/test_runner_datetime.py
Add missing mod property assert to datetime recognizer
=> Fix datetime asserts

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseSetExtractor.cs, JavaScript/packages/recognizers-date-time/src/dateTime/baseSet.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_set.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/french_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/portuguese_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/spanish_date_time.py, Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/SetExtractor.json
- minor: refine QuarterTermRegex
- add test cases
=> Fix bugs in DateTime's set extractor

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimePeriodParserConfiguration.cs, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/DateTimeModelSplitDateAndTime.json, Specs/DateTime/English/DateTimePeriodExtractor.json, Specs/DateTime/English/MergedParser.json
#655 
Cases like "1/1/2015 after 2" is not support in this PR
=> Merge Date and Time for cases like "1/1/2015 after 2:00"

.NET/Microsoft.Recognizers.Definitions/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Constants.cs, .NET/Microsoft.Recognizers.Text.Number/English/Extractors/MergedNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Extractors/BaseMergedNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs, .NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/BaseMergedUnitExtractor.cs, JavaScript/packages/recognizers-number/src/resources/englishNumeric.ts, Patterns/English/English-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py, Specs/Number/English/NumberModel.json
GitHub issue #322
- minor fix for compound units
- add tests
=> Basically support mixed written words and numerals in English

Specs/Number/English/NumberModel.json, Specs/Number/English/NumberModelPercentMode.json, Specs/Number/English/PercentModel.json, Specs/Number/English/PercentModelPercentMode.json, Specs/Number/French/NumberModel.json, Specs/Number/French/PercentModel.json, Specs/Number/German/NumberModel.json, Specs/Number/German/PercentModel.json, Specs/Number/Portuguese/NumberModel.json, Specs/Number/Portuguese/PercentModel.json, Specs/Number/Spanish/NumberModel.json, Specs/Number/Spanish/PercentModel.json
This PR is used to format part of specs for Numbers.
=> Format part of specs for Numbers

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDurationExtractorConfiguration.cs, .NET/Samples/SimpleConsole/Program.cs, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
This PR address issue #675
- add tests
- revise simple console
=> Fix bugs in extracting multiple durations

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs
- refactor code to move all logic of updating timex to be end inclusive inside method GenerateAlterTimex
- rename it to GenerateEndInclusiveTimex()
=> Refactor code in PR#700

Specs/DateTime/Korean/DateExtractor.json, Specs/DateTime/Korean/DateParser.json, Specs/NumberWithUnit/Korean/AgeModal.json, Specs/NumberWithUnit/Korean/AgeModel.json
korean test spec added 
* NumberWithUnit - AgeModal
* DateTime - DateExtractor
* DateTime - DateParser
=> Korean test specs added for Age and Date

Specs/Number/Korean/NumberModel.json, Specs/Number/Korean/NumberModelPercentMode.json, Specs/Number/Korean/NumberRangeModel.json, Specs/Number/Korean/OrdinalModel.json, Specs/Number/Korean/PercentModel.json, Specs/Number/Korean/PercentModelPercentMode.json
=> Add missing NotSupported tags for Korean test specs

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateTimeParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateParser.cs, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/date_parser_config.py, Specs/DateTime/Chinese/DateParser.json, Specs/DateTime/Chinese/DateTimeModel.json
=> Revise swift day in Chinese date parsing

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/MergedDateTimeExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/ExtractResultExtension.cs, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/merged_extractor.py
=> Revise Chinese merged extractor 

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs, JavaScript/packages/recognizers-date-time/src/dateTime/baseDateTimePeriod.ts, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_datetimeperiod.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/DateTimeModelExtendedTypes.json
Not supported in js and python for now.
=> Fix cases like "Tuesday or Wednesday from 10-4"

JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/constants.ts, JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/extractors.ts, JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/models.ts, JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/parsers.ts, JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/utilities.ts, JavaScript/packages/recognizers-text/src/parsers.ts, Specs/NumberWithUnit/English/CurrencyModel.json
- Fix GitHub issue (#752)
- Enable some English Currency tests in JavaScript
=> Fix JavaScript currency model

Specs/DateTime/Dutch/DateExtractor.json, Specs/DateTime/Dutch/DateParser.json, Specs/DateTime/Dutch/DateTimeExtractor.json, Specs/DateTime/Dutch/DateTimePeriodParser.json, Specs/DateTime/Dutch/DurationExtractor.json, Specs/DateTime/Dutch/DurationParser.json, Specs/DateTime/Dutch/HolidayExtractor.json, Specs/DateTime/Dutch/HolidayParser.json, Specs/DateTime/Dutch/SetExtractor.json, Specs/DateTime/Dutch/TimeExtractor.json, Specs/DateTime/Dutch/TimeParser.json, Specs/DateTime/Dutch/TimePeriodExtractor.json, Specs/DateTime/Dutch/TimeZoneParser.json
Add beginning of the Dutch DateTime specs. If you could keep this open for a few days, then I will have some Dutch people proofreading it since I already spotted some small mistakes. Will push the fixes asap this week.
(created by the Dutch MicrosoftNL employees 👍)
=> Add Dutch DateTime specs

.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs, JavaScript/packages/recognizers-number/src/number/cjkParsers.ts, Specs/Number/Japanese/NumberModel.json, Specs/Number/Japanese/PercentModel.json
"五百五" should output "505", not "550"
=> [dotNet+JavaScript]fix wrong output values like "五百五" in Japanese Number model

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishCommonDateTimeParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/ITimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/ICommonDateTimeConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimePeriodExtractorConfiguration.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
- Support AmbiguityFiltersDict for cases like "good morning"
- Fix cases like "between 7 and 9 PM EST"
=> Support AmbiguityFiltersDict for cases like "good morning"

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_English.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/TestHelpers.cs, .NET/Microsoft.Recognizers.Text.Number/English/Extractors/NumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs, Specs/Number/English/NumberModelExperimentalMode.json
Disable cases like "30000 in 2009"
=> [EN Number] Disable ambiguous fraction number

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/BaseCurrencyParser.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Utilities/DictionaryUtils.cs, Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/utilities/DictionaryUtils.java, JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/parsers.ts, JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/utilities.ts, Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/utilities.py, Specs/NumberWithUnit/English/DimensionModel.json
=> Fix letter case issue in number with unit

Specs/DateTime/Japanese/DateExtractor.json
DateExtractor.json in Japanese
=> Add Japanese DateTime specs

JavaScript/lerna.json, JavaScript/package-lock.json, JavaScript/package.json, JavaScript/test/browser-specs/index.js
Force `lerna@2.11.0` due to an issue with the license of future versions.
=> Use lerna 2.11.0 as default

JavaScript/package.json, JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, JavaScript/test/browser-specs/index.js
lerna decided to restore their old license (MIT)
=> Update lerna to use latest ver

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DatePeriodParser.json
=> [EN DatePeriod] Fix bug when processing  cases like "this decade"(#824)

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Dutch.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Dutch.cs, .NET/Microsoft.Recognizers.Text.DateTime/Config/BaseOptionsConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Config/IOptionsConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Dutch/Extractors/NumberRangeExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/English/Extractors/NumberRangeExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs
Minor edits related to readiness for new models
=> Improving consistency across model+culture registration

Specs/DateTime/Japanese/DateTimeParser.json
Add a DateTimeParser.json in Japanese.
=> Add Japanese/DateTimeParser.json

.NET/Microsoft.Recognizers.Definitions/Chinese/NumbersDefinitions.cs, Patterns/Chinese/Chinese-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/resources/chinese_numeric.py, Specs/Number/Chinese/NumberRangeModel.json, Specs/Number/Chinese/NumberRangeModelExperimentalMode.json
=> [CN Number]Fix cases like "(在)10000与20000(之)间"(#657)

.NET/Microsoft.Recognizers.Definitions/Dutch/NumberDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Dutch.cs, .NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, Patterns/Dutch/Dutch-Numbers.yaml, Specs/Number/Dutch/NumberModelPercentMode.json, Specs/Number/Dutch/PercentModel.json, Specs/Number/Dutch/PercentModelPercentMode.json
- Added support for Dutch PercentModel in .NET
- Marked one case as NotSupported, since 'de' (the) is not a supported article yet
=> [NL Numbers] Support Dutch PercentModel in .NET

Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
=> Add test for cases like "year to date"

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs, JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts, Patterns/Chinese/Chinese-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py, Specs/DateTime/Chinese/DatePeriodExtractor.json, Specs/DateTime/Chinese/DatePeriodParser.json
=> Github Issue #598, fix wrong extraction like '帮我统计一下2010年之后2018年之前的销量'

.NET/Microsoft.Recognizers.Definitions/BasePhoneNumbers.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/PhoneNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/PhoneNumberParser.cs, JavaScript/packages/recognizers-sequence/src/resources/basePhoneNumbers.ts, JavaScript/packages/recognizers-sequence/src/sequence/english/extractors.ts, JavaScript/packages/recognizers-sequence/src/sequence/english/parsers.ts, Patterns/Base-PhoneNumbers.yaml, Specs/Sequence/English/PhoneNumberModel.json, Specs/Sequence/Portuguese/PhoneNumberModel.json
- Refine score function
- Add some cases generated by Faker to specs
- Support newly added cases and prevent extracting sequences start with '#' or look like hexadecimal
=> Refine phone number scoring function and add support to new cases

Patterns/Chinese/Chinese-DateTime.yaml
增加判斷 
WeekDayRegex: 週一 / 禮拜一
SpecialDayRegex: 後天 & 大後天"
=> [CN DateTime] Increase Statement for WeekDay and SpecialDay

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/English/TimeZoneDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Patterns/English/English-TimeZone.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/TimeZoneParser.json
- Synonyms and fix for European timezone resolutions;
- Adding synonym in timerange for 'since'.
=> Small fixes for European timezones

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Japanese.cs, .NET/Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.nuspec, .NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.nuspec, .NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs
- Updating Numbers and Units nuget package descriptions;
- Removing incorrectly registered Japanese model that are not yet ready.
=> Updating nuget packages for new release

.NET/Microsoft.Recognizers.Definitions/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Portuguese.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Spanish.cs, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/DateTime/Portuguese/DateTimeModel.json, Specs/DateTime/Spanish/DateTimeModel.json
=> Fixing DateTime PT regexes for days of week.

.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexHelpers.cs
=> [EN DateTimeV2] Fix TimexHelpers.ExpandDateTimeRange returns wrong end value

.NET/Microsoft.Recognizers.Definitions/French/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Utilities/DefinitionLoader.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Chinese/Extractors/ChineseNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Dutch/Extractors/DutchNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/EnglishNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/BaseMergedUnitExtractor.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/INumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/FrenchNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/GermanNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/ItalianNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Extractors/JapaneseNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/PortugueseNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/SpanishNumberWithUnitExtractorConfiguration.cs, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, JavaScript/packages/recognizers-number-with-unit/src/resources/frenchNumericWithUnit.ts, Patterns/English/English-DateTime.yaml, Patterns/French/French-NumbersWithUnit.yaml, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/NumberWithUnit/French/CurrencyModel.json
Issue #206. 
Moved existing filter code.
=> Fix "cent" wrongly extracted as currency from "pour cent" 

.NET/Microsoft.Recognizers.Definitions/BaseGUID.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/GUIDParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/GUIDModel.cs, JavaScript/packages/recognizers-sequence/src/resources/baseGUID.ts, JavaScript/packages/recognizers-sequence/src/sequence/english/parsers.ts, JavaScript/packages/recognizers-sequence/src/sequence/models.ts, Patterns/Base-GUID.yaml, Specs/Sequence/English/GUIDModel.json
- Support unformatted GUID sequence
- Support GUID extraction with more boundaries
- Score extracted GUID sequence according to formats and boundaries
=> GUID enhancement with more formats and score function

.NET/Microsoft.Recognizers.Text/Utilities/QueryProcessor.cs, Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/utilities/RegExpUtility.java, Python/libraries/resource-generator/lib/code_writer.py
- Minor cleanup in QueryProcessor in C#;
- Method to check Java version;
- Code formatting in Python resource code writer.
=> Few small miscellaneous changes

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDatetimeUtilityConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IDateExtractorConfiguration.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java
- Added BaseDateExtractor and its unit tests
- This PR is based on PR #955; only f3842d14fa95f1874aa7bef2c4d3850238d1a4a6 is specific to this PR
- Once PR #955 is merged, southworks will rebase with master
=> [Java][Datetime] Port BaseDateExtractor from C# to Java

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishHolidayExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseHolidayExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IHolidayExtractorConfiguration.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java
- Added BaseHolidayExtractor and its unit tests
- This PR is based on PR #955 (which includes datetime module's base structure)
- Once PR #955 is merged, we'll rebase with master
=> [Java][Datetime] Port BaseHolidayExtractor from C# to Java

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDatePeriodExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDatePeriodExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IDatePeriodExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/ResultIndex.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java, Specs/DateTime/English/DatePeriodExtractor.json
- Added BaseDatePeriodExtractor and its unit tests
- This PR is based on PR #958
- Once PR #958 is merged, southworks will rebase with master
=> [Java][Datetime] Port BaseDatePeriodExtractor from C# to Java

Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/utilities/RegExpUtility.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java
=> Fixing PR merge mistake with Java extractor tests

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateTimePeriodExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimeExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimePeriodExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IDateTimePeriodExtractorConfiguration.java, Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/utilities/StringUtility.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java, Specs/DateTime/English/DateTimePeriodExtractor.json
- Added BaseDateTimePeriodExtractor and its unit tests
- We disabled some tests that were broken after rebasing with latest master changes. We'll bring the new functionalities form C# to Java in another thread and PR.
- This PR is based on several PRs: #976 & #966.
=> [Java][Datetime] Port BaseDateTimePeriodExtractor from C# to Java

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/DateTimeModelExperimentalMode.json, Specs/DateTime/English/DateTimeModelExtendedTypes.json
Javascript and Python support are not part of this PR as this feature doesn't exist on other platforms.
=> Support cases like "next Monday or next Tuesday" in ComplexCalendar mode

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDateParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDurationParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/FormatUtil.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java, Specs/DateTime/English/DateParser.json
- Skipped 3 unsupported tests failing after master rebase.
- Re added Pattern.CASE_INSENSITIVE flag due to failing tests. Will remove them in another thread and PR.
- Include nit code format
=> [Java][Datetime] Port BaseDateParser from C# to Java

Specs/DateTime/Spanish/TimePeriodExtractor.json, Specs/DateTime/Spanish/TimePeriodParser.json
Hello, I find the division of a day quite confusing. I've established a different time division than that of the cases already there. Mine is:
por la mañana 8:00-12:00
por la tarde 13:00-20:00
por la noche 20:00-23:59
I don't understand either why the original cases define mediodía as 12:00-16:00. I've checked the Real Academia Española and other resources, maybe it's more like hours near 12:00.
Just a little comment. Thank you!
=> Add cases for TimePeriodExtractor & TimePeriodParser in Spanish

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimePeriodExtractor.java, Specs/DateTime/English/DateTimePeriodExtractor.json
Fixes DateTimePeriodExtractor's skipped tests
=> [Java][Recognizer-Text] Fix DateTimePeriodExtractor's skipped tests

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/Constants.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/DateTimeResolutionKey.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishMergedExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDateTimeAltParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishMergedParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimePeriodExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseTimePeriodExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateTimeAltParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateTimePeriodParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDateTimeAltParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IMergedParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/FormatUtil.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java, Specs/DateTime/English/MergedParser.json
- Ported BaseMergedParser & BaseDteTimeAltParser to Java
- Skipped tests not supported. We'll fix in another thread and PR.
=> [Java][Datetime] Port BaseMergedParser from C# to Java

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IDateExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/ConditionalMatch.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/RegexExtension.java, Specs/DateTime/English/DateExtractor.json
- Fix skipped tests for `DateExtractor` in **Java**.
=> [Java][DateTime] Fix DateExtractor's skipped test

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDatePeriodExtractor.java, Specs/DateTime/English/DatePeriodExtractor.json
- Enabled 6 unit tests and brought C# new logic to make them pass.
=> [Java][DateTime] Enable and Fix DatePeriodExtractor unit tests

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDurationExtractor.java, Specs/DateTime/English/DateTimeExtractor.json
- Enabled 4 unit tests and fix an issue related to `DurationExtractor`
=> [Java][DateTime] Enable and Fix DateTimeExtractor unit tests

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/Constants.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDurationParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimexUtility.java, Specs/DateTime/English/DurationParser.json
- Enabled 2 unit tests and fix an issue related to `DurationParser`.
=> [Java][DateTime] Enable and Fix DurationParser unit tests

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishCommonDateTimeParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishTimePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseTimePeriodParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/ICommonDateTimeParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/ITimePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimeOfDayResolutionResult.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimeZoneUtility.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimexUtility.java, Specs/DateTime/English/TimePeriodParser.json
- Enable 3 tests skipped in previous versions.
- Fix an issue related to `TimePeriod` parse method.
=> [Java][DateTime] Enable and Fix TimePeriod unit tests

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishMergedExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseMergedExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IMergedExtractorConfiguration.java, Specs/DateTime/English/MergedParser.json
- Enable 18 tests skipped in previous versions.
- Fix an issue related to `Merged` extractor.
=> [Java][DateTime] Enable and Fix Merged parser unit tests

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateTimePeriodExtractorChs.cs, .NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/DateTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs, .NET/Microsoft.Recognizers.Text/Extractors/IExtractor.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedParser.java, JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_merged.py, Specs/DateTime/English/DateTimeModelSplitDateAndTime.json
Github Issue #948
- Fix wrong boundary of subentity in DateTimeModelSplitDateAndTime
- Fix some typos
=> Fix wrong boundary of extracted subentities in DateTimeModelSplitDateAndTime

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs, JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts, Patterns/Chinese/Chinese-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py, Specs/DateTime/Chinese/DateTimeModel.json
Added "钟头“， “个钟头” into Chinese time unit.
=> Fix "半个钟头" and "一个钟头" cannot be recognized

.NET/Microsoft.Recognizers.Definitions/CommonDefinitions.ttinclude, .NET/Microsoft.Recognizers.Definitions/Dutch/NumberDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/French/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/German/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Italian/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Portuguese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions/Spanish/NumbersDefinitions.cs
=> [dotnet] Fix escape-char resolution in List

.NET/Build.CI.cmd, .NET/Build.cmd, .NET/Microsoft.Recognizers.Definitions/BuildResources.cmd, .NET/Microsoft.Recognizers.Definitions/CommonDefinitions.ttinclude, .NET/Microsoft.Recognizers.Definitions/Microsoft.Recognizers.Definitions.csproj
- Created script to process all T4 templates
- Removed T4 generator from csproj to disable auto-processing
- Include BuildResources as part of Build process
=> Add script to process T4 templates

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishCommonDateTimeParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishMergedParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimeAltExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseMergedDateTimeExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseTimeExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseTimePeriodExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/models/DateTimeModel.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateTimeAltParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateTimePeriodParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseTimeParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/MatchingUtil.java, Specs/DateTime/English/DateTimeModelComplexCalendar.json
- Enable 83 tests.
- Fix several issues with `ComplexCalendar` enable.
This PR is based on #1072. We'll rebase once it is merged.
=> [Java][DateTime] Enable and Fix DateTimeModel with ComplexCalendar unit tests

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianHolidayParserConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in ItalianHolidayParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishHolidayParserConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishHolidayParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchHolidayParserConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in FrenchHolidayParserConfiguration

.NET/Build.cmd
Use [vswhere](https://github.com/Microsoft/vswhere) in build.cmd to locate Visual Studio 2017 and to find MSBuild. 
- vswhere only works with Visual Studio 2017 Update 2 or newer installed, should we provide a fallback or add it as a dev environment requirement? I prefer no fallback
- Support Community & Professional Edition, instead of Enterprise edition only
- Fixes #1096
=> [Infra] Remove hardcoded MSBuild path & support VS Community Edition

Specs/DateTime/Dutch/DateExtractor.json, Specs/DateTime/Dutch/DateParser.json, Specs/DateTime/Dutch/DateTimeExtractor.json, Specs/DateTime/Dutch/DateTimePeriodParser.json, Specs/DateTime/Dutch/DurationExtractor.json, Specs/DateTime/Dutch/DurationParser.json, Specs/DateTime/Dutch/HolidayExtractor.json, Specs/DateTime/Dutch/HolidayParser.json, Specs/DateTime/Dutch/SetExtractor.json, Specs/DateTime/Dutch/TimeExtractor.json, Specs/DateTime/Dutch/TimeParser.json, Specs/DateTime/Dutch/TimePeriodExtractor.json, Specs/DateTime/Dutch/TimeZoneParser.json
To not clutter my upcoming PR for .NET DateTime implementation for Dutch, adding all required properties to the testcases.
- Add missing Start + Length properties to add Dutch DateTime tests (autogenerated)
=> [NL DateTime] Add Start + Length properties to Dutch DateTime tests

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimePeriodExtractorConfiguration.cs
Per https://github.com/Microsoft/Recognizers-Text/pull/1110#pullrequestreview-188887332
=> [StyleCop] Minor indentation fix in FrenchDateTimePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDurationExtractor.cs
- reordered methods
- removes extra lines
- added whitespaces
-  fixed variable casing
=> [StyleCop] Fix all StyleCop warnings in BaseDurationExtractor

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishMergedParserConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishMergedParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
- reordered usings and methods
=> [StyleCop] Fix all StyleCop warnings in BaseDatePeriodExtractor

.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDatePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in GermanDatePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDatePeriodExtractorConfiguration.cs
- reordered fields
- fix spacing
=> [StyleCop] Fix all StyleCop warnings in ItalianDatePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishDatePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDatePeriodExtractorConfiguration.cs
- reordered fields
- fix spacing
=> [StyleCop] Fix all StyleCop warnings in FrenchDatePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/AbstractYearExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs
- promote config protected field to property
=> [StyleCop] Fix all StyleCop warnings in AbstractYearExtractor

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/TimeExtractorChs.cs
- reordered fields and enums
- added comment spaces
=> [StyleCop] Fix all StyleCop warnings in TimeExtractorChs

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/TimeExtractor.cs
- reordered usings, enums and class
=> [StyleCop] Fix all StyleCop warnings in TimeExtractor

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimeExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimeExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in FrenchTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimeExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in PortugueseTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimeExtractorConfiguration.cs
=> [SyleCop] Fix all StyleCop warnings in SpanishTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianTimeExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in ItalianTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateExtractorChs.cs
=> [StyleCop] Fix all StyleCop warnings in DateExtractorChs

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DatePeriodExtractorChs.cs
=> [StyleCop] Fix all StyleCop warnings in DatePeriodExtractorChs

.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in SpanishDateExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishDateExtractorConfiguration

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/DateTimeOptions.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDatePeriodExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseMergedDateTimeExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDatePeriodParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/DateTimeParseResult.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimexUtility.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/Token.java, Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/parsers/BaseNumberParser.java, Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/ExtractResult.java, Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/Metadata.java, Java/libraries/recognizers-text/src/main/java/com/microsoft/recognizers/text/ParseResult.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeTest.java, Specs/DateTime/English/DateTimeModelExperimentalMode.json
Enable and fix issues with 58 skipped tests in `DateTimeModelExperimentalMode.json` in Java
---
This PR is based on #1077. We'll rebase once it is merged.
=> [Java][DateTime] Enable and Fix DateTimeModel with ExperimentalMode unit tests

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in PortugueseDateExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in ItalianDateExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in GermanDateExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in FrenchDateExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimeAltParserConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishDateTimeAltParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/SetParserChs.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishSetParserConfiguration.cs
- reordered constructor and methods
=> [StyleCop] Fix all StyleCop warnings in SetParserChs, EnglishSetParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimeExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in GermanDateTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimeExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishDateTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDurationParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDurationParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDurationParserConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishDurationParserConfiguration, FrenchDurationParserConfiguration, GermanDurationParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateTimeExtractorChs.cs
=> [StyleCop] Fix all StyleCop warnings in DateTimeExtractorChs

.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in SpanishDatePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDurationParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDurationParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDurationParserConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in ItalianDurationParserConfiguration, PortugueseDurationParserConfiguration, SpanishDurationParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/DateTimeExtractor.cs
=> [StyleCop] Fix all StyleCop warnings in DateTimeExtractor

.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimeExtractorConfiguration.cs
- added new lines
- removed extra parenthesis
=> [StyleCop] Fix all StyleCop warnings in SpanishDateTimeExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/DurationParser.cs
- reordered fields
- fixed variable names
- reordered child class
=> [StyleCop] Fix all StyleCop warnings in DurationParser

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDurationExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in ItalianDurationExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/DurationExtractor.cs
=> [StyleCop] Fix all StyleCop warnings in DurationExtractor

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDurationExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in FrenchDurationExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDurationExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishDurationExtractorConfiguration and GermanDurationExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDurationExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in PortugueseDurationExtractorConfiguration, SpanishDurationExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishSetExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in PortugueseSetParserConfiguration, SpanishSetParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateParserConfiguration.cs
=> [StyleCop] Fix StyleCop warnings in IDateParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimeParserConfiguration.cs
=> [StyleCop] Fix StyleCop warnings in IDateTimeParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/TimeParser.cs
=> [StyleCop] Fix StyleCop warnings in French TimeParser

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IFullDateTimeParserConfiguration.cs
- removed region
- reordered properties
=> [StyleCop] Fix StyleCop warnings in IFullDateTimeParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/ITimePeriodParserConfiguration.cs
=> [StyleCop] Fix StyleCop warnings in ICommonDateTimeParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Utilities/EnglishDatetimeUtilityConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishDatetimeUtilityConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Utilities/FrenchDatetimeUtilityConfiguration.cs
=> [StyleCop] Fix StyleCop warnings in FrenchDatetimeUtilityConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs
=> [StyleCop] Fix all StyleCop warnings in BaseDateTimeAltExtractor

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/SetExtractorChs.cs
=> [StyleCop] Fix all StyleCop warnings in SetExtractorChs

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchMergedParserConfiguration.cs
=> [StyleCop] Fix StyleCop warnings in FrenchMergedParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimeParserConfiguration.cs
=> [StyleCop] Fix StyleCop warnings in FrenchDateTimeParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishTimePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/ITimePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in ITimePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in FrenchTimePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianTimePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in ItalianTimePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateTimeParserChs.cs
- reordered using and props
- renamed private fields
=> [StyleCop] Fix all StyleCop warnings in DateTimeParserChs

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/TimePeriodExtractor.cs
=> [StyleCop] Fix all StyleCop warnings in TimePeriodExtractor

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in PortugueseTimePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimePeriodExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in SpanishTimePeriodExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimePeriodParserConfiguration.cs
=> [StyleCop] Fix StyleCop warnings in FrenchDateTimePeriodParserConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateTimePeriodParserChs.cs
- reordered using, props and methods
=> [StyleCop] Fix all StyleCop warnings in DateTimePeriodParserChs

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimeAltExtractorConfiguration.cs
- reordered using, props and methods
=> [StyleCop] Fix all StyleCop warnings in EnglishDateTimeAltExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishHolidayExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishHolidayExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs
=> [StyleCop] Fix all StyleCop warnings in EnglishMergedExtractorConfiguration

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/MergedDateTimeParserChs.cs
=> [StyleCop] Fix all StyleCop warnings in MergedDateTimeParserChs

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishMergedExtractorConfiguration.java
* Remove excess whitespace from Java SpanishMergedExtractorConfiguration
=> [Java][Datetime] Fix SpanishMergedExtractorConfiguration remove excess whitespace

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDateParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDateParserConfiguration.java
- Apply c# modifications to `IDateParserConfiguration`
- Apply changes to the files that where using the old implementation
=> [Java][Datetime] Update IDateParserConfiguration with C# changes

.NET/Microsoft.Recognizers.Text.Sequence/SequenceRecognizer.cs
-Reorder static members
-Reorder protected members
=> [StyleCop] Fix all the warnings in SequenceRecognizer

.NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/EmailExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/GUIDExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/HashTagExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/IpExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/MentionExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/PhoneNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Extractors/URLExtractor.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/EmailParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/GUIDParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/HashTagParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/IpParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/MentionParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/PhoneNumberParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/URLParser.cs
Fixed warnings:
- Spacing
- Accessors
- Variables names
=> [StyleCop] Fix all the warnings in SequenceEnglish

.NET/Microsoft.Recognizers.Text.Sequence/Models/AbstractSequenceModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/EmailModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/GUIDModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/HashTagModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/IpAddressModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/MentionModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/PhoneNumberModel.cs, .NET/Microsoft.Recognizers.Text.Sequence/Models/URLModel.cs
=> [Stylecop] Fix all the warnings in SequenceModels

.NET/Microsoft.Recognizers.Text/Extractors/IExtractor.cs, .NET/Microsoft.Recognizers.Text/Extractors/Metadata.cs
- Add space between properties
- Extract Metadata Class
=> [StyleCop] Fix all the warnings in IExtractor

.NET/Microsoft.Recognizers.Text/Models/ExtendedModelResult.cs, .NET/Microsoft.Recognizers.Text/Models/ModelResult.cs
- Add whitespace before comments
- Reorder methods and parameters
=> [StyleCop] Fix all the warnings in TextModels

.NET/Microsoft.Recognizers.Text/ModelFactory.cs
- Set public method before private
=> [StyleCop] Fix all the warnings in Text\ModelFactory

.NET/Microsoft.Recognizers.Text/Recognizer.cs
- Set public method before private
- Set Generic type constraints in their own line
=> [StyleCop] Fix all the warnings in Text\Recognizer

.NET/Microsoft.Recognizers.Text/Culture.cs
- Update variables CultureName and CultureCode to be properties
- Add space between properties
=> [StyleCop] Fix all the warnings in Text\Culture

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/TimePeriodFunctions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/TimePeriodParserChs.cs
- Classes were separated into different files.
- Reordered using statements.
- Added spaces and trailing commas when needed.
=> [StyleCop] Fix all warnings in TimePeriodParserChs

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/DatePeriodExtractor.cs
=> [StyleCop] Fix all warnings in DatePeriodExtractor file

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Models/NumberModel.cs
-Remove extra spaces
-Add trailing comma
-Put constructor initializer on its own line
=> [StyleCop] Fix warnings in TextNumberModels

.NET/Microsoft.Recognizers.Text.DateTime/Utilities/DateObjectExtension.cs
- Added parenthesis, spaces and trailing commas when needed.
=> [StyleCop] Fix all warnings in DateObjectExtension file

.NET/Microsoft.Recognizers.Text.DateTime/Utilities/ExtractResultExtension.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/RegexExtension.cs
- Added and removed parenthesis when needed.
=> [StyleCop] Fix all warnings in DateTime files

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianTimeParserConfiguration.cs
- Restore constructor deleted by mistake on #1280
=> [StyleCop] Restore ItalianTimeParserConfiguration constructor

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Properties/AssemblyInfo.cs
=> [StyleCop] Fix all warnings in file AssemblyInfo

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishMergedParserConfiguration.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java
**Note:** This branch is based on PR #1274. We will rebase once it is merged with master. 
---
- Port `MergedParser` to Java
=> [Java][Datetime] Port SpanishMergedParserConfiguration from C# to Java

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDateParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDateParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishCommonDateTimeParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishDurationParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishTimeParserConfiguration.java, Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimePeriodExtractor.json
- Reordered properties and methods
- Added spaces and trailing commas when needed
- Placed all regex parameters in one line
- Fixed spacing
=> [StyleCop] Fix warnings TextNumberDutch Extractors and Parsers

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/DateTimeRecognizer.java
- Activate spanish `DateTimeModel` tests
=> [Java][DateTime] Activate DateTimeModel tests for Spanish

.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConstantsEnglish.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConvertEnglish.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexRelativeConvertEnglish.cs
- TimexConstantsEnglish
- TimeConvertEnglish
- TimeRelativeConvertEnglish
=> [StyleCop] Fix warning in TimexExpression\English

.NET/Microsoft.Recognizers.Text.Choice/Models/BooleanModel.cs, .NET/Microsoft.Recognizers.Text.Choice/Models/ChoiceModel.cs
- Fix spacing
- Add trailing coma in multi-line initializers
=> [StyleCop] Fix all the warnings in Choice\Models

.NET/Microsoft.Recognizers.Text.Choice/Extractors/BooleanExtractor.cs, .NET/Microsoft.Recognizers.Text.Choice/Extractors/ChoiceExtractDataResult.cs, .NET/Microsoft.Recognizers.Text.Choice/Extractors/ChoiceExtractor.cs
- Add trailing coma
- Extract ChoiceExtractDataResult class
- Add spacing
- Remove parentheses
=> [StyleCop] Fix all the warnings in ChoiceExtractor

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs, .NET/Samples/SimpleConsole/Program.cs
- language fix in SampleConsole;
- minor rename and style warning fix.
=> Fix wrongly modified language in SampleConsole code

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseTimePeriodParser.java, Specs/DateTime/English/DateTimeModelComplexCalendar.json
**Note:** This branch is based on PR #1328. We will rebase once it is merged with master. 
---
- Enable tests
- Fix BaseTimePeriodParser
**Before**
**After**
=> [Java][Datetime] Fix ModelComplexCalendar tests

.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/AgeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/AreaExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/CurrencyExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/EnglishNumberWithUnitExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/LengthExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/SpeedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/TemperatureExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/VolumeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/WeightExtractorConfiguration.cs
- Fix spacing
- Reorder methods and properties
=> [StyleCop] Fix all the warnings in English Extractors

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/DateTimeModel.json
=> Support normalized query like "1990 s".

.NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/GUIDParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/English/Parsers/IpParser.cs, .NET/Microsoft.Recognizers.Text.Sequence/SequenceOptions.cs
- Fix parameter name to begin with lower-case
=> [Stylecop] Fix warnings in Test.Sequence project

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Utilities/DictionaryUtils.cs
- Braces should not be omitted
- Set parameters across multiple lines
=> [StyleCop ] Fix warnings in DictionaryUtils

.NET/Microsoft.Recognizers.Text/Extractors/Metadata.cs
- Add setters and getters to the fields
- Remove spacing
=> [StyleCop] Fix all the warnings in Metadata

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishTimeParserConfiguration.java
Start using RegexExtension to make the code clearer. Applied the same changes that were applied in PR #1003 
- Update SpanishTimeParserConfiguration
=> [Java][DateTime] Port Spanish Parsers latest changes in C#

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDatePeriodExtractorConfiguration.java
Fixed rangeConnectorRegex Pattern to public static in EnglishDatePeriodExtractorConfiguration class.
=> [Java][DateTime] Fixed rangeConnectorRegex Pattern to public static

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs
Refactor nested if-else sequence to start using a switch-case, and extract the whole task to a private method(ParseResult).
=> [DotNet][DateTime] Refactor nested if-else in BaseMergedDateTimeParser

Specs/DateTime/Dutch/DateParser.json
- Enable some tests
- Remove 2 tests which are not used in Dutch, language is incorrect
=> [.NET DateTime] Enable NL DateParser tests + remove 2 tests

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java, JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/DateTimeModelExperimentalMode.json, Specs/DateTime/English/MergedParser.json
For example, "After mid September", the modifier would be "after-mid".
This PR only enable this combination for .Net
=> Support combination of modifiers

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimePeriodExtractor.json
add the "h" suffix for "AtRegex" and "TimeRegex1"
=> fix "Estaré afuera desde las 16 h de 1 de ene de 2016 hasta hoy a las 17 h"

Specs/DateTime/Spanish/DateTimePeriodExtractor.json
The word "de" should be extracted here. "de" means from here.
=> fix a test spec. "de" means "from" here.

.NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/INumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Portuguese/Parsers/PortugueseNumberParserConfiguration.cs
- Rename local variable
- Reorder methods
- Remove regions
- Add spacing
=> [StyleCop]Fix all the remaining warnings in Number Project

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseMergedDateTimeParserConfiguration.cs
- Remove unused if statement from Japanese `MergeDateTimeParser` class
=> [dotnet] Remove unused code from MergedDateTimeParser

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimePeriodExtractor.json
Fix three test specs. These three specs are all in the pattern like "in the next/past 5 hours/mins..."
=> Fix TimeUnitRegex and RelativeTimeUnitRegex

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimePeriodExtractor.json
change TimeRegex3 from (tres min pasadas las)? 3.00 (pm) to (tres min pasadas las)? 3.00 (pm|h)
=> fix "Ocurrirá 1/1/2015 entre las 10 h y las 11.30 h" and "Ocurrirá desde las 10.30 h hasta las 15 h de 1/1/15"

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
Support for Javascript, Java and Python would be in the upcoming PRs.
=> Support cases like "Tuesday, Jan 15, 1:00 PM - 1:15 PM"

Python/libraries/recognizers-number/recognizers_number/number/extractors.py, Python/libraries/recognizers-number/recognizers_number/number/spanish/extractors.py, Specs/Number/Spanish/NumberModel.json
=> Fix number thousand mark escape issue in Python 

JavaScript/package-lock.json, JavaScript/package.json
Updating _lodash_ and _handlebars_ due to possible prototype pollution and _braces_ due to potential regex DOS.
=> Fixing JavaScript security issues flagged by GitHub

.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, .NET/Recognizers-Text.ruleset
This makes more clear what is discussed in #1493.
=> Minor code readability change in BaseNumberParser

.NET/Microsoft.Recognizers.Definitions.Common/German/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersDefinitions.cs, Patterns/German/German-Numbers.yaml, Patterns/Spanish/Spanish-Numbers.yaml, Specs/Number/German/PercentModel.json, Specs/Number/Spanish/OrdinalModel.json
=> Minor fixes for Spanish Ordinal and German Percent

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs
fixes #969 
(for the C# - we shouldn't close the issue out until we update the JavaScript)
=> add more resolutions for daterange

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexHelpers.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs, JavaScript/packages/datatypes-date-time/src/timexHelpers.js, JavaScript/packages/datatypes-date-time/src/timexResolver.js, JavaScript/packages/datatypes-date-time/test/timexResolver.spec.js
=> resolve last three weeks

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_English.cs, .NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs, Specs/Number/English/OrdinalModel.json, Specs/Number/English/OrdinalModelEnablePreview.json
add ordinal.relative into OrdinalEnablePreview
=> Hide new ordinal.relative behind Options flag

JavaScript/packages/recognizers-date-time/src/dateTime/baseDate.ts, JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/dateTimePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/datePeriodConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/datePeriodConfiguration.ts, Specs/DateTime/English/DatePeriodExtractor.json, Specs/DateTime/English/DatePeriodParser.json, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
=> JavaScript support for issue #1540 ("between now and date")

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_German.cs, .NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs, Specs/Number/German/OrdinalModel.json, Specs/Number/German/OrdinalModelEnablePreview.json
I'm not sure this is all there needs to be done; please inform me if I have to add more than this :)
=> Add German Ordinal.relative spec examples (#1555)

Python/CreateAllPackages.cmd, Python/build.ci.cmd, Python/libraries/recognizers-date-time/CreatePackage.cmd, Python/libraries/recognizers-number-with-unit/CreatePackage.cmd, Python/libraries/recognizers-number/CreatePackage.cmd, Python/libraries/recognizers-sequence/CreatePackage.cmd, Python/libraries/recognizers-text/CreatePackage.cmd, appveyor.yml
Update the Appveyor file in order to save the wheels packages of the python libraries as part of the build artifacts
- Update appveyor.yml file to save the python wheels packages in the build artifacts
- Add .cmd files to create python wheels package
To test these changes, we configured an Appveyor app connected to a test branch.
The artifacts are successfully being saved as part of the build result.
=> [Python] Update Appveyor CI to save the wheels package as build artifacts

Specs/DateTime/Dutch/DatePeriodExtractor.json, Specs/DateTime/Dutch/DatePeriodParser.json, Specs/DateTime/Dutch/DateTimeModel.json
Initial versions of DateTime DatePeriodExtractor and DatePeriodParser
=> Added Dutch DateTime specs, initial versions

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateParser.java, JavaScript/packages/recognizers-date-time/src/dateTime/baseDate.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/dateConfiguration.ts, JavaScript/packages/recognizers-text/src/utilities.ts, Specs/DateTime/English/DateExtractor.json, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
This PR adds support for relative cases previously in .NET (PR #1573).
TODO: Implement validateMatch as in .NET, left for future PR.
=> Propagate new relative datetime support from .NET to JS

.NET/Microsoft.Recognizers.Definitions.Common/English/TimeZoneDefinitions.cs, Patterns/English/English-TimeZone.yaml
Adding Barcelona and Bentonville to list of cities.
=> Minor: Adding Barcelona and Bentonville to city list for time zone extraction

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
Fix "Cortana find 30 minutes later this week"
Expected: Two entities, one for duration "30 minutes" and another one for "later this week"
=> Fix incorrectly tagged duration as datetime

Python/libraries/recognizers-text/recognizers_text/culture.py, Python/tests/runner.py
This will avoid build breaks as the one mentioned in #1567.
=> Minor: Make test Python runner handle UTF-8 BOM and declare new ongoing cultures

Specs/NumberWithUnit/Korean/CurrencyModel.json, Specs/NumberWithUnit/Korean/DimensionModel.json, Specs/NumberWithUnit/Korean/TemperatureModel.json
The requested extra cases for explicit USD, Korean units, and other Korean-specific cases will be added with the implementation in future PRs.
=> Korean NumbersWithUnit specs localized

Specs/Number/Turkish/NumberModel.json, Specs/Number/Turkish/NumberRangeModel.json, Specs/Number/Turkish/OrdinalModel.json, Specs/Number/Turkish/PercentModel.json
The requested extra cases for Turkish-specific cases will be added with the implementation in future PRs.
=> Turkish Number specs localized

Specs/DateTime/Dutch/DateExtractor.json, Specs/DateTime/Dutch/DateParser.json, Specs/DateTime/Dutch/DatePeriodExtractor.json, Specs/DateTime/Dutch/DatePeriodParser.json, Specs/DateTime/Dutch/DateTimeExtractor.json, Specs/DateTime/Dutch/DateTimeModel.json, Specs/DateTime/Dutch/DateTimeParser.json, Specs/DateTime/Dutch/DateTimePeriodExtractor.json, Specs/DateTime/Dutch/DateTimePeriodParser.json, Specs/DateTime/Dutch/DurationExtractor.json, Specs/DateTime/Dutch/DurationParser.json, Specs/DateTime/Dutch/HolidayExtractor.json, Specs/DateTime/Dutch/HolidayParser.json, Specs/DateTime/Dutch/MergedExtractor.json, Specs/DateTime/Dutch/SetExtractor.json, Specs/DateTime/Dutch/TimeExtractor.json, Specs/DateTime/Dutch/TimeParser.json, Specs/DateTime/Dutch/TimePeriodExtractor.json, Specs/DateTime/Dutch/TimePeriodParser.json
=> Dutch specs localized and filtered

Specs/Choice/Turkish/BooleanModel.json, Specs/DateTime/Turkish/DateExtractor.json, Specs/DateTime/Turkish/DateParser.json, Specs/DateTime/Turkish/DatePeriodExtractor.json, Specs/DateTime/Turkish/DatePeriodParser.json, Specs/DateTime/Turkish/DateTimeExtractor.json, Specs/DateTime/Turkish/DateTimeModel.json, Specs/DateTime/Turkish/DateTimeParser.json, Specs/DateTime/Turkish/DateTimePeriodExtractor.json, Specs/DateTime/Turkish/DateTimePeriodParser.json, Specs/DateTime/Turkish/DurationExtractor.json, Specs/DateTime/Turkish/DurationParser.json, Specs/DateTime/Turkish/HolidayExtractor.json, Specs/DateTime/Turkish/HolidayParser.json, Specs/DateTime/Turkish/MergedExtractor.json, Specs/DateTime/Turkish/MergedParser.json, Specs/DateTime/Turkish/SetExtractor.json, Specs/DateTime/Turkish/SetParser.json, Specs/DateTime/Turkish/TimeExtractor.json, Specs/DateTime/Turkish/TimeParser.json, Specs/DateTime/Turkish/TimePeriodExtractor.json, Specs/DateTime/Turkish/TimePeriodParser.json
Trukish DateTime
************************************************************
DateExtractor | added: 2 | not applicable: 69
DateParser | added: 10 | not applicable: 10
DatePeriodExtractor | added: 13 | not applicable: 15
DatePeriodParser | added: 2 | not applicable: 8
DateTimeExtractor | added: 0 | not applicable: 2
DateTimeModel | added: 1 | not applicable: 45
DateTimeParser | All localized from English counterpart 
DateTimePeriodExtractor | added: 1 | not applicable: 3
DateTimePeriodParser | added: 0 | not applicable: 3
DurationExtractor | added: 3 | not applicable: 5
DurationParser | All localized from English counterpart 
HolidayExtractor | added: 7 | not applicable: 1
HolidayParser | added: 0 | not applicable: 2
MergedExtractor | added: 0 | not applicable: 16
MergedParser | added: 0 …
=> Turkish specs localized.

Specs/Choice/Korean/BooleanModel.json, Specs/DateTime/Korean/DateExtractor.json, Specs/DateTime/Korean/DateParser.json, Specs/DateTime/Korean/DatePeriodExtractor.json, Specs/DateTime/Korean/DatePeriodParser.json, Specs/DateTime/Korean/DateTimeExtractor.json, Specs/DateTime/Korean/DateTimeModel.json, Specs/DateTime/Korean/DateTimePeriodExtractor.json, Specs/DateTime/Korean/DateTimePeriodParser.json, Specs/DateTime/Korean/DurationExtractor.json, Specs/DateTime/Korean/DurationParser.json, Specs/DateTime/Korean/HolidayExtractor.json, Specs/DateTime/Korean/HolidayParser.json, Specs/DateTime/Korean/MergedExtractor.json, Specs/DateTime/Korean/SetExtractor.json, Specs/DateTime/Korean/SetParser.json, Specs/DateTime/Korean/TimeExtractor.json, Specs/DateTime/Korean/TimeParser.json, Specs/DateTime/Korean/TimePeriodExtractor.json, Specs/DateTime/Korean/TimePeriodParser.json, Specs/NumberWithUnit/Korean/CurrencyModel.json, Specs/NumberWithUnit/Korean/DimensionModel.json, Specs/NumberWithUnit/Korean/TemperatureModel.json
KoreanChoice 
********************************************************************
BooleanModel | added: 0 | notapplicable: 1
KoreanDateTime 
********************************************************************
DateParser | added: 0 | corrected: 44
DatePeriodExtractor | added: 0 | corrected: 2
DatePeriodParser | added: 0 | corrected: 0
DateTimeExtractor | added: 0 | corrected: 1
DateTimeModel | added: 0 | corrected: 20
DateTimePeriodExtractor | added: 0 | corrected: 1
DateTimePeriodParser | added: 0 | corrected: 0
DurationExtractor | added: 0 | corrected: 3
DurationParser | added: 0 | corrected: 0
HolidayExtractor | added: 0 | corrected: 0
HolidayParser | added: 0 | corrected: 0
MergedExtractor | added: 0 | corrected: 29
SetExtractor | added: 0 | corrected: 0
SetParser | added: 0 | …
=> Korean specs localized

Specs/DateTime/Japanese/DateExtractor.json, Specs/DateTime/Japanese/DateParser.json, Specs/DateTime/Japanese/DatePeriodExtractor.json, Specs/DateTime/Japanese/DatePeriodParser.json, Specs/DateTime/Japanese/DateTimeExtractor.json, Specs/DateTime/Japanese/DateTimeModel.json, Specs/DateTime/Japanese/DateTimeParser.json, Specs/DateTime/Japanese/DateTimePeriodExtractor.json, Specs/DateTime/Japanese/DateTimePeriodParser.json, Specs/DateTime/Japanese/DurationExtractor.json, Specs/DateTime/Japanese/DurationParser.json, Specs/DateTime/Japanese/HolidayExtractor.json, Specs/DateTime/Japanese/HolidayParser.json, Specs/DateTime/Japanese/MergedExtractor.json, Specs/DateTime/Japanese/SetExtractor.json, Specs/DateTime/Japanese/SetParser.json, Specs/DateTime/Japanese/TimeExtractor.json, Specs/DateTime/Japanese/TimeParser.json, Specs/DateTime/Japanese/TimePeriodExtractor.json, Specs/DateTime/Japanese/TimePeriodParser.json, Specs/NumberWithUnit/Japanese/DimensionModel.json, Specs/NumberWithUnit/Japanese/TemperatureModel.json
Japanese   NumberWith
*****************************************************************
DimensionModel | added: 0 | notapplicable: 3
TemperatureModel | added: 0 | notapplicable: 8
Japanese Datetime
*****************************************************************
DatePeriodExtractor | added: 0 | not applicable: 6
DateTimeExtractor | added: 0 | not applicable: 2
DateTimeModel | added: 0 | not applicable: 4
DateTimePeriodExtractor | added: 0 | not applicable: 2
DateTimePeriodParser | added: 0 | not applicable: 2
DurationExtractor | added: 0 | not applicable: 0
DurationParser | added: 0 | not applicable: 0
HolidayExtractor | added: 0 | not applicable: 0
HolidayParser | added: 0 | not applicable: 0
DateExtractor | added: 0 | corrected: 31
DateParser | added: 0 | corrected: 63
DatePeriodParser …
=> Japanese Specs Localized

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateTimePeriodExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDateTimePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimeAltExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimePeriodExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IDateTimePeriodExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateTimePeriodParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDateTimePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDateTimePeriodExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishDateTimePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimeZoneUtility.java, Specs/DateTime/English/DateTimeModelComplexCalendar.json
=> support cases like "Thursday morning EST" in Java

Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
"monday the twenty seventh at six pm"
=> Adding new complex DataTime specs

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, Patterns/English/English-Numbers.yaml, Specs/Number/English/OrdinalModel.json, Specs/Number/English/OrdinalModelSuppressExtendedTypes.json
Fixes cases like "the one before the last"
=> Fix regression bug in ordinal.relative

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishCommonDateTimeParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDatePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDatePeriodParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/ICommonDateTimeParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDatePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/FrenchDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/PortugueseDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/SpanishDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishCommonDateTimeParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishDatePeriodParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimexUtility.java, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
Propagating from .Net in #1645.
=> [Java] Support "this calendar year"

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/FullDateTimeParser.cs, Specs/DateTime/Chinese/DateTimeModel.json, Specs/DateTime/Japanese/DateTimeModel.json
Fixes #1681. 
Add sourceEntity for Chinese and modify related specs.
=> [.NET] Adding sourceEntity for Chinese

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Turkish.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/AreaExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/LengthExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/SpeedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/TemperatureExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/VolumeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/WeightExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/AreaParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/DimensionParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/LengthParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/SpeedParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/TemperatureParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/VolumeParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/WeightParserConfiguration.cs, Patterns/Turkish/Turkish-NumbersWithUnit.yaml, Specs/NumberWithUnit/Turkish/DimensionModel.json
Dimension support. 
Passing: 45
Skipped: 2
Issue summary: 
- Partial match: "saatte 188 milden" -> Actual: 188 milden
-  500.000 varil düştü -> recognized as two numbers
=> [.NET] Turkish NumbersWithUnit (Dimension) support

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Turkish.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs, Patterns/Turkish/Turkish-NumbersWithUnit.yaml, Specs/NumberWithUnit/Turkish/DimensionModel.json, Specs/NumberWithUnit/Turkish/TemperatureModel.json
Temperature support. 
Passing: 31
Skipped: 1
Work in progress as same YAML is included in #1703.  once merged this will be updated to ready for review.
=> [.NET] Turkish NumbersWithUnit (Temperature) support

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseTimePeriodParser.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/packages/recognizers-date-time/src/dateTime/baseTimePeriod.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_timeperiod.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/TimePeriodParser.json, Specs/DateTime/French/TimePeriodParser.json
Support "later in the afternoon" same as "late afternoon"
=> [DateTime] Support "later in the afternoon"

JavaScript/.gitignore, JavaScript/.vscode/extensions.json, JavaScript/.vscode/settings.json
This ESLint extension should help to guide the contributors to a standard development process. This will prompt Visual Studio Code to suggest the installation of the ESLint extension automatically.
You can review the extension documentation [here]( https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).
- `.vscode/extensions.json`
- `.gitignore`: Added exception for the new file, but ignoring the rest of the folder.
- `.gitignore`: included exception for settings file (workspace).
- `.vscode/settings.json`: contains configuration for eslint validation (typescript).
You can see now eslint lint warnings in visual studio code.
This IDE integration should improve productivity. The warnings detected will also appear in the *Problems* window.
*IDE warning highlights* …
=> [Javascript] Suggest to contributor adding ESLint extension to VSCode

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersWithUnitDefinitions.cs, Patterns/Turkish/Turkish-Numbers.yaml, Patterns/Turkish/Turkish-NumbersWithUnit.yaml, Specs/Number/Turkish/NumberModel.json, Specs/NumberWithUnit/Turkish/DimensionModel.json, Specs/NumberWithUnit/Turkish/TemperatureModel.json
NumberModel: 123 passed, 3 skipped
TempratureModel: all passed
DimensionModel: 53 passed 1 skipped
=> [.NET] Turkish Numbers and NumbersWithUnit various small fixes

.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, Patterns/Italian/Italian-DateTime.yaml, Specs/DateTime/Italian/DurationExtractor.json, Specs/DateTime/Italian/DurationParser.json
=> [.NET] Italian DateTime Duration support

.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDateTimePeriodParserConfiguration.cs, Patterns/Italian/Italian-DateTime.yaml, Specs/DateTime/Italian/DateTimePeriodExtractor.json, Specs/DateTime/Italian/DateTimePeriodParser.json, Specs/DateTime/Italian/TimePeriodExtractor.json, Specs/DateTime/Italian/TimePeriodParser.json
All test cases pass except 2. 
Support for the 2 in a separate PR as the suggested solution modifies the BaseDateTimePeriodParser
=> [.NET] Italian DateTime DateTimePeriod support

Python/libraries/recognizers-number/recognizers_number/number/english/extractors.py, Specs/NumberWithUnit/English/DimensionModel.json
=> [EN Units] 1.6m isn't recognized (Python) #1519

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
=> [EN DateTimeV2] Contextual numbers interpreted as hours #1752

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/FrenchDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
=> [EN DateTimeV2] Failure to understand "Tuesday of Last Week" #1527

.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseSetExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/ISetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseSetParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/ISetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishSetExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishSetParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/SetHandler.cs, Patterns/Italian/Italian-DateTime.yaml, Specs/DateTime/Italian/DateTimeExtractor.json, Specs/DateTime/Italian/DateTimeParser.json, Specs/DateTime/Italian/SetExtractor.json, Specs/DateTime/Italian/SetParser.json
SetExtractor: 25 pass. 
SetParser: 27 pass. 
3 moved to DateTimeExtractor.
2 moved to DateTimeParser. 
***********************************************************************
work in progress because of the SetWeekDay change
=> [.NET] Italian DateTime Set support

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
=> [DE DateTimeV2] The datetimeV2 prebuilt entity does not recognize "um 13 uhr 20"

.NET/build.sh
=> [.NET] Support build script on Ubuntu Linux #1778

.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianCommonDateTimeParserConfiguration.cs, Patterns/Italian/Italian-DateTime.yaml, Specs/DateTime/Italian/DatePeriodExtractor.json, Specs/DateTime/Italian/DatePeriodParser.json, Specs/DateTime/Italian/DateTimeModel.json, Specs/DateTime/Italian/DateTimePeriodExtractor.json, Specs/DateTime/Italian/DateTimePeriodParser.json
All test cases pass
We modified some test cases:
-"Tornerò tra un'ora" was treated as "I'll go back next hour" but it means "I'll go back in an hour", so we changed the result accordingly and introduced the case "Tornerò la prossima ora" that corresponds to "I'll go back next hour"
-"Tornerò verso le 11", we treated this case as "I'll go back around 11" and added the case "Tornerò alle 11 circa" as counterpart of "I'll be back 11ish"
-"organizzami un appuntamento la mattina dalle 9 alle 10" translates to "organize a meeting from 9 to 10 in the morning" so we modified the result accordingly
=> [.NET] Italian DateTime DateTimeModel support

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
- Ignore the "May I" at the beginning of sentences. Such as “may” in “Ok, may I ask Cortana to help?”.
=> [DateTimeV2] Revise ambiguity "may" regex

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDatePeriodExtractorConfiguration.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DatePeriodParser.json, Specs/DateTime/German/DateTimeModel.json
=> [DE DateTimeV2] Imporve RelativeRegex and minor modify some regex

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimeAltExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishDateTimeAltExtractorConfiguration.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateTimeAltExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimeAltExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IDateTimeAltExtractorConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDateTimeAltExtractorConfiguration.java, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/DateTimeModelExtendedTypes.json
"ABC-12345-A1B2C3 this is yet to be submitted" would be recognized as "3 this" in ExtendType Mode.
=> [EN DateTimeV2] Avoid some wrong recognize, like "3 this"

Python/libraries/recognizers-text/recognizers_text/Matcher/aa_node.py, Python/libraries/recognizers-text/recognizers_text/Matcher/abstract_matcher.py, Python/libraries/recognizers-text/recognizers_text/Matcher/ac_automaton.py, Python/libraries/recognizers-text/recognizers_text/Matcher/match_result.py, Python/libraries/recognizers-text/recognizers_text/Matcher/match_strategy.py, Python/libraries/recognizers-text/recognizers_text/Matcher/matcher.py, Python/libraries/recognizers-text/recognizers_text/Matcher/matcher_abstract.py, Python/libraries/recognizers-text/recognizers_text/Matcher/node.py, Python/libraries/recognizers-text/recognizers_text/Matcher/number_with_unit_tokenizer.py, Python/libraries/recognizers-text/recognizers_text/Matcher/simple_tokenizer.py, Python/libraries/recognizers-text/recognizers_text/Matcher/string_matcher.py, Python/libraries/recognizers-text/recognizers_text/Matcher/token.py, Python/libraries/recognizers-text/recognizers_text/Matcher/tokenizer.py, Python/libraries/recognizers-text/recognizers_text/Matcher/trie_tree.py, Python/libraries/recognizers-text/setup.py, Python/tests/matcher/test_simple_tokenizer.py, Python/tests/matcher/test_string_matcher.py
Based on Microsoft.Recognizers.Text, we migrated the classes and tests, to have an implementation that matches the one in C#.
**High level**
- Add [multipledispatch](https://pypi.org/project/multipledispatch/) as a dependency in order to be able to implement [multimethods](https://en.wikipedia.org/wiki/Multiple_dispatch) for the `init` and `find` methods
- Add the folder `tests/matcher` with the implementation of the required tests for the library
- Modify the `setup.py` file to require multipledispatch
**Classes**
- AaNode
- AbstractMatcher
- AcAutomation
- MatchResult
- Node
- NumberWithUnitTokenizer
- SimpleTokenizer
- StringMatcher
- Token
- TrieTree
**Tests**
- StringMatcher
- SimpleTokenizer
=> [Python][Recognizers-Text] Matcher utilities

Python/libraries/recognizers-sequence/recognizers_sequence/sequence/extractors.py, Python/libraries/recognizers-text/recognizers_text/Matcher/matcher.py, Python/libraries/recognizers-text/recognizers_text/Matcher/node.py, Python/libraries/recognizers-text/recognizers_text/Matcher/string_matcher.py, Python/libraries/recognizers-text/recognizers_text/Matcher/trie_tree.py, Python/tests/matcher/test_string_matcher.py, Specs/Sequence/English/URLModel.json
Merge after #1795 
Add the usage of StringMatcher to implement the method `_is_valid_match()` correctly.
- Refactor the method `_is_valid_match()` to use a StringMatcher
- Add the property `tld_matcher` to store the matcher we will be using for BaseURL
- Enable missing tests
=> [Python][Sequence] Implement matcher utilities

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/FrenchDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/PortugueseDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/SpanishDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/frenchDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts, Patterns/German/German-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/french_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/portuguese_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/spanish_date_time.py, Specs/DateTime/German/DateTimeModel.json, Specs/DateTime/German/DateTimeModelCalendarMode.json, Specs/DateTime/German/TimePeriodExtractor.json
=> [DE DateTimeV2] Avoid recognizing single numbers as Time and fix "um viertel nach drei" case

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersWithUnitDefinitions.cs, Patterns/Turkish/Turkish-Numbers.yaml, Patterns/Turkish/Turkish-NumbersWithUnit.yaml, Specs/Number/Turkish/NumberModel.json, Specs/Number/Turkish/OrdinalModel.json, Specs/NumberWithUnit/Turkish/CurrencyModel.json
Additional requested fixes to Number and NumberWithUnit
Added relevant test cases to specs
=> [.NET] Turkish Number additional fixes

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/German/DateTimeModel.json
This fixes #1847 
Now only support in .NET
=> [DateTimeV2] Fix cases like "next monday to friday"

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
=> [DE DateTimeV2] Extend recognition to support prepositions "vor" and "nach" #1853

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/EnglishNumeric.java, JavaScript/packages/recognizers-number/src/resources/englishNumeric.ts, Patterns/English/English-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py, Specs/Number/English/NumberModel.json
Added the following test:
```
{
"Input": "hundred thousand dollars",
"Results": [
{
"Text": "hundred thousand",
"TypeName": "number",
"Resolution": {
"subtype": "integer",
"value": "100000"
},
"Start": 0,
"End": 15
}
]
}
```
and edited the regex to extract the number correctly.
=> [EN Numbers] Added and resolved new case

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/ChineseDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts, Patterns/Chinese/Chinese-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py, Specs/DateTime/Chinese/DateTimeModel.json, Specs/DateTime/Chinese/DateTimePeriodExtractor.json, Specs/DateTime/Chinese/DateTimePeriodParser.json
Fixes  #1879 and cases like "7月26日早间".
=> [CN DateTime V2] Time of day refinements, like for "早间"

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Turkish.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishTimeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishTimeParserConfiguration.cs, Patterns/Turkish/Turkish-DateTime.yaml, Specs/DateTime/Turkish/DateParser.json, Specs/DateTime/Turkish/TimeExtractor.json, Specs/DateTime/Turkish/TimeParser.json
(The yaml file includes the support for DatePeriod)
=> [.NET] Turkish DateTime Time support

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Turkish.cs, .NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDurationExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDurationExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishDurationExtractorConfiguration.cs, Patterns/Turkish/Turkish-DateTime.yaml, Patterns/Turkish/Turkish-Numbers.yaml, Specs/DateTime/Turkish/DurationExtractor.json, Specs/DateTime/Turkish/DurationParser.json
(The yaml file includes the support for DatePeriod and Time)
=> [.NET] Turkish DateTime Duration support

.NET/Microsoft.Recognizers.Definitions.Common/English/ChoiceDefinitions.cs, JavaScript/packages/recognizers-choice/src/resources/englishChoice.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/frenchDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts, Patterns/English/English-Choice.yaml, Specs/Choice/English/BooleanModel.json
=> [EN Choice] Add ChoiceRecognizer support for "Yup" and "Yeah"

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Turkish.cs, .NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/ITimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishTimePeriodParserConfiguration.cs, Patterns/Turkish/Turkish-DateTime.yaml, Specs/DateTime/Turkish/TimePeriodExtractor.json, Specs/DateTime/Turkish/TimePeriodParser.json
=> [.NET] Turkish DateTime TimePeriod support

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishSetParserConfiguration.cs, Patterns/Turkish/Turkish-DateTime.yaml, Specs/DateTime/Turkish/SetExtractor.json, Specs/DateTime/Turkish/SetParser.json
=> [.NET] Turkish DateTime Set support

.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs, .NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDateTimePeriodParserConfiguration.cs, Patterns/Turkish/Turkish-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/Turkish/DateTimePeriodExtractor.json, Specs/DateTime/Turkish/DateTimePeriodParser.json
=> [.NET] Turkish DateTime DateTimePeriod support

.NET/Microsoft.Recognizers.Definitions.Common/German/NumbersWithUnitDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/FrenchDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/PortugueseDateTime.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/SpanishDateTime.java, Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/resources/GermanNumericWithUnit.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/frenchDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/portugueseDateTime.ts, JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts, Patterns/German/German-NumbersWithUnit.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/french_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/portuguese_date_time.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/spanish_date_time.py, Specs/NumberWithUnit/German/TemperatureModel.json
Added entries for kelvin, celsius for better results in LUIS
=> [DE Unit] Update Temperature entries

.NET/Microsoft.Recognizers.Definitions.Common/BasePhoneNumbers.cs, .NET/Microsoft.Recognizers.Text.Sequence/Extractors/BasePhoneNumberExtractor.cs, JavaScript/packages/recognizers-sequence/src/sequence/extractors.ts, Patterns/Base-PhoneNumbers.yaml, Python/libraries/recognizers-sequence/recognizers_sequence/resources/base_phone_numbers.py, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/extractors.py, Specs/Sequence/English/PhoneNumberModel.json
=> [PhoneNumber] Avoid extracting SSN as PhoneNumber

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/EnglishNumeric.java, JavaScript/packages/recognizers-number/src/resources/englishNumeric.ts, Patterns/English/English-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py, Specs/Number/English/NumberModel.json
This reverts PR #1871 because of the performance drop it causes (~5%).
=> Revert (#1871) due to performance drop

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/BaseMergedUnitExtractor.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs
=> [.NET] Bug fix in BaseDatePeriodExtractor due to ExtractResults creation

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/date_extractor.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/date_parser.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/date_parser_config.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/datetime_extractor.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/datetime_parser.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/datetime_parser_config.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/merged_parser.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/constants.py, Python/libraries/recognizers-text/recognizers_text/meta_data.py, Python/samples/simple_console/sample.py, Specs/DateTime/Chinese/DateTimeModel.json
Fixes #1885.
- Add support for cases like "5天前" “5分钟前”.
- Enable test cases.
=>  [Python|CN DateTimeV2] Add support for relative cases like "5天前"

Python/libraries/recognizers-sequence/recognizers_sequence/sequence/chinese/extractors.py, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/config/__init__.py, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/config/base_phone_number_configuration.py, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/config/phone_number_configuration.py, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/english/__init__.py, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/english/extractors.py, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/portuguese/extractors.py, Specs/Sequence/Dutch/PhoneNumberModel.json, Specs/Sequence/French/PhoneNumberModel.json, Specs/Sequence/Italian/PhoneNumberModel.json, Specs/Sequence/Korean/PhoneNumberModel.json, Specs/Sequence/Spanish/PhoneNumberModel.json, Specs/Sequence/Turkish/PhoneNumberModel.json
Add BasePhoneNumberExtractorConfiguration in python
Remove useless methods.
Add Python support #1906
=> [Python] Add BasePhoneNumberExtractorConfiguration

Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateExtractor.json
Fix to match Saturday with its accent mark in Spanish
=> Fix pattern for Spanish Saturday accent mark

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/ChoiceDefinitions.cs, .NET/Microsoft.Recognizers.Text.Choice/ChoiceRecognizer.cs, Patterns/Hindi/Hindi-Choice.yaml, Specs/Choice/Hindi/BooleanModel.json
All cases passing. 
(ना) not being caught with word boundary due to diacritic.
=> [.NET] Hindi Choice support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersWithUnitDefinitions.cs, Patterns/Hindi/Hindi-NumbersWithUnit.yaml, Specs/NumberWithUnit/Hindi/AgeModel.json
Support for Hindi Age. 
(Bare-bone for now with disabled cases)
All test cases passing. 
Added 5 cases with code-mixing
**********************************************************************************************************
Work in progress as #1913 needs to be merged first.
=> [.NET] Hindi NumbersWithUnits Age support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersWithUnitDefinitions.cs, Patterns/Hindi/Hindi-NumbersWithUnit.yaml, Specs/NumberWithUnit/Hindi/TemperatureModel.json
Support for Hindi Temprature.
(Bare-bone for now with disabled cases)
All test cases passing.
Added 13 cases with code-mixing and Devanagari numerals
***********************************************************************************************************
Work in progress as #1913 needs to be merged first.
=> [.NET] Hindi NumbersWithUnits Temperature support

.NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, Specs/Number/Hindi/OrdinalModel.json
All ordinal cases pass. 
Added 24 case with code-mixing and Devanagari numerals. 
***************************************************************************************************
Work in progress as it includes base from #1913; and #1913 needs to be merged first.
=> [.NET] Hindi Numbers Ordinal support

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Constants.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDateParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/AgoLaterUtil.cs, Patterns/Turkish/Turkish-DateTime.yaml, Specs/DateTime/Turkish/DateExtractor.json, Specs/DateTime/Turkish/DateParser.json, Specs/DateTime/Turkish/DatePeriodExtractor.json, Specs/DateTime/Turkish/DatePeriodParser.json, Specs/DateTime/Turkish/DateTimeExtractor.json, Specs/DateTime/Turkish/DateTimeModel.json, Specs/DateTime/Turkish/DateTimeParser.json, Specs/Number/Turkish/OrdinalModel.json
DateTimeV2 validation
Fixes from DateTimeModel refinements
=> Turkish Enhancements

.NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs, Specs/NumberWithUnit/Hindi/AgeModel.json
=> [.NET] Hindi NumbersWithUnit Age support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, Patterns/Hindi/Hindi-Numbers.yaml, Specs/Number/Hindi/PercentModel.json
=> [.NET] Hindi Numbers Percent support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs, Patterns/Hindi/Hindi-Numbers.yaml, Patterns/Hindi/Hindi-NumbersWithUnit.yaml, Specs/NumberWithUnit/Hindi/DimensionModel.json
All test cases passing.
************************************************************************************************************
Notes: 
- We changed डेमी  to डेसीमीटर (Decimeter) as shortened डेमी is ambiguous in Hindi with Decameter. 
- We changed Megabite in "इस फ़ाइल का आकार 100 एमबी ह" to Megabyte as in Hindi there is no difference between MB and mb. 
- We added a \b to इं (in [inch]) because इं is ambiguous in Hindi and was being extracted within other strings e.g. इंटेल.
=> [.NET] Hindi NumbersWithUnit Dimension support

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_datetime.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_merged.py, Python/libraries/recognizers-text/recognizers_text/utilities.py
This PR ports the changes made on PR #1839  for .NET to Python.
**BaseDateTimeExtractor**
- `special_time_of_date` (logic changes) [#1893]
**BaseDateTimeParser**
- `parse_special_time_of_date` (logic changes) [#1893]
**BaseMergedExtractor**
- `try_merge_modifier_token` (remove duplicated method)
**RegExpUtility**
- `match_begin` (logic changes)
=> [Python] Port the changes on BaseDateTimeExtractor and BaseDateTimeParser

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/package-lock.json, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Patterns/German/German-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Python/libraries/recognizers-number/recognizers_number/resources/chinese_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/french_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/japanese_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/portuguese_numeric.py, Python/libraries/recognizers-number/recognizers_number/resources/spanish_numeric.py, Specs/DateTime/German/DateExtractor.json, Specs/DateTime/German/DateParser.json, Specs/DateTime/German/DateTimeModel.json
This fixes #1943 
- Fix cases like "den 28.Oktober" and "den 28.11.".
- Add test.
- Generate some missing YAML files.
=> [DE DateTimeV2] Fix cases like “für den [date]”

Specs/Sequence/Hindi/PhoneNumberModel.json
Specs for Hindi common phone numbers.
=> [Sequence PhoneNumber] Hindi PhoneNumber specs

Specs/Sequence/Turkish/PhoneNumberModel.json
Specs for Turkish common phone numbers.
=> [Sequence PhoneNumber] Turkish PhoneNumber specs

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_date.py
This PR ports the changes made on PR #1839 and PR #1936 for .NET to Python.
**BaseDateExtractor**
- `strip_inequality_prefix` to `strip_inequality` (logic changes) [#1888]
- `strip_inequality_duration` (logic changes) [#1888] + [#1936]
- `get_year_index` (logic changes) [#1936]
=> [Python] Port the changes on BaseDateExtractor

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishSetParserConfiguration.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishSetParserConfiguration.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/packages/recognizers-date-time/src/dateTime/english/setConfiguration.ts, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/english/set_parser_config.py, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/English/DateTimeModelExperimentalMode.json, Specs/DateTime/English/SetExtractor.json, Specs/DateTime/English/SetParser.json
- Support cases like "Let's have a quarterly meeting."
- Add tests.
=> [EN DateTime] Add support for "quarterly"

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts, Patterns/English/English-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py, Specs/DateTime/English/TimePeriodExtractor.json, Specs/DateTime/English/TimePeriodParser.json
- Add support for cases like "lunch time" "dinner time" "at dinner"
- Add test
=> [EN DateTimeV2] Add support for "lunch time" "at lunch"

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiTimePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs, Patterns/Hindi/Hindi-DateTime.yaml, Specs/DateTime/Hindi/DateTimeModel.json, Specs/DateTime/Hindi/TimePeriodExtractor.json, Specs/DateTime/Hindi/TimePeriodParser.json
All test cases passing.
In DateTimeModel: 4 cases passing, 80 failing.
=> [.NET] Hindi DateTime TimePeriod support

.NET/Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.xml, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs, JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/mergedConfiguration.ts, Specs/DateTime/English/DateTimeModel.json
- Avoid single years being extracted. 
- Revise Timex generate (.NET)
=> [EN Datetime] Revise DatePeriod Parser

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDatePeriodParserConfiguration.cs, Patterns/Hindi/Hindi-DateTime.yaml, Patterns/Hindi/Hindi-Numbers.yaml, Specs/DateTime/Hindi/DatePeriodExtractor.json, Specs/DateTime/Hindi/DatePeriodParser.json, Specs/DateTime/Hindi/TimeExtractor.json, Specs/DateTime/Hindi/TimeParser.json
DateTimeModel: 42 passing, 42 failing.
=> [.NET] Hindi DateTime DatePeriod support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiTimeExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDateTimeParserConfiguration.cs, Patterns/Hindi/Hindi-DateTime.yaml, Patterns/Hindi/Hindi-Numbers.yaml, Specs/DateTime/Hindi/DatePeriodParser.json, Specs/DateTime/Hindi/DateTimeExtractor.json, Specs/DateTime/Hindi/DateTimeParser.json, Specs/DateTime/Hindi/TimeExtractor.json, Specs/DateTime/Hindi/TimeParser.json, Specs/DateTime/Hindi/TimePeriodExtractor.json, Specs/DateTime/Hindi/TimePeriodParser.json
=> [.NET] Hindi DateTime DateTime support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDateTimePeriodParserConfiguration.cs, Patterns/Hindi/Hindi-DateTime.yaml, Patterns/Hindi/Hindi-Numbers.yaml, Specs/DateTime/Hindi/DateTimePeriodExtractor.json, Specs/DateTime/Hindi/DateTimePeriodParser.json, Specs/DateTime/Hindi/TimePeriodParser.json
Extractor: 52 passing, 16 failing;
Parser: 35 passing, 33 failing.
DateTimeModel: 46|38
=> [.NET] Hindi DateTime DateTimePeriod support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDateTimePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDateTimePeriodParserConfiguration.cs, Patterns/Hindi/Hindi-DateTime.yaml, Patterns/Hindi/Hindi-Numbers.yaml, Specs/DateTime/Hindi/DateTimePeriodExtractor.json, Specs/DateTime/Hindi/DateTimePeriodParser.json, Specs/DateTime/Hindi/MergedExtractor.json, Specs/DateTime/Hindi/MergedParser.json, Specs/DateTime/Hindi/TimePeriodParser.json
Extractor: all passing;
Parser: 35 passing, 21 failing.
DateTimeModel: 46|38
=> [.NET] Hindi DateTime Merged partial support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiTimePeriodExtractorConfiguration.cs, Patterns/Hindi/Hindi-DateTime.yaml, Patterns/Hindi/Hindi-Numbers.yaml, Specs/DateTime/Hindi/DatePeriodExtractor.json, Specs/DateTime/Hindi/DatePeriodParser.json, Specs/DateTime/Hindi/DateTimeModel.json, Specs/DateTime/Hindi/DateTimePeriodExtractor.json, Specs/DateTime/Hindi/DateTimePeriodParser.json, Specs/DateTime/Hindi/MergedExtractor.json, Specs/DateTime/Hindi/MergedParser.json, Specs/DateTime/Hindi/TimePeriodExtractor.json, Specs/DateTime/Hindi/TimePeriodParser.json
DateTimeModel: 67 passing, 17 failing.
=> [.NET] Hindi DateTime DateTimeModel complete support

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiTimePeriodExtractorConfiguration.cs, Patterns/Hindi/Hindi-DateTime.yaml, Patterns/Hindi/Hindi-Numbers.yaml, Specs/DateTime/Hindi/DatePeriodExtractor.json, Specs/DateTime/Hindi/DatePeriodParser.json, Specs/DateTime/Hindi/DateTimePeriodExtractor.json, Specs/DateTime/Hindi/DateTimePeriodParser.json, Specs/DateTime/Hindi/MergedExtractor.json, Specs/DateTime/Hindi/MergedParser.json, Specs/DateTime/Hindi/TimePeriodExtractor.json, Specs/DateTime/Hindi/TimePeriodParser.json
Notes:
- We have modified Period test cases to include in the extracted text prepositions such as "between", "to" "until",... Not including them was causing problems in Merged where these prepositions are matched as modifiers. 
- Some of the test cases in Merged have been modified to match the corresponding English case structure (when this is required to extract the same entities).
=> [.NET] Hindi DateTime Merged complete support

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/ChineseDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts, Patterns/Chinese/Chinese-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py, Specs/DateTime/Chinese/DateTimeModel.json
Avoid wrongly extracting date in CN in cases like "888-000-999"
- Revise regex.
=> [CN Sequence.Phone] Reduce phone number false positives in CN

Specs/DateTime/Spanish/DateTimeModel.json
- This is to check the result of #2039
=> [ES DateTime] Add Spanish spec tests for reported range issues

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/SpanishDateTime.java, JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts, Patterns/Spanish/Spanish-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/resources/spanish_date_time.py, Specs/DateTime/Spanish/DatePeriodExtractor.json
- Fix cases like "(206)555-1212"
=> [ES DateTimeV2] Avoid extracting date period from TEL

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs
=> Fix to handle invalid end date of YYYY-13-01(#2041)

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Chinese/Extractors/NumberExtractor.cs, Patterns/Chinese/Chinese-Numbers.yaml, Specs/Number/Chinese/NumberModel.json
I added the false positive filter for Chinese NumberExractor according to English NumberExtractor. For this, I added a AmbiguityFilterDict in Chinese NumbersDefinitions of Recognizers.Definitions.
=> [.NET Number] Add false positive filter for Chinese

.NET/Microsoft.Recognizers.Definitions.Common/Arabic/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Arabic.cs
- Enabling test execution for Ordinal and NumberRange in Arabic;
- Re-gen Arabic resources.
=> Minor: Pending edits over PR #2083

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/Portuguese/DateTimeModel.json
Fixes #2076 and build break due to #2088.
=> Fixes issue #2076 in PT

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/Portuguese/DateTimeModel.json
Fixes #2053.
Added processing for special day(like today/yesterday) to BaseDatePeriodParser of English, and also added specs tests to DateTimeModel.json and DateTimeModelComplexCalendar.json in English and Portuguese.
=> "Fix incorrect returned end year when today/now present in date range with a datepoint and different start year(#2053)

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersDefinitions.cs, Patterns/Chinese/Chinese-Numbers.yaml, Specs/Number/Chinese/NumberRangeModel.json
fix to bug #2047 for Chinese as requested in #2077
=> [.NET] Chinese NumberRange bug #2047 fix

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Chinese/Extractors/ChineseNumberWithUnitExtractorConfiguration.cs, Patterns/Chinese/Chinese-Numbers.yaml, Patterns/Chinese/Chinese-NumbersWithUnit.yaml, Specs/DateTime/Chinese/DateTimeModel.json, Specs/Number/Chinese/NumberModel.json, Specs/NumberWithUnit/Chinese/CurrencyModel.json, Specs/NumberWithUnit/Chinese/DimensionModel.json
Added specs to Chinese CurrencyModel.json, NumberModel.json, DimensionModel.json and DateTimeModel.json
Add AmbiguityFiltersDict to Chinese NumberWithUnit.yaml and ChineseNumberWithUnitExtractorConfiguration.cs
=> Refinements to false positives in Chinese units and datetime

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Japanese/Extractors/OrdinalExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs, Patterns/Japanese/Japanese-Numbers.yaml, Specs/Number/Japanese/OrdinalModel.json
- Spec (96) including Existing-12 and New-84
- Not supported: 8
- Ordinal Extractor improvement
=> [JA Ordinal] Improvements to coverage

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Dutch.cs, .NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchTimeParserConfiguration.cs, Patterns/Dutch/Dutch-DateTime.yaml, Specs/DateTime/Dutch/TimeExtractor.json, Specs/DateTime/Dutch/TimeParser.json
=> [.NET] Dutch DateTime Time support

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs, Patterns/Japanese/Japanese-Numbers.yaml, Specs/Number/Japanese/NumberModel.json
**PR Includes:**
- **Extractor:** Negative support for both Kanji and HW
- **Spec Update:** Removed NotSupported for fraction
- Included Number Definitions
=> [JA Fraction] Spec Update and Extractor - Negative support for both Kanji and HW

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
alternative solution to #1971.
Did not see any performance issue with this approach.
=> [EN DateTimeV2] Revise ImplicitDate fix

.NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberRangeExtractor.cs, Specs/Number/Hindi/NumberRangeModel.json, Specs/Number/Turkish/NumberRangeModel.json
Fix for Hindi (#2113) and Turkish (#1947) unsupported cases in NumberRangeModel.
The solution turned out to be simpler than expected.
=> [.NET] Hindi/Turkish Number NumberRange fix

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, Patterns/French/French-DateTime.yaml, Patterns/German/German-DateTime.yaml, Patterns/Italian/Italian-DateTime.yaml, Specs/DateTime/French/DateTimeModel.json, Specs/DateTime/German/DateTimeModel.json, Specs/DateTime/Italian/DateTimeModel.json
fix for bug #2123. 
The solution has been applied to German, French and Italian.
Relevant test cases added to DateTimeModel
=> [DE DateTimeV2] bug #2123 fix

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, Patterns/Hindi/Hindi-DateTime.yaml, Specs/DateTime/Hindi/DurationExtractor.json, Specs/DateTime/Hindi/DurationParser.json
Support for additional cases in Duration (6 in DurationExtractor, 13 in DurationParser).
=> [.NET] Hindi DateTime Duration enhancements

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Korean.cs, .NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/AgnosticNumberParserFactory.cs, Patterns/Korean/Korean-Numbers.yaml, Specs/Number/Korean/PercentModel.json
- Percentage Extractor
- Spec (Cases 30): Extraction Passed -30
- Existing: 15
- New: 15
=> [KO Percentage] Enabled Extractor and Spec Updates

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs, Patterns/Korean/Korean-Numbers.yaml, Specs/Number/Korean/OrdinalModel.json
- Ordinal Extractor
- Spec (Cases 51): Extraction Passed - 51
- Existing: 16
- New: 35
=> [KO Ordinal] Extractor and Spec Updates

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiTimePeriodParserConfiguration.cs, Patterns/Hindi/Hindi-DateTime.yaml, Specs/DateTime/Hindi/TimePeriodExtractor.json, Specs/DateTime/Hindi/TimePeriodParser.json
Support for additional cases in TimePeriod (10 in Extractor and 15 in Parser).
In DataTimeModel, 207 cases pass, 295 fail.
=> [.NET] Hindi DateTime TimePeriod enhancements

Specs/DateTime/English/DateTimeExtractor.json, Specs/DateTime/Hindi/DateTimeExtractor.json, Specs/DateTime/Hindi/DateTimeParser.json, Specs/DateTime/Hindi/TimePeriodExtractor.json
Support for additional cases in DateTime (20 in Extractor and 8 in Parser).
No changes in DataTimeModel.
=> [.NET] Hindi DateTime DateTime enhancements

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersDefinitions.cs, Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/chinese/extractors/NumberExtractor.java, JavaScript/packages/recognizers-number/src/number/chinese/extractors.ts, Patterns/Chinese/Chinese-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/number/chinese/extractors.py, Specs/Number/Chinese/NumberModel.json
Fix the issue #1792
Add some corner cases of Chinese Number to ambiguity filter;
Add test cases to Chinese NumberModel.json
=> [CN Number] Filter false positives in Chinese Number (#1792)

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs, Patterns/Korean/Korean-Numbers.yaml, Specs/Number/Korean/NumberModel.json
- Number Definitions 
- Integer and Fraction Extractor
**New Cases: 135**
- Integer 56: Extraction Passed-50, Skipped-6
- Fraction 58: Extraction Passed-58
- Decimal 9: Extraction Passed-9
- Power 2: Extraction Passed-2
- Negative 10 : Extraction Passed-4, Skipped-6
- Few cases identified earlier with comment:"As per language expert, input needs to be corrected" are updated.
=> [KO Number]  Number Coverage Improvement and Spec Updates

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Korean.cs, .NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/NumberRangeExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Korean/Parsers/KoreanNumberRangeParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs, Patterns/Korean/Korean-Numbers.yaml, Specs/Number/Korean/NumberRangeModel.json
- Number-Range Extractor
- Test Spec: Cases 122 (Extractor Passed - 71, Full Passed - 54, Skipped - 51)
**Existing Cases: 53**
- Extractor Passed: 23
- Full Passed: 19
- Skipped: 30
**New Cases: 69**
- Extractor Passed: 48
- Full Passed: 35
- Skipped: 21
=> [KO NumberRange] Extractor implementation and adding test specs

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Dutch/Parsers/DutchNumberParserConfiguration.cs, Patterns/Dutch/Dutch-Numbers.yaml, Specs/Number/Dutch/NumberModel.json, Specs/Number/Dutch/OrdinalModel.json
Support for 6 previously not supported cases in Ordinal.
=> [.NET] Dutch Ordinal enhancements

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs, Patterns/Japanese/Japanese-Numbers.yaml, Specs/Number/Japanese/OrdinalModel.json
- Specs
- OrdinalModel
- Ordinal Model Extractor
- Total Test Cases 96: (Extractor Passed - 96, Full Passed - 18, Skipped - 0)
- Existing Cases 12: Extractor Passed - 12, Full Passed - 12
- New Cases 84: Extractor Passed - 84, Full Passed - 6
=> [JA Ordinal] Coverage Improvements

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanTimeParserConfiguration.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json, Specs/DateTime/German/TimeParser.json
Fix to issue #2036.
Added relevant test cases to TimeParser and DateTimeModel.
=> [DE DateTimeV2] Enable recognition of dialectal clock expressions (#2036)

.NET/Microsoft.Recognizers.Definitions.Common/Arabic/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Arabic/Extractors/NumberRangeExtractor.cs, Patterns/Arabic/Arabic-Numbers.yaml, Specs/Number/Arabic/NumberModel.json, Specs/Number/Arabic/NumberRangeModel.json
- Specs
- NumberModel
- NumberRangeModel
- Number Model Extractor
- Total Cases 279: Extractor Passed - 138, Full Passed - 37, Skipped - 141
- New Cases 135: Extractor Passed - 130, Full Passed - 29, Skipped - 5
- Integer 48: Extraction Passed - 44, Full Passed - 7, Skipped - 4
- Fraction 56: Extraction Passed - 55, Full Passed - 12, Skipped - 1
- Decimal 9: Extraction Passed - 9
- Power 11: Extraction Passed - 11, Full Passed - 0, Skipped - 0
- Negative 11: Extraction Passed - 11, Full Passed - 11
- Number Range Model Extractor
- Total Test Cases 145: Extractor Passed - 105, Full Passed - 48, Skipped - 40
- New Cases 78: Extractor Passed - 64, Full Passed - 12, Skipped- 14
- Existing Cases 67: Extractor Passed - 41, Full Passed - 36, Skipped - 26
** …
=> [AR NumberRange] Coverage Improvements, Extractor and Spec Update

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs, Patterns/Hindi/Hindi-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json
Modify previous filter in FilterAmbiguity to make sure it's not overly aggressive.
=> [.NET] Improving previous false positive filter for dates surrounded by hyphens

Specs/DateTime/Hindi/SetExtractor.json, Specs/DateTime/Hindi/SetParser.json
Support for additional cases in Set (3 in Extractor and 1 in Parser).
=> [.NET] Hindi DateTime Set spec additions

.NET/Microsoft.Recognizers.Definitions.Common/French/NumbersDefinitions.cs, Patterns/French/French-Numbers.yaml, Specs/Number/French/NumberModel.json
fix to issue #471.
Added relevant test cases to French NumberModel.
=> [FR Number] Mixed number and words with dozen support (#471)

Specs/DateTime/Spanish/DateExtractor.json, Specs/DateTime/Spanish/DatePeriodExtractor.json, Specs/DateTime/Spanish/DatePeriodParser.json, Specs/DateTime/Spanish/DateTimePeriodExtractor.json, Specs/DateTime/Spanish/DateTimePeriodParser.json, Specs/DateTime/Spanish/DurationExtractor.json, Specs/DateTime/Spanish/TimePeriodExtractor.json, Specs/DateTime/Spanish/TimePeriodParser.json
Enable some Spanish DateTime test cases that can pass in .NET
=> [.NET] Enable passing test cases in Spanish DateTime

Script/Utils/countNotSupportedCases.py, Script/Utils/deleteNotSupportedPlatform.py, Script/Utils/getNotSupportedInput.py
Add python script for counting not supported cases in certain module;
Add python script for deleting the not supported flag of test cases for one platform;
Add python script for getting inputs which not supported for one platform;
=> Util scripts in Python to process specs (v0)

.NET/Microsoft.Recognizers.Text.Sequence/Extractors/BasePhoneNumberExtractor.cs, JavaScript/packages/recognizers-sequence/src/sequence/extractors.ts, Python/libraries/recognizers-sequence/recognizers_sequence/sequence/extractors.py, Specs/Sequence/English/PhoneNumberModel.json
Fix issue #2189.
This PR supersedes #2199.
=> [* PhoneNumber] Hotfix for credit card number wrongly detected as phone number

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimeModel.json
Added support for fiscal year in Spanish (#2212).
=> [ES DateTimeV2] Support for Fiscal year in Spanish (#2212)

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimeModel.json
Improved resolution for year ranges in Spanish (fixes #2211).
=> [ES DateTimeV2] Improve resolution for year ranges (#2211)

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs, Patterns/English/English-DateTime.yaml, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
Added support for expressions like "to/till date" in DatePeriod (#2054).
=> [EN DateTimeV2] Added support for "To/Till date" (#2054)

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/English/Extractors/NumberRangeExtractor.cs, .NET/Microsoft.Recognizers.Text.Number/Spanish/Extractors/NumberRangeExtractor.cs, Patterns/English/English-Numbers.yaml, Patterns/Spanish/Spanish-Numbers.yaml, Specs/Number/English/NumberRangeModel.json, Specs/Number/Spanish/NumberRangeModel.json
Fixes issue  #2214 (for both English and Spanish).
Added relevant test cases in NumberRangeModel.
=> [EN/ES NumberRange] Fixed compound disjoint range extraction (#2214)

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimeModel.json
Fix to issue #1835 for patterns like "inicio de mes", "fin de año".
=> [ES DateTimeV2] Added support for entities like "inicio de mes" (#1835)

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishMergedParserConfiguration.cs, Patterns/English/English-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
added support in .NET for cases like "from around 1pm" (#2243).
=> [EN DateTimeV2] Added support for text like "from around 1pm" (#2243)

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimeModel.json
Fixed null resolution for spec cases witch comment tag RANGECRIT (#2283).
Test cases re-enabled in .NET.
=> [ES DateTimeV2] Fixed null resolutions for ranges (#2283)

.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Chinese/Parsers/ChineseNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Constants.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Dutch/Parsers/DutchNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/EnglishNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Parsers/FrenchNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/GermanNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Hindi/Parsers/HindiNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/ItalianNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Parsers/JapaneseNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/AbstractNumberWithUnitModel.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/INumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/PortugueseNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/SpanishNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Swedish/Parsers/SwedishNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/TurkishNumberWithUnitParserConfiguration.cs, Specs/NumberWithUnit/English/DimensionModel.json
Added "subtype" attribute to Resolution field for Dimension units (#2097) in .NET.
=> [EN Unit Dimension] Added resolution of sub-types of dimension unit (#2097)

.NET/Microsoft.Recognizers.Definitions.Common/Italian/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Dutch/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Dutch/Parsers/DutchNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Parsers/FrenchNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/GermanNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Hindi/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Hindi/Parsers/HindiNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/ItalianNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/PortugueseNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/SpanishNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Swedish/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Swedish/Parsers/SwedishNumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Parsers/TurkishNumberWithUnitParserConfiguration.cs, Patterns/Italian/Italian-NumbersWithUnit.yaml, Specs/NumberWithUnit/Dutch/DimensionModel.json, Specs/NumberWithUnit/French/DimensionModel.json, Specs/NumberWithUnit/German/DimensionModel.json, Specs/NumberWithUnit/Hindi/DimensionModel.json, Specs/NumberWithUnit/Italian/DimensionModel.json, Specs/NumberWithUnit/Portuguese/DimensionModel.json, Specs/NumberWithUnit/Spanish/DimensionModel.json, Specs/NumberWithUnit/Swedish/DimensionModel.json, Specs/NumberWithUnit/Turkish/DimensionModel.json
Added "subtype" attribute to Resolution field for Dimension units (#2097) for NL/FR/DE/HI/IT/PT/ES/SV/TR.
=> [NL/FR/DE/HI/IT/PT/ES/SV/TR Unit Dimension] Added resolution of sub-types of dimension unit (#2097)

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishDatePeriodParserConfiguration.java, Specs/DateTime/Spanish/DateTimeModel.json
=> [ES DateTimeV2] Re-added support for relative suffixes in Java (#2322)

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
=> [DE DateTimeV2] "12 Uhr abends/nachts" recognized as midday time (#2335)

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
Added support for isolated occurrences of "weekends" in Set (#2326).
=> [EN DateTimeV2] Fixed "dinner with mom weekendS" still not recognized (#2326)

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateParserConfiguration.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimeModel.json
=> [ES DateTimeV2] Fixed incorrect entity boundaries / overly aggressive merging (#2285)

Specs/Number/Swedish/NumberModel.json
Adding missing specs for features introduced in PR #2351
=> [SV Number] Add missing specs for vulgar fractions

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimePeriodExtractorConfiguration.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/Spanish/DateTimeModel.json
=> [ES DateTimeV2] Added support for expressions like "el año anterior" (#2323)

.NET/Samples/SimpleConsole/Program.cs
Added encoding for exotic characters in SimpleConsole (#2361).
=> [.NET SimpleConsole] Added support for "€" symbol (#2361)

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeExtractor.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimeExtractor.java, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_datetime.py, Specs/DateTime/English/DateTimeModel.json
=> [EN DateTimeV2] Fixed "end of" by itself incorrectly extracted as entity (#2367)

Specs/DateTime/French/HolidayExtractor.json
Add 12 new specs to file for parity with English.
=> [FR DateTimeV2] Add new French specs for HolidayExtractor

Python/libraries/recognizers-text/recognizers_text/model.py, Python/samples/README.md
#2398 
* Implemented `__repr__`, `__str__`, and `get_dict` methods for the `ModelResult` class.
* Modify `README.md` for Python samples
=> [Python] Enrich convenience of ModelResult for visualization and dict result

.NET/Microsoft.Recognizers.Text.Number/Chinese/Parsers/ChineseNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Japanese/Parsers/JapaneseNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Korean/Parsers/KoreanNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/ICJKNumberParserConfiguration.cs
Hotfix probability mega problem caused by `ImmutableDictionary`, refer to #2365.
=> [ZH NumberRange] Fix to deal with hash order and collisions (#2365)

Tools/src/ValidationTool/ValidationTool.cs, Tools/src/ValidationTool/ValidationTool.csproj
1. Modify the error message.
2. Refactor runpipeline to separate validation and visualization.
3. Add the index automatic correction function, save the correct result to a new file.
=> [Tools] Spec validation tool v2

Tools/src/ValidationTool/ValidationTool.cs
Change log content.
Fix specs number log.
=> [Tools] Improving logs in validation tool output

Python/libraries/recognizers-text/recognizers_text/utilities.py, Python/libraries/recognizers-text/setup.py, Python/requirements.txt
fix emoji package dependency after breaking change in v1.0.
=> [Python] Fixing emoji package dependency after breaking change in v1.0

Specs/DateTime/French/DatePeriodExtractor.json, Specs/DateTime/French/DatePeriodParser.json, Specs/DateTime/French/TimeZoneParser
Add 352 French specs for DatePeriodExtractor,
remove duplicates :
ce week-end = this weekend, this weekend
Add 244 French specs for DatePeriodParser
=> [FR DateTimeV2] Add new French specs for DatePeriodExtractor/Parser

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexHelpers.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexHelpers.cs, .NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs
Fix recognize Timex for weeks like "2020-W23" in TimexHelper (#2160)
=> [TimexExpression] Fix recognize timex for weeks in TimexHelper (#2160)

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, Patterns/French/French-DateTime.yaml, Specs/DateTime/French/DateTimeModel.json
Fix to issue #2489.
Test cases added to French DateTimeModel.
=> [FR DateTimeV2] Fixed time resolved as datetime with time of day modifier (#2489)

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Spanish/DateTimeModel.json
Fixed the last failing case of the list (8 pm menos cuarto) in #2477.
=> [ES DateTimeV2] Fixed issues with time of day modifiers in Spanish like "de la mañana" vs. "am" (#2477)

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/DateTime/Portuguese/DateTimeModel.json
Fix to issue #2481. 
Added test case to DateTimeModel.
=> [PT DateTimeV2] Fixed "dia" breaking recognition of a full date value (#2481)

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/Portuguese/DateTimeModel.json, Specs/DateTime/Spanish/DateTimeModel.json
Fix to issue #2482 only for PT (ES was already working correctly).
Added test cases in EN, ES and PT DateTimeModels.
=> [PT DateTimeV2] Fixed weekday + date + time not resolved correctly (#2482)

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Dutch/Dutch-DateTime.yaml, Patterns/English/English-DateTime.yaml, Patterns/French/French-DateTime.yaml, Patterns/German/German-DateTime.yaml, Patterns/Italian/Italian-DateTime.yaml, Patterns/Portuguese/Portuguese-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
=> [EN DateTimeV2] Fixed false positives detecting abbreviated month name (#2527)

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, Patterns/French/French-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/French/DateTimeModel.json
Fix to issue #2486.
Test cases added to French and English DateTimeModels.
=> [FR DateTimeV2] Fixed inconsistency between French and English in extracting time+date entities (#2486)

Python/libraries/datatypes-timex-expression/datatypes_timex_expression/timex_helpers.py, Python/tests/datatypes/test_timex.py, Python/tests/datatypes/test_timex_resolver.py
=> [Python] TimexHelpers duration resolution bugfix

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeParser.cs, Specs/DateTime/English/DateTimeModelComplexCalendar.json
Fix to issue #2550.
Test cases added to DateTimeModelComplexCalendar.
=> [EN DateTimeV2] Support timezone resolution for TimeOfDay + Time patterns (#2550)

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishTimeParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchTimeParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.sln, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/french/parsers/FrenchTimeParserConfiguration.java, JavaScript/packages/recognizers-date-time/src/dateTime/french/timeConfiguration.ts, Patterns/English/English-DateTime.yaml, Patterns/French/French-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/french/time_parser_config.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/French/DateTimeModel.json
=> [FR DateTimeV2] Fixed ignored minutes in "past" and "before" time forms (#2490)

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, JavaScript/packages/recognizers-date-time/src/dateTime/english/dateTimeConfiguration.ts, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
Fix to issue #2563 in .NET and JavaScript.
=> [.NET|JavaScript | EN DateTimeV2] Added support to expressions indicating the present moment (#2563)

JavaScript/packages/recognizers-date-time/src/dateTime/baseDate.ts, JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/english/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/french/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/dateConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/spanish/mergedConfiguration.ts, JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/Spanish/DateTimeModel.json
=> [JavaScript | * DateTimeV2] Added missing filter methods (#2509)

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
Fix to issue #2582.
Test cases added to German DateTimeModel.
=> [DE DateTimeV2] Added support for early/late modifiers as suffixes in DatePeriod expressions (#2582)

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
Fix to issue #2606.
Test case added to German DateTimeModel.
=> [DE DateTimeV2] Fixed ignoring the date in a weekday-date construction (#2606)

.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, Patterns/Italian/Italian-DateTime.yaml, Specs/DateTime/French/DateTimeModel.json, Specs/DateTime/Italian/DateTimeModel.json
Fix to issue #2604 in Italian (the pattern was already working as expected in French).
Test case added to French and Italian DateTimeModel.
=> [FR, IT DateTimeV2] Fixed dates with slashes resolved incorrectly following a weekday (#2604)

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, Patterns/French/French-DateTime.yaml, Specs/DateTime/French/DateTimeModel.json
Fix to issue #2602.
Test cases added to French DateTimeModel
=> [FR DateTimeV2] Fixed "à midi" not recognized as a time (#2602)

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimePeriodExtractorConfiguration.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DatePeriodParser.json, Specs/DateTime/German/DateTimeModel.json
Fix to issue #2636.
Test cases added to German DateTimeModel.
=> [DE DateTimeV2] Fixed time + weekday range behaviour is inconsistent with English (#2636)

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Japanese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Korean/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/BaseCJKDatePeriodExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/ICJKDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/JapaneseDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Korean/Extractors/KoreanDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Korean/Parsers/KoreanDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDatePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/ICJKDatePeriodParserConfiguration.cs, Patterns/Chinese/Chinese-DateTime.yaml, Patterns/Japanese/Japanese-DateTime.yaml, Patterns/Korean/Korean-DateTime.yaml, Specs/DateTime/Korean/DatePeriodExtractor.json, Specs/DateTime/Korean/DatePeriodParser.json
Extractor: 180 pass, 0 fail.
Parser: 42 pass, 122 only extraction, 0 fail.
No spec inputs have been modified.
Ported method MatchComplexCases from BaseDatePeriodExtractor to BaseCJKDatePeriodExtractor.
=> [.NET] Korean DatePeriod support

.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimeFunctions.cs, Specs/DateTime/Chinese/DateTimeModel.json
Fix to issue #2647.
Test cases added to Chinese DateTimeModel.
=> [ZH DateTimeV2] Fixed time entities after noon returning inconsistent extra resolution as if ambiguous (#2647)

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
Fix to issue #2658.
Test case added to German DateTimeModel.
=> [DE DateTimeV2] Fixed mentions like "immer sonnabends" not recognized as Set (#2658)

Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/extractors.py, Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/parsers.py
Not sure why these were allowed in in previous PRs.
=> Python lint build fixes

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
=> Support German next/last modifier variations

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs, Specs/Timex/Resolver.json
Also adding dotnet UT showing correct behaviour for comparison with other platforms.
=> Proposal json spec for timex resolution tests for cross-plat

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/German/German-DateTime.yaml, Specs/DateTime/German/DateTimeModel.json
Fix to issue #2720.
Test cases added to German DateTimeModel.
=>  [DE DateTimeV2] Fixed morgens um 7 Uhr (#2720)

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, Patterns/Portuguese/Portuguese-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Specs/DateTime/Portuguese/DateTimeModel.json, Specs/DateTime/Spanish/DateTimeModel.json
Fix to issue #2749.
Test cases added to Spanish and Portuguese DateTimeModels.
=> [ES DatetimeV2] Fixed numeric month not recognized (#2749)

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersWithUnitDefinitions.cs, Patterns/Portuguese/Portuguese-NumbersWithUnit.yaml, Patterns/Spanish/Spanish-NumbersWithUnit.yaml, Specs/NumberWithUnit/Portuguese/CurrencyModel.json, Specs/NumberWithUnit/Spanish/CurrencyModel.json
Fix to issue #2753.
Test cases added to ES DateTimeModel.
=>  [ES Currency] Fixed currency with 'con' for decimals not completely recognized (#2753)

JavaScript/packages/recognizers-text-suite/README.md
Correction of documentation errors in javascript package
=> Correction instantiation code in JavaScript docs

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelExperimentalMode.json
Adding few more relevant keywords to each unit regex to increase the coverage for recurrence
=> [EN DateTimeV2] Increasing coverage for recurrence mentions

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Patterns/German/German-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/German/DateTimeModel.json
Fix to issue #2663 in DE and EN.
Test cases added to DateTimeModels.
=>  [EN|DE DateTimeV2] Fixed inconsistent behaviour recognizing complex entities including “frühmorgens” (#2663)

.NET/Microsoft.Recognizers.Definitions.Common/French/NumbersDefinitions.cs, Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/FrenchNumeric.java, JavaScript/packages/recognizers-number/src/resources/frenchNumeric.ts, Patterns/French/French-Numbers.yaml, Python/libraries/recognizers-number/recognizers_number/resources/french_numeric.py, Specs/Number/French/NumberModel.json
=> [FR DateTimeV2] Fix omission in French numbers for 0

.NET/Microsoft.Recognizers.Definitions.Common/BaseDateTime.cs, .NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/MatchingUtil.cs, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateExtractor.java, Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/MatchingUtil.java, JavaScript/packages/recognizers-date-time/src/dateTime/baseDate.ts, JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts, Patterns/Base-DateTime.yaml, Patterns/English/English-DateTime.yaml, Patterns/French/French-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_date.py, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/utilities.py, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/French/DateTimeModel.json
Fix to issue #2695 in EN and FR.
=> [EN DateTimeV2] Fixed proper handling of transcribed dates (#2695)

.NET/Microsoft.Recognizers.Definitions.Common/BaseNumbers.cs, .NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/English/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/EnglishNumberWithUnitExtractorConfiguration.cs, Patterns/English/English-Numbers.yaml, Patterns/English/English-NumbersWithUnit.yaml, Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/extractors.py, Specs/Number/English/NumberModel.json, Specs/NumberWithUnit/English/CurrencyModel.json, Specs/NumberWithUnit/English/DimensionModel.json, Specs/NumberWithUnit/English/TemperatureModel.json
Fix to issue #2692 in EN. 
Test cases added to NumberModel, CurrencyModel, DimensionModel, TemperatureModel.
=>  [* Number|Unit] Fixed tokenization of elements in the middle of digit/character sequence is not correct (#2692)

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
=> [* DateTimeV2] Fixed common date format YYYYMMDD not properly supported (#2705)

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, Patterns/English/English-Numbers.yaml, Specs/Number/English/NumberModel.json
Fix to issue #2704 in EN. 
Test cases added to NumberModel.
=> [* Number] Added support for unconventional scientific notation (#2704)

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, Patterns/French/French-DateTime.yaml, Specs/DateTime/French/DateTimeModel.json
Fix to issue #2491.
Test cases added to French DateTimeModel.
=> [FR DateTimeV2] Fixed failing to recognize certain ambiguous spelled-out hours as times (#2491)

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs, Specs/DateTime/English/DateTimeModel.json
=> [EN DateTimeV2] Fixed "every week starting next week" returns empty/null timex (#2724)

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Japanese.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Extractors/TemperatureExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Parsers/TemperatureParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/INumberWithUnitParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs, Patterns/Japanese/Japanese-NumbersWithUnit.yaml, Specs/NumberWithUnit/Japanese/TemperatureModel.json
=> [.NET] Japanese Temperature support

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, Patterns/French/French-DateTime.yaml, Specs/DateTime/French/DateTimeModel.json
=> [FR Datetime] Fixed a daterange starting with the = sign (like "= An") gives stack overflow (#2807)

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/French/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/German/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Italian/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Portuguese/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Text.Number/Constants.cs, .NET/Microsoft.Recognizers.Text.Number/Dutch/Parsers/DutchNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/French/Parsers/FrenchNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/German/Parsers/GermanNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Italian/Parsers/ItalianNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs, .NET/Microsoft.Recognizers.Text.Number/Portuguese/Parsers/PortugueseNumberParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.Number/Spanish/Parsers/SpanishNumberParserConfiguration.cs, Patterns/Dutch/Dutch-Numbers.yaml, Patterns/English/English-Numbers.yaml, Patterns/French/French-Numbers.yaml, Patterns/German/German-Numbers.yaml, Patterns/Italian/Italian-Numbers.yaml, Patterns/Portuguese/Portuguese-Numbers.yaml, Patterns/Spanish/Spanish-Numbers.yaml, Specs/Number/Dutch/NumberModel.json, Specs/Number/English/NumberModel.json, Specs/Number/French/NumberModel.json, Specs/Number/German/NumberModel.json, Specs/Number/Italian/NumberModel.json, Specs/Number/Portuguese/NumberModel.json, Specs/Number/Spanish/NumberModel.json
Fix to issue #2786 in EN|ES|IT.
Test cases added to NumberModels.
=> [NL|EN|FR|DE|IT|PT|ES Number] Fixed large number expressed as a fraction not recognized correctly (#2786)

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimeExtractorConfiguration.cs, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/DateTime/Portuguese/DateTimeModel.json
=> [PT DateTimeV2] Fixed failing to recognize times in the n horas format (#2669)

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs, Patterns/English/English-Numbers.yaml, Specs/Number/English/NumberModel.json
Fix to issue #2716 in .NET.
Test cases added to NumberModel.
=>  [EN Number] Fixed Issue with fracLikeNumberParse in .NET (#2716)

Patterns/Base-Numbers.yaml
Added missing definition of PlaceHolderMixed in Base-Numbers.yaml
=> [* Number] Added missing change from PR  #2778

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Korean/Parsers/TemperatureParserConfiguration.cs, Patterns/Korean/Korean-Numbers.yaml, Patterns/Korean/Korean-NumbersWithUnit.yaml, Specs/NumberWithUnit/Korean/TemperatureModel.json
=> [KO NumberWithUnit] Korean Temperature refinements

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
=>  [EN DateTimeRange] Fixed "Rating where year is greater than 2015" doesn't recognize a ">2015" DateTimeRange (#2840)

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/WeightExtractorConfiguration.cs, Patterns/Portuguese/Portuguese-NumbersWithUnit.yaml, Specs/NumberWithUnit/Portuguese/DimensionModel.json, Specs/NumberWithUnit/Portuguese/TemperatureModel.json
Fix to issue #2884.
Test cases added to DimensionModel.
=>  [PT Units] Fix a few missing patterns are not supported (#2884)

.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, Patterns/Italian/Italian-DateTime.yaml, Specs/DateTime/Italian/DateTimeModel.json
=> [IT DateTimeV2] Fix mentions in the form "day-of-week, date" not recognized (#2900)

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/SpanishNumberWithUnitExtractorConfiguration.cs, Patterns/Spanish/Spanish-NumbersWithUnit.yaml, Specs/NumberWithUnit/Spanish/CurrencyModel.json
Fix to issue #2889.
Test cases added to CurrencyModel.
=> [ES Currency] Fix $$ USD Million not recognized as well as $$ MXN$ not recognized (#2889)

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs, Specs/NumberWithUnit/Japanese/CurrencyModel.json
Moved timex logic to TimexUtility as for comment in PR #2961.
Added test cases from issue #2921 in Japanese CurrencyModel.
=> [.NET] Refinements from addressing issues #2936, #2921

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs, Patterns/Chinese/Chinese-DateTime.yaml, Specs/DateTime/Chinese/DateTimeModel.json
Fix to issue #2937.
Test cases added to Chinese DateTimeModel.
=> [ZH DateTimeV2] Added support for DateTimePeriod patterns like "还剩5 分钟" (#2937)

.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/CurrencyExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/CurrencyParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/BaseCurrencyParser.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/INumberWithUnitParserConfiguration.cs, Specs/NumberWithUnit/English/CurrencyModel.json
Fix to issue #2942.
Test cases added to EN CurrencyModel.
=> [EN Currency] Fix MUSD not recognized (#2942)

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, Patterns/English/English-DateTime.yaml, Specs/DateTime/English/DateTimeModel.json
=> [EN DateTimeV2] Fixed some durations are returned without a resolution in English (#2691)

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs, Patterns/Dutch/Dutch-DateTime.yaml, Patterns/English/English-DateTime.yaml, Patterns/French/French-DateTime.yaml, Patterns/Hindi/Hindi-DateTime.yaml, Patterns/Italian/Italian-DateTime.yaml, Patterns/Portuguese/Portuguese-DateTime.yaml, Patterns/Spanish/Spanish-DateTime.yaml, Patterns/Turkish/Turkish-DateTime.yaml, Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_merged.py, Specs/DateTime/Dutch/DateTimeModel.json, Specs/DateTime/English/DateTimeModel.json, Specs/DateTime/English/DateTimeModelComplexCalendar.json, Specs/DateTime/Spanish/DateTimeModel.json
=> [EN DateTime V2] Fixed handling cases like "-2020-07-01-" or "-20200701-" (#2949)

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs, Patterns/Portuguese/Portuguese-DateTime.yaml, Specs/DateTime/Portuguese/DateTimeModel.json
=> [PT DateTimeV2] Fixed failing to recognize times in the 'das n' format (#2668)

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs, Specs/DateTime/French/DateTimeModel.json
=> [FR DateTimeV2] Stack overflow fix in .NET

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs, Patterns/French/French-DateTime.yaml, Specs/DateTime/French/DateTimeModel.json
- improving the coverage of the terms dernier (last) on French sentences such as "au cours des dix derniers mois" 
which means "in the last ten months"
=> [FR DateTimeV2] Improving coverage of terms for last in French

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersDefinitions.cs, Patterns/Chinese/Chinese-Numbers.yaml, Specs/Number/Chinese/NumberModel.json
=> [ZH Number] Add AmbiguityFiltersDict for cases like "伍"

NuGet.Config, appveyor.yml
Adding a NuGet.Config template file that is used in OneBranch pipeline.
=> [Infra] - Safe addition of NuGet.Config

JavaScript/packages/recognizers-number-with-unit/package.json
Bump dependency and package version for recognizers number with unit
Ran npm install, npm run build and npm run test on parent Javascript directory
Successful build
Successful test
=> Bump dependencies and package version for recognizers number with unit

JavaScript/package.json, JavaScript/packages/recognizers-text-suite/README.md, JavaScript/packages/recognizers-text-suite/package.json
Bumping up package version for recognizers suite and recognizers
Ran npm install, npm run build and npm run test in the main javascript folder
build successful:
test successful:
=> Bump version for recognizers suite and recognizers

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.csproj, Patterns/Spanish/Spanish-DateTime.yaml, Patterns/Spanish/Spanish-NumbersWithUnit.yaml, Specs/DateTime/Spanish/DatePeriodExtractor.json, Specs/DateTime/Spanish/DatePeriodParser.json, Specs/DateTime/Spanish/DateTimeModel.json, Specs/NumberWithUnit/Spanish/AgeModel.json
Merge latest master into Package
=> Merge latest master into Package

NuGet.Config
Update NuGet.Config with master
=> Update NuGet.Config with master

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersWithUnitDefinitions.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/DimensionExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/DimensionParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.xml, .NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs, Patterns/English/English-NumbersWithUnit.yaml, Specs/NumberWithUnit/English/DimensionModel.json
Support mixed length unit foot and inch, like 5 ft 3 inch, 5 feet 3 inches.
=> Support mixed length unit foot and inch

.NET/Microsoft.Recognizers.Definitions.Common/BaseEmail.cs, .NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDateExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDatePeriodExtractorConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDatePeriodParserConfiguration.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDateParser.cs, .NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDatePeriodParser.cs, Patterns/Base-Email.yaml, Patterns/Chinese/Chinese-DateTime.yaml, Specs/DateTime/Chinese/DateExtractor.json, Specs/DateTime/Chinese/DateParser.json, Specs/DateTime/Chinese/DatePeriodExtractor.json, Specs/DateTime/Chinese/DatePeriodParser.json, Specs/DateTime/Chinese/DateTimeModel.json, Specs/Sequence/English/EmailModel.json
cherry-picking two recent commits from master.
=> New nuget update to release fixes for Chinese
