Microsoft.Recognizers.Text.DateTime.Tests/English/TestDatePeriodParser.cs
Microsoft.Recognizers.Text.DateTime.Tests/Spanish/TestDatePeriodParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs

As discussed with Borje, we should inform the user for the change before we actually make the change. Before that we should set the bool "InclusiveEndPeriod" in BaseDatePeriodParser to false.

Change the end of date period to inclusive

---

Microsoft.Recognizers.Text.DateTime.Tests/English/TestHolidayParser.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/BaseDateTimeExtractor.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DatePeriodExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateTimeExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateTimePeriodExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DurationExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/MergedDateTimeExtractor.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/SetExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/TimeExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/TimePeriodExtractorChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateTimeParserConfiguration.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateParser.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateTimeParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateTimePeriodParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DurationParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/HolidayParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/MergedParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/SetParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/TimeParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/TimePeriodParserChs.cs
Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimeExtractorConfiguration.cs
Microsoft.Recognizers.Text.DateTime/English/Parsers/TimeParser.cs
Microsoft.Recognizers.Text.DateTime/English/Utilities/EnlighDatetimeUtilityConfiguration.cs
Microsoft.Recognizers.Text.DateTime/Spanish/Utilities/SpanishDatetimeUtilityConfiguration.cs
Microsoft.Recognizers.Text.Number/NumberRecognizer.cs
Microsoft.Recognizers.Text.NumberWithUnit.Tests/TestNumberWithUnitPortuguese.cs
Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/CurrencyExtractorConfiguration.cs
Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/CurrencyExtractorConfiguration.cs

- Currency extractor almost fully translated;
- Unit tests for currency in Portuguese passing, but utterances not fully in PT, only numbers and units;
- Small currency fixes in Spanish;
- Cleanup in Chinese.
Next PR will finish currencies.

More currency extractor changes for Portuguese + small fixes and cleanup in Spanish and Chinese recognizers

---

Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimeExtractor.cs

Replace 3 missing regex definitions for BaseTimeExtractor.
They were already being generated from YAML.

Extract BaseTimeExtractor regex definitions

---

Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParserConfiguration.cs

Replace missing dictionary definitions for BaseDateParserConfiguration.
They were already being generated from YAML.

Extract BaseDateParserConfiguration dictionary definition

---

Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs
Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedParser.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateParser.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateTimeParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DateTimePeriodParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/HolidayParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/TimeParserChs.cs
Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/TimePeriodParserChs.cs
Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimePeriodExtractorConfiguration.cs
Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishHolidayParserConfiguration.cs
Microsoft.Recognizers.Text.DateTime/English/Parsers/TimeParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseHolidayParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseHolidayParserConfiguration.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimeParser.cs
Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs
Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateExtractorConfiguration.cs
Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs
Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/DateTimePeriodParser.cs
Microsoft.Recognizers.Text.DateTime/Utilities/DateObjectExtension.cs
Patterns/English/English-DateTime.yaml

1. change the new DateObject to DateObject.SetValue extension method which will check if the date object is valid or not to avoid argument exceptions.
2. fix the bug in "to" as a connector to restrict the exact match
3. restrict the month regex and day regex to end with '\b'

Fix bugs reported by mercury#4

---

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateTimeExtractorChs.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateTimePeriodExtractorChs.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs

An issue arise when running the tests through MsTest.exe
Sorting two extraction results with the same Start index (and different length) returns different orders using MsTest.exe and Visual Studio Test Runner.
The first extraction may be placed second, making the extraction behave differently between test runners.
Cause:  C# List.Sort uses quicksort internally which is  unstable (see remarks on https://msdn.microsoft.com/en-us/library/w56d4y5z(v=vs.110).aspx)
"This implementation performs an unstable sort; that is, if two elements are equal, their order might not be preserved. In contrast, a stable sort preserves the order of elements that are equal."
Fix: use LINQ OrderBy which is stable - https://msdn.microsoft.com/en-us/library/bb534966.aspx
"This method performs a stable sort; that …

Change from using List.Sort unstable sort to stable LINQ OrderBy

---

JavaScript/src/dateTime/english/dateTimeConfiguration.ts
JavaScript/test/mergedExtractor-english.test.js

Issue: In case-sensitive filesystems these imports were failing
Solution: use same casing as filenames

TypeScript - Proper filename casing when importing modules

---

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime.Tests/English/TestEnglishModel.cs
.NET/Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime.Tests/English/TestMergedParser.cs
.NET/Microsoft.Recognizers.Text.DateTime.Tests/Spanish/TestMergedExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/MergedParserChs.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/IMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishMergedParserConfiguration.cs
Patterns/English/English-DateTime.yaml
Patterns/Spanish/Spanish-DateTime.yaml

Bug: **"_Since August_"** resolves to the first day of September as a start date
Solution: The prefix **since** needs to be handled apart from **after** to be resolved in the right way.
- **"_After August_"** resolves to the first day of September as a start date
- **"_Since August_"** resolves to the first day of August as a start date
related to https://stackoverflow.com/questions/46208542/luis-pre-built-entity-datetimev2-does-not-resolve-properly

Fix "since" prefix bug

---

JavaScript/test/datadriven-tests.js
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/MergedParser.json
Specs/NumberWithUnit/English/DimensionModel.json

Some tests are failing in Microsoft.Recognizers.Text.with.Spec.Tests.sln due to outdated spec files.
Specs files can be updated running the instrumented tests in Microsoft.Recognizers.Text.sln.
This commit include those updates that fix the failing tests.

Fix specs test runners with missing spec file updates

---

JavaScript/build.cmd
JavaScript/test/runner-datetime.js

**Issue:** JavaScript DateTime tests fails on node js v7 or prior because `Date.parse` behavior differs from the implemented on node js v8. [Related node issue (Date parse behavior change in node-v8)](https://github.com/nodejs/node/issues/13210)
**Fix:** Use a custom `ISODateString-to-dateObject` converter to get the same behavior in all node versions.
Additionally, the JavaScript build script has been modified to force build submodules.

Fix JavaScript parse reference date

---

.NET/buildtools/updateAssemblyInfo.ps1

Fix to code signing build now that the .NET solution references a sub-project two directories deep.

Fix to code signing build

---

.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestHelpers.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseHolidayParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseSetParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/DateTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/AgoLaterUtil.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs
.NET/Microsoft.Recognizers.Text/ModelContainer.cs

Moving out var declarations inline to make sure builds are now properly configured to use VS2017.

Moving out var declarations inline to make sure build uses VS2017

---

.NET/Build.CI.cmd
appveyor.yml

- New Build.CI.cmd intented to be run on AppVeyor
- Update appveyor.yml to include .NET build & tests

CI - AppVeyor updates for building .NET

---

Specs/Number/French/NumberModel.json
Specs/NumberWithUnit/French/CurrencyModel.json

- Fixing broken currency case;
- Workaround for failing test in numbers (IPs shouldn't be recognized as numbers, or all 4 segments should be recog separately); temporarily reverting to same behaviour as other languages.

Fixing 2 broken unit tests in French

---

.NET/Build.CI.cmd
.NET/Build.cmd

- CI Fix to report failure when a .NET test fails
- Run .NET tests in parallel

CI - .NET Test Fails should invalidate build

---

JavaScript/packages/recognizers-date-time/src/dateTime/baseTimePeriod.ts
JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts

Related to https://github.com/Microsoft/Recognizers-Text/issues/172
Only happens on machines where timezone has daylight savings
Fix works out by taking in consideration the timezone offset when calculating durations between dates,  thus avoiding the +1 or -1 hours of daylight savings.

Fix to duration calculation when daylight saving occurs

---

JavaScript/lerna.json
JavaScript/packages/recognizers-date-time/package.json
JavaScript/packages/recognizers-number-with-unit/package.json
JavaScript/packages/recognizers-number/package.json
JavaScript/packages/recognizers-options/package.json
JavaScript/packages/recognizers-text-suite/package.json
JavaScript/packages/recognizers-text/package.json

To match latest internal prerelease publish

JavaScript -Version bump to RC 29 (1.0.0-rc.29.0)

---

JavaScript/packages/recognizers-options/src/options/english/boolean.ts
Specs/Options/English/BooleanModel.json

The 'global' property from token regular expression was removed since this RegExp is used several times in different contexts, so it causes getting unexpected results

Remove global property from recognizer options token regular expression

---

JavaScript/packages/recognizers-choice/src/choice/choiceRecognizer.ts

Fixed ChoiceRecognizer class name. Exported class is renamed as ChoiceRecognizer, so it doesn't affect  [external invokes](https://github.com/Microsoft/Recognizers-Text/blob/d7f4d27a3d32dc766ff0d3f7b71305824c361eb8/JavaScript/packages/recognizers-choice/src/recognizers-text-choice.ts#L1).

Fix choiceRecognizer class name

---

.NET/Microsoft.Recognizers.Text.DateTime/Utilities/MatchingUtil.cs
JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts
Specs/DateTime/English/DateTimeExtractor.json
Specs/DateTime/English/DateTimeParser.json
Specs/DateTime/French/DateExtractor.json

GitHub issue #401
Fix incorrect date/time phrase extraction, large chunks of sentence mistakenly extracted as time phrase.

Fix incorrect datetime extraction.

---

.NET/Microsoft.Recognizers.Text.Choice/Extractors/ChoiceExtractor.cs
.NET/Microsoft.Recognizers.Text.Choice/Microsoft.Recognizers.Text.Choice.csproj

We implemented the only piece of logic we used from the NeoSmart.Unicode package within the class.
- bool IsEmoji(string letter)
- IEnumerable<string> Letters(string text)

Remove NeoSmart.Unicode (no strong named) dependency form Choice*

---

.NET/Microsoft.Recognizers.Definitions/BaseIp.cs
JavaScript/packages/recognizers-sequence/src/resources/baseIp.ts
Patterns/Base-Ip.yaml
Specs/Sequence/English/IpAddressModel.json

fix ipv6 bug for ellipsis
example: sync:

Fix ipv6 bug for single ‘:’

---

.NET/Microsoft.Recognizers.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.DataTypes.DateTime/TimexResolver.cs
JavaScript/packages/datatypes-date-time/src/timexResolver.js
JavaScript/packages/datatypes-date-time/test/timexResolver.spec.js

This fixes a bug reported as follows: From what I use from LUIS I get the timex equal to “2018-03-18TNI” Native LUIS resolves it as: 
"entity": "tonight",
"type": "builtin.datetimeV2.datetimerange",
"startIndex": 13,
"endIndex": 19,
"resolution": {
"values": [
{
"timex": "2018-03-18TNI",
"type": "datetimerange",
"start": "2018-03-18 20:00:00",
"end": "2018-03-18 23:59:59"
}
]
}
But when I use var r = TimexResolver.Resolve(new[] {“2018-03-18TNI” }, DateTime.Now);
Except that the resolver resolves the end date to 2018-03-18 24:00:00 which is consistent with the other date time ranges.

Fix classic style resolution for tonight (NI)

---

.NET/Microsoft.Recognizers.Definitions/Chinese/NumbersDefinitions.cs
JavaScript/packages/recognizers-number/src/resources/chineseNumeric.ts
Patterns/Chinese/Chinese-Numbers.yaml
Python/libraries/recognizers-number/recognizers_number/resources/chinese_numeric.py
Specs/Number/Chinese/PercentModel.json

This PR address issue #534 #538, tests marked as not supported Javascript for current issue with lookbehind regex in JS.

Fix percentage wrongly extracted in mixed text for Chinese

---

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs
JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts
Patterns/Chinese/Chinese-DateTime.yaml
Specs/DateTime/Chinese/DatePeriodExtractor.json
Specs/DateTime/Chinese/DatePeriodParser.json

GitHub issue #532, this PR also address an issue that year improperly extracted from number sequences. Parse test marked as not supported Javascript because of known issue #541.
- fix number beyond valid range wrongly recognized as years (#532)
- fix year improperly extracted from number sequences

Fix bugs in Chinese year regexes

---

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/DatePeriodParserChs.cs
JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts
Patterns/Chinese/Chinese-DateTime.yaml
Specs/DateTime/Chinese/DatePeriodExtractor.json
Specs/DateTime/Chinese/DatePeriodParser.json
Specs/DateTime/Chinese/DateTimeModel.json

#476 
Note that only "0x 年“ should be recognized.
"1x年", "2x年" is ambigious, not handled in this PR

Recognize "07年" in Chinese DateTime

---

JavaScript/package-lock.json
JavaScript/package.json
JavaScript/packages/datatypes-date-time/package-lock.json
JavaScript/packages/recognizers-number/package-lock.json
JavaScript/packages/recognizers-number/package.json
JavaScript/packages/recognizers-number/src/culture.ts
JavaScript/packages/recognizers-number/src/number/chinese/parsers.ts
JavaScript/packages/recognizers-number/src/number/parsers.ts

- remove "ERRORS" config in bigNumber.js
- change the import method of bigNumber
- move bigNumber and xregexp to global package.json
- minor: toDigits -> precision
ref:
- Import issue https://github.com/MikeMcl/bignumber.js/issues/166
- ERRORS config https://github.com/MikeMcl/bignumber.js/issues/148
- toDigits -> precision https://github.com/MikeMcl/bignumber.js/issues/139

Bump up version of bigNumber.js and xregexp to their latest release

---

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimeZoneExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/IMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimeZoneExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimeZoneExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimeZoneExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimeZoneExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/MatchingUtil.cs
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModelComplexCalendar.json

Support superfluous word filter in English under the preview mode.
For cases like "OK, let’s find some time to discuss it next week, preferably on Tuesday" in which "preferably" is a superfluous word.

Support superfluous word filter in English

---

.NET/Microsoft.Recognizers.Definitions/Japanese/ChoiceDefinitions.cs
.NET/Microsoft.Recognizers.Definitions/Japanese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs
JavaScript/packages/recognizers-choice/src/resources/japaneseChoice.ts
Patterns/Japanese/Japanese-Choice.yaml
Patterns/Japanese/Japanese-Numbers.yaml
Specs/Choice/Japanese/BooleanModel.json
Specs/Number/Japanese/PercentModel.json

{
"Input": "今シーズンの打率は3割8分7厘でした",
"NotSupported": "javascript, python",
"Results": [
{
"Text": "3割8分7厘",
"TypeName": "percentage",
"Resolution": {
"value": "38.7%"
}
}
]
}

Add missing case for xxx割xxx分xxx厘 (#634)

---

Java/build-resources.cmd
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/NumberWithUnitRecognizer.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/extractors/NumberWithUnitExtractor.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/resources/ChineseNumericWithUnit.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/AgeExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/AreaExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/CurrencyExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/DimensionExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/LengthExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/SpanishNumberWithUnitExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/SpeedExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/TemperatureExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/VolumeExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/extractors/WeightExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/AgeParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/AreaParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/CurrencyParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/DimensionParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/LengthParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/SpanishNumberWithUnitParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/SpeedParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/TemperatureParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/VolumeParserConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/spanish/parsers/WeightParserConfiguration.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/ChineseNumeric.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/EnglishNumeric.java
Specs/NumberWithUnit/Spanish/AgeModel.json
Specs/NumberWithUnit/Spanish/DimensionModel.json

The PR contains the following (Spanish) models:
- Ages
- Currencies
- Dimensions
- Temperatures
Two tests had to be disabled due to the same issue identified on the NumberRecognizer:
- English/AgeModel/"Tiene unos 40 - 50 años"
- English/DimensionModel/"En 1995 Cannon introdujo la primera lente SLR comercialmente disponible con estabilización de imagen interna, 75 - 300 mm f / 4 - 5. 6 es usm."

[Java] NumberWithUnit - Spanish

---

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs

This PR improve the performance of the C# DateTime model by about 14.89%.
The experiment is conducted on a dataset consist of 2065 sentences based on the version 0ffbe4a.

Improve c# DateTimePeriodExtractor's performance

---

.NET/Microsoft.Recognizers.Definitions/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

This PR addresses GitHub issue #713 #716 and also improves the performance of the C# DateTime model by about **13.16%**.
The experiment is conducted on a dataset consist of 2065 sentences based on the version f1eb553

Minor fixes for English Datetime and performance improvement

---

Specs/Choice/Dutch/BooleanModel.json
Specs/Number/Dutch/NumberModel.json
Specs/Number/Dutch/NumberModelPercentMode.json
Specs/Number/Dutch/NumberRangeModel.json
Specs/Number/Dutch/OrdinalModel.json
Specs/Number/Dutch/PercentModel.json
Specs/Number/Dutch/PercentModelPercentMode.json
Specs/NumberWithUnit/Dutch/AgeModel.json
Specs/NumberWithUnit/Dutch/DimensionModel.json
Specs/NumberWithUnit/Dutch/TemperatureModel.json

Changed ```NotSupported``` to ```NotSupportedByDesign``` for javascript, python and java. 
I kept the dotNet on NotSupported for now, should I also change them to NotSupportedByDesign since there is no implementation yet? Or keep them on NotSupported since implementation is planned.

Normalize existing testcases for Dutch language

---

JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/japanese/age.ts
JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/numberWithUnitRecognizer.ts
JavaScript/packages/recognizers-number-with-unit/src/recognizers-text-number-with-unit.ts
Specs/NumberWithUnit/Japanese/AgeModel.json

- Add Age recognizer for Japanese
- Range is not yet supported. (e.g. 70-90日齢)

[JavaScript] Japanese Age model

---

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeAltParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/DateTimeModelExtendedTypes.json

For cases like "next Monday or Tuesday after 1pm GMT" which throws an exception previously, and cases like "I am looking at 18 and 19 June" in which "18" is wrongly recognized as a time point previously.

Fix bugs in date-time alternative

---

JavaScript/packages/recognizers-number/package-lock.json
JavaScript/packages/recognizers-number/package.json

Add missing `bignumber.js` dependency in `JavaScript/packages/recognizers-number/package.json`.
This dependency was updated and incorrectly _moved_ to root's package.json.
It is correct to update in root since it is used by lerna, however since removed from `recognizers-number/package.json` is is no longer installed alongside which causes issues in dependant packages like [`botbuilder-dialogs`](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/package.json#L25-L28)

Add bignumber.js missing dependency

---

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateTimeParserConfiguration.cs
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/date_parser_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py
Specs/DateTime/Chinese/DateExtractor.json
Specs/DateTime/Chinese/DateParser.json
Specs/DateTime/Chinese/DateTimeModel.json

- Github Issue #860  
- Add cases "後天", "大後天", "週三" for CN datetimeV2.

Fix wrong parse result for 後天你有空吗？

---

JavaScript/packages/recognizers-date-time/src/dateTime/chinese/datePeriodConfiguration.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/dateperiod_parser.py
Specs/DateTime/Chinese/DatePeriodParser.json
Specs/DateTime/Chinese/DateTimeModel.json

Fix wrong parse result for '从二零一六年至二零一八年' in Python and JavaScript

---

.NET/Microsoft.Recognizers.Definitions/Chinese/DateTimeDefinitions.cs
.NET/Samples/SimpleConsole/Program.cs
.gitignore
JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts
Patterns/Chinese/Chinese-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py

Revised direction 
1. 后=>后|後
2. 之后=>之后|之後
3. 以后=>以后|以後

 [CN DateTime] Extend the recognition for traditional Chinese

---

.NET/Microsoft.Recognizers.Definitions/Dutch/NumberDefinitions.cs
Patterns/Dutch/Dutch-Numbers.yaml
Specs/Number/Dutch/NumberModel.json

- Fix ‘honderduizend’ and ‘honderd duizend’
- Enable testcases for .NET and add missing testcases

[NL NumberModel] Fix ‘honderduizend’ and ‘honderd duizend’

---

Java/tests/src/test/java/com/microsoft/recognizers/text/tests/AbstractTest.java

- We found the failed count in the summary table for Java unit tests might not be counting failed tests properly. However, it does mark the build as failed and it is showing the error details.

[Java] Fix failed unit tests count in summary table

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/TimeTypeConstants.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishCommonDateTimeParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDurationParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDurationParser.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/BaseDateParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/ICommonDateTimeParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDurationParserConfiguration.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/helpers/TimeZoneResolutionResultMixIn.java
Specs/DateTime/English/DurationParser.json

- setup main datetime parsers structure: test runner and folder structure
- In EnglishCommonDateTimeParserConfiguration.java included only those available extractors/parser. Will update incrementally as needed when port new parsers.
- Skipped one test added to C# after porting this class. We'll re-enable in another thread and PR.

[Java][Datetime] Port BaseDurationParser from C# to Java

---

Java/linting-rules.xml

Linting rules update:
* Parameter and catch parameter name must match the regex `^[a-z][a-zA-Z0-9]*$`, which allow variables name with the format `variableName`, `varName01`, `vName01`, `vNAME` and `v01`.
* Local variable name must match the regex `^([a-z][a-zA-Z0-9]*|[A-Z][A-Z0-9_]*)$`, which allow variables name with the format `variableName`, `varName01`, `vName01`, `vNAME`, **`VAR_NAME`** and `v01`.
* Variable declaration distance change from 5 to 10.
* The operators `&&`, `||` and `?` must be at the end of the line when the line is split into multiple lines.
* Add a new rule for "No white spaces after typecast".

[Java][Recognizers-Text] Linting rules update

---

Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/extractors/BaseMergedUnitExtractor.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/models/AbstractNumberWithUnitModel.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/parsers/BaseCurrencyParser.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/parsers/NumberWithUnitParser.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/extractors/BaseNumberExtractor.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/extractors/BaseNumberRangeExtractor.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/extractors/BasePercentageExtractor.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/parsers/BaseCJKNumberParser.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/parsers/BaseNumberParser.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/parsers/BaseNumberRangeParser.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/parsers/BasePercentageParser.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/parsers/NumberFormatUtility.java
Java/linting-rules.xml

Apply new linting rules to:
* Recognizers-text-number
* Recognizers-text-number-with-units

[Java][Recognizers-text] Apply new linting rules to number & number-with-units

---

Java/tests/src/test/java/com/microsoft/recognizers/text/tests/TestCase.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java

- Enable Set parer tests (were disable due to failing tests)
- Fixed Set parser tests supporting timezone parsing from test cases

[Java][Datetime] Fix BaseSetParser unit tests

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateTimeExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishDateTimeParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimeExtractor.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/config/IDateTimeExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDateTimeParser.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/config/IDateTimeParserConfiguration.java
Specs/DateTime/English/DateTimeParser.json

- Enable 8 tests skipped in previous versions.
- Fix an issue related to `DateTime` parse method.

[Java][DateTime] Enable and Fix DateTime parser unit tests

---

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/DummyTimeZoneParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishMergedParserConfiguration.cs

Remove repeating TimeZoneParser in Portuguese, French, German, Spanish, and Italian. A DummyTimeZone file is added to avoid override warnings when build under .Net

Fix override warnings build under .Net in PT/ES/FR/GE/IT

---

.NET/Microsoft.Recognizers.Definitions/Chinese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Chinese/Extractors/IntegerExtractor.cs
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
JavaScript/packages/recognizers-number/src/number/chinese/extractors.ts
JavaScript/packages/recognizers-number/src/resources/chineseNumeric.ts
Patterns/Chinese/Chinese-Numbers.yaml
Python/libraries/recognizers-number/recognizers_number/number/chinese/extractors.py
Python/libraries/recognizers-number/recognizers_number/resources/chinese_numeric.py
Specs/DateTime/Chinese/DateTimeModel.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/DateTimeModelExperimentalMode.json
Specs/Number/English/NumberModel.json

#1054 
A HalfUnitRegex is added to fix datetime duration like "半小时", "半个月", and "半年", etc. The specs for "twenty-six" is added.

Fix "半小时" cannot be recognized, add specs for "twenty-six"

---

.NET/Microsoft.Recognizers.Definitions/German/NumbersDefinitions.cs
Patterns/German/German-Numbers.yaml
Specs/Number/German/NumberModel.json

Filter out certain cases of ein/1 ambiguity in German where "ein" is incorrectly parsed as a number at the end of a phrase or sentence. This will improve behaviour especially with smart home use cases.
Examples:
- "Schalte das Radio ein"
- "Ein"
- "Mir fällt nichts ein"
- "Schalte die Heizung ein"

Filter out certain German ein/1 ambiguity, correct incorrect spec

---

appveyor.yml

Fix the appveyor.yml file to start running builds/tests over the `feature/[anything]` branches. The reason is that the `.yml` file needs a regular expression instead of a wildcard ([more info here](https://www.appveyor.com/docs/branches/#white--and-blacklisting)).
Also, add the `fix/[anything]` and `hotfix/[anything]` regexes.
AppVeyor successfully run after the `.yml` file modification

Fix regex in appveyor.yml file

---

JavaScript/packages/recognizers-number/src/number/cjkParsers.ts

Depends on #1065 
- Replace `regExp.test()` with `RegExpUtility.isMatch()` in `recognizers-number` for **Chinese**. When executing the same Regex method in a single scope, the starting index in the Regex is modified and results may be affected ([more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#Description))
- Run all `JavaScript` tests at once.

Replace 'RegExp.test()' with RegExpUtility.isMatch()'

---

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/DateTimePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimePeriodExtractorConfiguration.cs

[StyleCop] Fix all StyleCop warnings in SpanishDateTimePeriodExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimePeriodExtractorConfiguration.cs

[StyleCop] Fix all StyleCop warnings in PortugueseDateTimePeriodExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateTimePeriodExtractorConfiguration.cs

[StyleCop] Fix all StyleCop warnings in ItalianDateTimePeriodExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimePeriodExtractorConfiguration.cs

[StyleCop] Fix all StyleCop warnings in GermanDateTimePeriodExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimePeriodExtractorConfiguration.cs

[StyleCop] Fix all StyleCop warnings in FrenchDateTimePeriodExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DateTimePeriodExtractorChs.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseDateTimeParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in JapaneseDateTimeParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDatePeriodParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in SpanishDatePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDatePeriodParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in PortugueseDatePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDatePeriodParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in ItalianDatePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDatePeriodParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in GermanDatePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDatePeriodParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in FrenchDatePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in EnglishDatePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishHolidayParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in SpanishHolidayParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseHolidayParserConfiguration.cs

[StyleCop] Fix all StyleCop warnings in PortugueseHolidayParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/HolidayParserChs.cs

[StyleCop] Fix all StyleCop warnings in HolidayParserChs.

---

.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/HolidayParserGer.cs

[StyleCop] Fix all StyleCop warnings in HolidayParserGer

---

.NET/Microsoft.Recognizers.Definitions/BuildResources.cmd

- Escape the file path to prevent ["No input file specified."](
https://github.com/atifaziz/t5/blob/6f93925ad1ecbd676013e1c3abc3fbfc75f9ba39/src/TextTransform/TextTransform.cs#L78) errors being thrown, when a path contains spaces
- Add check if `CommonAssemblyPath` exists

[Infra] Check if CommonAssemblyPath exists & escape path in BuildResources.cmd

---

Specs/DateTime/Dutch/DateExtractor.json
Specs/DateTime/Dutch/DateParser.json
Specs/DateTime/Dutch/DateTimeExtractor.json
Specs/DateTime/Dutch/DateTimePeriodParser.json
Specs/DateTime/Dutch/DurationParser.json
Specs/DateTime/Dutch/SetExtractor.json
Specs/DateTime/Dutch/TimeExtractor.json
Specs/DateTime/Dutch/TimeParser.json
Specs/DateTime/Dutch/TimePeriodExtractor.json

I added the `Start` + `Length` properties with a script I wrote myself, however it didn't take into account that some tests had a deviant `Input` and `Text` property. Fixed.

[NL DateTime] Fix tests which have Start set to -1

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/utilities/SpanishDatetimeUtilityConfiguration.java

* Port `SpanishDateTimeUtilityConfiguration` from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Utilities/SpanishDatetimeUtilityConfiguration.cs) to Java

[Java][DateTime] Port SpanishDateTimeUtilityConfiguration from C# to Java

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDurationExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/utilities/SpanishDatetimeUtilityConfiguration.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java

**NOTE**: This PR is related to the [PR #1117](https://github.com/Microsoft/Recognizers-Text/pull/1117) and must be merged after it.
* Port SpanishDurationExtractorConfiguration from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDurationExtractorConfiguration.cs) to Java
* Add SpanishExtractor's tests placeholder in DateTimeExtractorTest
* Enable SpanishDurationExtractor's tests

[Java][Datetime] Port SpanishDurationExtractorConfiguration from C# to Java

---

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimeParserConfiguration.cs

- reordered usings, static fields and constructor
- removed extra spaces

[StyleCop] Fix all StyleCop warnings in EnglishDateTimeParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimePeriodParserConfiguration.cs

- reordered static fields and constructor
- removed extra new line

[StyleCop] Fix all StyleCop warnings in EnglishDateTimePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimeExtractorConfiguration.cs

[StyleCop] Fix all StyleCop warnings in FrenchDateTimeExtractorConfiguration

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishTimeExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishTimeZoneExtractorConfiguration.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java

**NOTE**: This PR is based both on PRs #1077 and #1119 . We'll rebase when the respective branches are merged.
---
- Enable `TimeExtractor` tests
- Port `SpanishTimeExtractorConfiguration` from C# to Java
- port `SpanishTimeZoneExtractorConfiguration` from C# to Java

[Java][DateTime] Port SpanishTime/SpanishTimeZoneExtractorConfiguration from C# to Java

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDateExtractorConfiguration.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java

* Enable SpanishDateExtractor's tests
* Port SpanishDateExtractorConfiguration from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateExtractorConfiguration.cs) to Java

[Java][Datetime] Port SpanishDateExtractorConfiguration from C# to Java

---

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimeExtractorConfiguration.cs

- removes extra parenthesis
- ctor formatted

[StyleCop] Fix all StyleCop warnings in PortugueseDateTimeExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/DurationExtractorChs.cs

- reodered using
- reordered enum
- reordered properties

[StyleCop] Fix all StyleCop warnings in DurationExtractorChs

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDatePeriodExtractorConfiguration.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/spanish/extractors/OrdinalExtractor.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java

* Enable SpanishDatePeriodExtractor's tests
* Port OrdinalExtractor's getInstance method from C# to Java
* Port SpanishDatePeriodExtractorConfiguration from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs) to Java

[Java][Datetime] Port SpanishDatePeriodExtractorConfiguration from C# to Java 

---

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishTimePeriodParserConfiguration.cs

- removed extra lines
- reordered ctor
- use string.Empty

[StyleCop] Fix all StyleCop warnings in EnglishTimePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/ICommonDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IHolidayParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/ITimeParserConfiguration.cs

[StyleCop] Fix StyleCop warnings in IHolidayParserConfiguration, ICommonDateTimeParserConfiguration & IMergedDateTimeParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchTimePeriodParserConfiguration.cs

- reodered ctor
- use string.Emtpy

[StyleCop] Fix StyleCop warnings in FrenchTimePeriodParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimeParser.cs

- reodered methods
- use string.Empty

[StyleCop] Fix StyleCop warnings in BaseTimeParser

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDateTimeAltExtractorConfiguration.java

* Port SpanishDateTimeAltExtractorConfiguration from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimeAltExtractorConfiguration.cs) to Java

[Java][Datetime] Port SpanishDateTimeAltExtractorConfiguration from C# to Java

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishHolidayExtractorConfiguration.java

* Change HolidayRegexes type from Array to ArrayList to match Java base implementation([BaseHolidayParserConfiguration](https://github.com/Microsoft/Recognizers-Text/blob/master/Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseHolidayParserConfiguration.java))
* Renamed HolidayRegexes to HolidayRegexList to match [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishHolidayExtractorConfiguration.cs) implementation

[Java][Datetime] Fix field name and type in SpanishHolidayExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/TimePeriodExtractorChs.cs

[StyleCop] Fix all StyleCop warnings in TimePeriodExtractorChs

---

.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimePeriodExtractorConfiguration.cs

[StyleCop] Fix all StyleCop warnings in GermanTimePeriodExtractorConfiguration

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseSetExtractor.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDateTimePeriodExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishSetExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishTimePeriodExtractorConfiguration.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/spanish/extractors/IntegerExtractor.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeExtractorTest.java

**Note:** This branch is based on #1204. We will rebase once it is merged with master.
---
* Enable SpanishSetExtractor's tests
* Port SpanishSetExtractorConfiguration from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishSetExtractorConfiguration.cs) to Java
* Fix BaseSetExtractor's TimeEveryDay method using the wrong regex

[Java][Datetime] Port SpanishSetExtractorConfiguration from C# to Java

---

JavaScript/.babelrc
JavaScript/package.json
JavaScript/test/.babelrc
JavaScript/test/runner.js

Depends on #1080 being merged before, or tests won't pass. This is due to ava v1.0.0 failing when encountering duplicated test titles.
- Update '[ava](https://github.com/avajs/ava)' dependency to v1.0.0 for [recent major release](https://blog.sindresorhus.com/ava-1-0-861d780b2d81).
- **Modify title structure for DateTime tests**; right now, title is formed with test `Input`, but different tests with different `ReferenceDateTime` have identical `Input`, so [adding the `ReferenceDateTime`](https://github.com/Microsoft/Recognizers-Text/compare/master...southworkscom:feature/southworks/update-ava-dependency#diff-f4d950b7c5709d0830a08de72c79e3d6R12) to the title for making them unique.

[DO NOT MERGE] Update 'ava' dependency to v1.0.0

---

.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/TimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishCommonDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimeAltParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishTimePeriodParserConfiguration.cs

- mainly reordering ctor and props
- fix spacing
- use stirng.Empty

[StyleCop] Fix Constructor and Properties order in Parsers

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishCommonDateTimeParserConfiguration.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java

* Add Spanish Parsers tests placeholder
* Port SpanishCommonDateTimeParserConfiguration from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishCommonDateTimeParserConfiguration.cs) to Java

[Java][Datetime] Port SpanishCommonDateTimeParserConfiguration from C# to Java

---

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/Spanish/DateTimePeriodExtractor.json

Fix "Estaré afuera de hoy a las 4 al próximo mie a las 5". Add three-letter abreviations of weekdays.

Fix "Estaré afuera de hoy a las 4 al próximo mie a las 5"

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDateExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishCommonDateTimeParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishDateParserConfiguration.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java

**Note:** This branch is based on #1237, also includes changes in #1239. We will rebase once they are merged with master. 
---
- Enable `DateParser` tests
- Port `SpanishDateParserConfiguration` from C# to Java
- Fix `DateRegexList` values assignation

[Java][Datetime] Port SpanishDateParserConfiguration from C# to Java

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/AgeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/AreaExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/CurrencyExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/DimensionExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/FrenchNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/LengthExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/SpeedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/TemperatureExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/VolumeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/WeightExtractorConfiguration.cs

- Fixed spacing.
- Reordered field, properties and methods.

[StyleCop] Fix all warnings in French Unit Extractor files

---

.NET/Microsoft.Recognizers.Text.Sequence/Constants.cs

-Add exeption to be able to use underscore in constants
-Add whitespace before = operator

[StyleCop] Fix all the warnings in Constants

---

.NET/Microsoft.Recognizers.Text.Sequence/Parsers/BaseIpParser.cs

- SA1122: Use string.Empty for empty strings
- SA1413: Use trailing comma in multi-line initializers

[StyleCop] Fix all the warnings in BaseIpParser

---

.NET/Microsoft.Recognizers.Text/Parsers/IParser.cs

- Add whitespace before comments
- Replace "" with string.Empty
- Remove space before closing brace

[StyleCop] Fix all the warnings in TextParsers

---

.NET/Microsoft.Recognizers.Text/Utilities/EnumUtils.cs
.NET/Microsoft.Recognizers.Text/Utilities/QueryProcessor.cs

- Put generic type constraints on their own line
- Remove spaces after opening braces
- Fix encoding
- Remove trailing whitespaces
- Move fields on top of methods

[StyleCop] Fix all the warnings in TextUtilities

---

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoiceRecognizerCache.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoiceRecognizerInitialization.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_Chinese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_Dutch.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_English.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_French.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_German.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_Japanese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_Portuguese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Choice/TestChoice_Spanish.cs

Fixes:
- Warning SA1100 Do not prefix calls with base unless local implementation exists
- Reorder using statements

[StyleCop] Fix warnings in DataDrivenTest/Choice

---

.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTimeRecognizerCache.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTimeRecognizerInitialization.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Chinese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_English.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_EnglishOthers.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_French.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_German.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Italian.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Japanese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Portuguese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Spanish.cs

Fixes
- Warning SA1100 Do not prefix calls with base unless local implementation exists
- Reorder using statements

[StyleCop] Fix warnings in DataDrivenTest/DateTime

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishTimePeriodExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishCommonDateTimeParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishTimePeriodParserConfiguration.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/datetime/DateTimeParserTest.java

- Enable `SpanishTimePeriodParser` tests
- Port `SpanishTimePeriodParserConfiguration` from [C#](https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishTimePeriodParserConfiguration.cs) to Java

[Java][Datetime] Port SpanishTimePeriodParserConfiguration from C# to Java

---

.NET/Microsoft.Recognizers.Text.Number/Constants.cs
.NET/Microsoft.Recognizers.Text.Number/NumberMapGenerator.cs
.NET/Microsoft.Recognizers.Text.Number/NumberOptions.cs
.NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs
.NET/Microsoft.Recognizers.Text.Number/Properties/AssemblyInfo.cs
.NET/Microsoft.Recognizers.Text.Number/RegexTagGenerator.cs
.NET/Microsoft.Recognizers.Text.Number/TypeTag.cs

- Reordered properties and methods
- Added spaces and trailing commas when needed
- Fixed spacing
- Suppress StyleCop Message in constants variables
- Remove region comments

[StyleCop] Fix warnings TextNumber Options

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Parsers/AgeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Parsers/CurrencyParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Parsers/JapaneseNumberWithUnitParserConfiguration.cs

- SA1210: Using directives should be ordered alphabetically by the namespaces - Reorder directives

[StyleCop] Fix all the warnings in Japanese Parsers

---

.NET/Microsoft.Recognizers.Text.Number/German/Extractors/CardinalExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/German/Extractors/DoubleExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/German/Extractors/FractionExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/German/Extractors/IntegerExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/German/Extractors/NumberExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/German/Extractors/OrdinalExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/German/Extractors/PercentageExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/German/Parsers/GermanNumberParserConfiguration.cs

-Reordered properties and methods
-Added spaces and trailing commas when needed
-Fixed spacing

[StyleCop] Fix warnings TextNumberGerman Extractors and Parsers

---

.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs

- Suppressed SA1310 rule to keep constant names with underscores.
- Reordered fields.
- Fixed spacing.

[StyleCop] Fix all warnings in DateTime/Constants file

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/AgeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/AreaParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/CurrencyParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/DimensionParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/LengthParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/SpanishNumberWithUnitParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/SpeedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/TemperatureParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/VolumeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Parsers/WeightParserConfiguration.cs

[StyleCop] Fix all the warnings in Spanish\Parsers

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/AgeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/AreaExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/CurrencyExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/DimensionExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/LengthExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/SpanishNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/SpeedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/TemperatureExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/VolumeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/WeightExtractorConfiguration.cs

[StyleCop] Fix all the warnings in Spanish\Extractors

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/AgeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/AreaParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/CurrencyParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/DimensionParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/LengthParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/PortugueseNumberWithUnitParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/SpeedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/TemperatureParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/VolumeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Parsers/WeightParserConfiguration.cs

[StyleCop] Fix all the warnings in Portuguese\Parsers

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/AgeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/AreaExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/CurrencyExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/DimensionExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/LengthExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/PortugueseNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/SpeedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/TemperatureExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/VolumeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/WeightExtractorConfiguration.cs

[StyleCop] Fix all the warnings in Portuguese\Extractors

---

.NET/Build.CI.cmd

- Fix Build.CI.cmd to abort and throw an error if the build fails. Currently, if the compile step fails but the tests pass, the build is marked as successful.
- We found this issue after #1280 was merged which should have broken the build but it still passes due to this issue.

[CI][DotNet] Fix Build.CI.cmd to fail on build errors

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseHolidayParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseHolidayParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/FullDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/DateTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/AgoLaterUtil.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/ConditionalMatch.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/DurationParsingUtil.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/MatchingUtil.cs

- Add whitespaces
- Replace "" with string.Empty
- Add spacing
- Reorder methods
- Document enums

[StyleCop] Fix all the warnings in DateTime files

---

.NET/Microsoft.Recognizers.Text/Matcher/AaNode.cs
.NET/Microsoft.Recognizers.Text/Matcher/AbstractMatcher.cs
.NET/Microsoft.Recognizers.Text/Matcher/AcAutomaton.cs
.NET/Microsoft.Recognizers.Text/Matcher/MatchResult.cs
.NET/Microsoft.Recognizers.Text/Matcher/MatchStrategy.cs
.NET/Microsoft.Recognizers.Text/Matcher/Node.cs
.NET/Microsoft.Recognizers.Text/Matcher/NumberWithUnitTokenizer.cs
.NET/Microsoft.Recognizers.Text/Matcher/SimpleTokenizer.cs
.NET/Microsoft.Recognizers.Text/Matcher/StringMatcher.cs
.NET/Microsoft.Recognizers.Text/Matcher/Token.cs
.NET/Microsoft.Recognizers.Text/Matcher/TrieTree.cs

- Reorder properties, fields and methods
- Add trailing comma
- Reformat setters and getters

[StyleCop] Fix all the warnings in TextMatchers

---

.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimeZoneExtractorConfiguration.cs

- Added class access modifier 'public.
- Added spaces when needed.

[StyleCop] Fix all warnings in FrenchTimeZoneExtractorConfiguration

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/AgeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/AreaExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/CurrencyExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/DimensionExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/ItalianNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/LengthExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/SpeedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/TemperatureExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/VolumeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/WeightExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/AgeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/AreaParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/CurrencyParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/DimensionParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/ItalianNumberWithUnitParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/LengthParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/SpeedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/TemperatureParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/VolumeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Parsers/WeightParserConfiguration.cs

[StyleCop] Fix all the warnings in English Parsers 

---

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimeAltExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseTimePeriodParserConfiguration.cs

- Reorder usings
- Reorder methods
- Remove extra whitespace
- Add spacing
- Change "" to string.Empty

[StyleCop] Fix all the warnings in Portuguese extractors and parsers

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/AgeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/AreaParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/CurrencyParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/DimensionParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/EnglishNumberWithUnitParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/LengthParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/SpeedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/TemperatureParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/VolumeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Parsers/WeightParserConfiguration.cs

- Fix spacing
- Reorder methods, fields and properties

[StyleCop] Fix all the warnings in English Unit Parsers

---

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Matcher/StringMatcherTest.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestHelpers.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestModel.cs

- Reorder static methods
- Add trailing comma
- Add space between properties
- Update variables to properly user upper and lower case.

[StyleCop] Fix warnings in DataDrivenTest\TestHelpers, Models, Base and StringMatcher files

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/SpanishDateTime.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/extractors/SpanishDatePeriodExtractorConfiguration.java
Specs/DateTime/Spanish/DatePeriodExtractor.json
Specs/DateTime/Spanish/DatePeriodParser.json
Specs/DateTime/Spanish/DateTimePeriodExtractor.json
Specs/DateTime/Spanish/DateTimePeriodParser.json
Specs/DateTime/Spanish/TimePeriodExtractor.json
Specs/DateTime/Spanish/TimePeriodParser.json

- Update Java regexes with `.yaml` file
- Enable regexes to match C# support
- Update all Java tests from `NotSupportedByDesign` to `NotSupported`
**Before**
**After**

[Java][Datetime] Update regexes and enable tests

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/DinoComparer.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/PrefixUnitResult.cs

- Add trailing coma in multi-line initializers
- Remove extra blank line
- Extract DinoComparer class
- Extract PrefixUnitResult class

[StyleCop] Fix all the warnings in NumberWithUnitExtractor

---

.NET/Microsoft.Recognizers.Text.Choice/Parsers/BooleanParser.cs
.NET/Microsoft.Recognizers.Text.Choice/Parsers/OptionsOtherMatchParseResult.cs
.NET/Microsoft.Recognizers.Text.Choice/Parsers/OptionsParseDataResult.cs
.NET/Microsoft.Recognizers.Text.Choice/Parsers/OptionsParser.cs

- Remove extra black space
- Add trailing coma in multi-line initializers
- Separate the file ChoiseParser on to
- OptionsOtherMatchParseResult
- OptionsParser
- OptionsParseDataResult

[StyleCop] Fix all the warnings in Choise\Parsers

---

Specs/DateTime/Spanish/DateTimePeriodExtractor.json

- Re-disabling "Hoy estaré fuera de cinco a siete" in DateTimePeriod parser for Java
- Disabling test in dotnet as well as behaviour seems incorrect

Fixing Java build break

---

.NET/Microsoft.Recognizers.Text.Choice/Chinese/Extractors/ChineseBooleanExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.Choice/Dutch/Extractors/DutchBooleanExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.Choice/English/Extractors/EnglishBooleanExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.Choice/French/Extractors/FrenchBooleanExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.Choice/German/Extractors/GermanBooleanExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.Choice/Japanese/Extractors/JapaneseBooleanExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.Choice/Portuguese/Extractors/PortugueseBooleanExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.Choice/Spanish/Extractors/SpanishBooleanExtractorConfiguration.cs

- Fixed spacing.
- Added trailing commas when needed.
- Added access modifier to classes.

[StyleCop] Fix all the warnings in BooleanExtractorConfiguration files.

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/AbstractNumberWithUnitModel.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/AgeModel.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/CurrencyModel.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/DimensionModel.cs

- SA1003:	Operator should not be followed by whitespace. - Remove whitespace
- SA1009:	Closing parenthesis should not be followed by a space - Remove space
- SA1012:	Opening brace should be followed by a space. - Add space
- SA1413:	Use trailing comma in multi-line initializers - Add trailing comma
- SA1500:	Braces for multi-line statements should not share line - Add space
- SA1305: Variable 'bAdd' should not use Hungarian notation - Rename to resultbAdd
- SA1028: Code should not contain trailing whitespace - Remove trailing whitespace

[StyleCop] Fix all the warnings in NumberWithUnit Models

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/AgeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/AreaExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/CurrencyExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/DimensionExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/ItalianNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/LengthExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/SpeedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/TemperatureExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/VolumeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/WeightExtractorConfiguration.cs

[StyleCop] Fix all the warnings in Italian Extractors

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/AgeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/AreaParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/CurrencyParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/DimensionParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/GermanNumberWithUnitParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/LengthParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/SpeedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/TemperatureParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/VolumeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/WeightParserConfiguration.cs

[StyleCop] Fix all the warnings in German Parsers

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/AgeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/AreaExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/CurrencyExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/DimensionExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/GermanNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/LengthExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/SpeedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/TemperatureExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/VolumeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/WeightExtractorConfiguration.cs

[StyleCop] Fix all the warnings in German Extractors

---

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Microsoft.Recognizers.Text.DataDrivenTests.csproj
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests.csproj
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests.xml
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimex.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexConvert.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexCreator.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexFormat.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexHelpers.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexParsing.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexRangeResolve.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexRelativeConvert.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs

- Add code analysis rule set for tests
- Add settings file
- Remove parenthesis
- Add spacing
- Add trailing comma

[StyleCop] Fix all the warnings in DataType.Tests

---

.NET/Microsoft.Recognizers.Text.DataDrivenTests/Microsoft.Recognizers.Text.DataDrivenTests.csproj
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnitRecognizerCache.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnitRecognizerInitialization.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Chinese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Dutch.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_English.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_French.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_German.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Italian.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Japanese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Portuguese.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/NumberWithUnit/TestNumberWithUnit_Spanish.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests.csproj

- Warning SA1100 Do not prefix calls with base unless local implementation exists
- Reorder using statements
- Add trailing comma

[StyleCop] Fix warnings in DataDrivenTest/NumberWithUnit

---

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs
Specs/DateTime/Spanish/DateTimePeriodExtractor.json

We applied the feedback of the PR #1351
- Fix test result
- Enable the test in Java and .Net
- Fix .Net BaseDateTimePeriodExtractor
**Before**
**After**

 [DateTime] Fix DateTimePeriodExtractor test

---

.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateParserConfiguration.cs

- Move constructor before properties
- Suppressed warning message because the method StringExtension will be refactored.

[StyleCop] Fix warnings in Spanish and Portuguese DateParserConfiguration

---

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/TimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/TimeParser.cs

- move constructor initializers on their own line

[StyleCop] Fix warnings in English and German TimeParser

---

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/StringExtension.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/PortugueseDateTime.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/SpanishDateTime.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/spanish/parsers/SpanishDateParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/StringExtension.java
Patterns/Portuguese/Portuguese-DateTime.yaml
Patterns/Spanish/Spanish-DateTime.yaml

Remove StringExtension 'Normalized' from Spanish and Portuguese parsers and create a unique String extension in utilities. This runs and replaces characters that are previously loaded using a YAML file.
- Add Spanish SpecialCharacters dictionary in YAML
- Add Portuguese SpecialCharacters dictionary in YAML
- Create in utilities StringExtension class with the normalized method
- Refactor Portuguese and Spanish parsers to start using this StringExtension
- Port changes to Java

[DateTime] Refactor StringExtension 'Normalized' method

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDatePeriodExtractorConfiguration.cs

- Renamed regex variable 'AndRegex' to match used regex 'RangeConnectorRegex'

[DotNet][DateTime] Renamed regex variable 'AndRegex' to match used regex

---

.NET/Microsoft.Recognizers.Definitions/Microsoft.Recognizers.Definitions.csproj
.NET/Microsoft.Recognizers.Definitions/Utilities/DefinitionLoader.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Properties/AssemblyInfo.cs

- Remove or add spacing when needed
- Reorder parameters
- Add header

 [StyleCop] Fix all the warnings in Definitions 

---

JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/extractors.ts

- Change the method DinoComparer to StringComparer for more clarity within the code. This method will take two strings and compare them, taking into consideration that they may be null or empty. 
- The method was refactored for a more clear implementation. 
- The extractor.ts file was updated to work with the changed name.
All the tests passed succesfully

[JavaScript] Rename DinoComparer to StringComparer and update implementation 

---

.NET/Microsoft.Recognizers.Text.Number/Extractors/BasePercentageExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.csproj
.NET/Microsoft.Recognizers.Text.Number/NumberMode.cs
.NET/Microsoft.Recognizers.Text.Number/Spanish/Parsers/SpanishNumberRangeParserConfiguration.cs

- XML comment analysis warning
SpanishNumberRangeParserConfiguration  …
- Move constructor before properties
- Move constructor initializers on their own line
- Add class access modifier
BasePercentageExtractor  …
- Reorder properties a fields
- Set field to a property to keep the variable name with upper-case
- Add returns comments in methods
- Add trailing coma in multi-line initializers
- Use String.Empty instead empty strings
NumberMode  …
- Update comment to fix CS1570 XML comment has badly formed

[StyleCop] Fix warnings in Text.Number Project

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/BaseMergedUnitParser.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs
.NET/Microsoft.Recognizers.Text/Matcher/AcAutomaton.cs
.NET/Microsoft.Recognizers.Text/Matcher/TrieTree.cs

*Disclaimer*: To fix some StyleCop warnings we might incur in breaking changes. In this case, related to protected properties that might be used by end users.
- Rename protected field to match the recommended casing

[StyleCop]  Add warning fixes generating Breaking Changes 

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishDateTimeExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/extractors/EnglishTimePeriodExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/parsers/EnglishCommonDateTimeParserConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/english/utilities/EnglishDatetimeUtilityConfiguration.java

The `EnglishDatetimeUtilityConfiguration` class was inside the `parsers` folder, we moved it onto the `utilities` folder. 
All the tests passed successfully

[Java][Datetime] Move EnglishDatetimeUtilityConfiguration class to utilities folder

---

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/Spanish/DatePeriodExtractor.json

DatePeriodExtractor: ❌(86 of 365 still unsupported)
Fix Spanish DatePeriod cases below type.
1.entre miércoles y viernes de la próxima semana
2.la próxima semana entre miércoles y viernes
3.comienzos de la próxima semana
4.finales de la semana pasada
5.años $year

Fix spanish dateperiod cases

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimeAltExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchTimePeriodExtractorConfiguration.cs

- Reorder fields, properties, methods and constructors
- Add and remove spaces when needed
- Remove unnecessary parenthesis

[StyleCop] Fix all the warnings in Dutch Extractors

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchCommonDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimeAltParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchHolidayParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/TimeParser.cs

- Reorder fields, properties, methods and constructors
- Add and remove spaces when needed
- Remove unnecessary parenthesis
- Reorder using statements

[StyleCop] Fix all the warnings in Dutch Parsers

---

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/Spanish/DateTimePeriodExtractor.json

Fixed three specs. The contents of these three specs are all like "rest of day".
Add a new "day" unit, "jornada" used in RestOfDateTimeRegex.

Fill in the blank of RestOfDateTimeRegex and add a new Unit "jornada"

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeExtractor.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDateTimeExtractor.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/FrenchDateTime.java
JavaScript/packages/recognizers-date-time/src/dateTime/baseDateTime.ts
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
JavaScript/packages/recognizers-date-time/src/resources/frenchDateTime.ts
Patterns/French/French-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_datetime.py
Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py
Python/libraries/recognizers-date-time/recognizers_date_time/resources/french_date_time.py
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json

For example, "Your renewal will be January 18, 2019.  You have until then to add the paid support. @Cortana, Please schedule a Skype call at 3pm today."
woud return:  "January 18, 2019"; "3pm"; "today", where "January 18, 2019" and "3pm today" are expected.
The fix applies to .Net and Java.
Javascript and Python has another issue when recognize "You have until then to add the paid support. @Cortana, Please schedule a Skype call at 3pm today.". The fix for Javascript and Python would be available in upcoming PRs.

Fix bug related to wrong recognition when there are more than one time phrases present

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/MergedParser.json

Cases fixed in this PR include:
"2100" in "Tel: 000 111 82-2100"
"2010-2015" in "Tel: +86 138-2010-2015"
Support for Javascript, Java and Python would be in the upcoming PRs

Fix wrongly extracted DateRange in dash-separated sequence

---

.NET/Build.cmd

When creating a pull request that inadvertently included StyleCop issues we found that the AzureDevOps build would not fail but the AppVeyor one did.
In the `Build.cmd` file we changed the `&` operand to `&&` because while `&` runs the second script without taking into consideration the outcome of the first one, with `&&` we make sure that the first script runs ok before running the second one.
We got to this solution after making a couple tests on AzureDevOp. If instead of running the original `Build.cmd` script from a single task we ran the `build.ci.cmd` and `tests.ci.cmd` scripts separately in two different tasks, it would work as expected. With this, we realized the issue was that even if the build script failed, the `tests.ci.cmd` script would run and would end up throwing a …

Make Azure DevOps build process fail on StyleCop issues

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
Patterns/English/English-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json

For example, "book my time for swimming every Tuesday and Thursday 19:00 - 21:00"
should return: "every Tuesday" and "Thursday 19:00 - 21:00"
The fix applies to .Net, Java, Javascript, Python.
Issue #1482

Fix regression in time span extraction

---

.NET/buildtools/updateAssemblyInfo.ps1

Code signing script introduces indentation inconsistency, which leads to build breaks as we now treat warnings as errors in the build.

Fix build script for code signing (indentation now causes build break)

---

.NET/Microsoft.Recognizers.Text.Choice/CreatePackage.cmd
.NET/Microsoft.Recognizers.Text.Choice/Microsoft.Recognizers.Text.Choice.nuspec
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/CreatePackage.cmd
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/Microsoft.Recognizers.Text.DataTypes.TimexExpression.nuspec
.NET/Microsoft.Recognizers.Text.DateTime/CreatePackage.cmd
.NET/Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.nuspec
.NET/Microsoft.Recognizers.Text.Number/CreatePackage.cmd
.NET/Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.nuspec
.NET/Microsoft.Recognizers.Text.NumberWithUnit/CreatePackage.cmd
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.nuspec
.NET/Microsoft.Recognizers.Text.Sequence/CreatePackage.cmd
.NET/Microsoft.Recognizers.Text.Sequence/Microsoft.Recognizers.Text.Sequence.nuspec
.NET/Microsoft.Recognizers.Text/CreatePackage.cmd
.NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.nuspec
.NET/Recognizers-Text.ruleset

`<licenseUrl>`  will be deprecated - https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#license-url-deprecation

Moving nuget package definitions to use <license> tag

---

.NET/Microsoft.Recognizers.Text.DateTime/Utilities/DateTimeFormatUtil.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDatePeriodParser.java
JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts
JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_dateperiod.py
Specs/DateTime/English/DatePeriodParser.json

Revise JavaScript baseDatePeriod to use ISO standard. [Issue #1442](https://github.com/Microsoft/Recognizers-Text/issues/1442)

Revise relative week parsing to use ISO 8601 standard

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs

.NET's TimexResolver is resolving Date types of Sunday as Monday, this change updates the DayOfWeek to use when encountering the "XXXX-WXX-7" Timex expression.
This issue was previously closed but the behavior still exists: [https://github.com/Microsoft/Recognizers-Text/issues/688](https://github.com/Microsoft/Recognizers-Text/issues/688)

Update TimexResolver to equate Timex "XXXX-WXX-7" as Sunday

---

.NET/Microsoft.Recognizers.Definitions.Common/Italian/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Korean.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs
.NET/Microsoft.Recognizers.Text.Number/Italian/Parsers/ItalianNumberParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/Japanese/Parsers/JapaneseNumberParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Parsers/KoreanNumberParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs
.NET/Microsoft.Recognizers.Text/Extractors/Metadata.cs
JavaScript/packages/recognizers-number/src/resources/japaneseNumeric.ts
Patterns/Italian/Italian-Numbers.yaml
Patterns/Japanese/Japanese-Numbers.yaml
Patterns/Korean/Korean-Numbers.yaml
Python/libraries/recognizers-number/recognizers_number/resources/japanese_numeric.py
Specs/Number/Chinese/OrdinalModel.json
Specs/Number/Dutch/OrdinalModel.json
Specs/Number/French/OrdinalModel.json
Specs/Number/German/OrdinalModel.json
Specs/Number/Italian/OrdinalModel.json
Specs/Number/Japanese/OrdinalModel.json
Specs/Number/Korean/OrdinalModel.json
Specs/Number/Portuguese/OrdinalModel.json
Specs/Number/Spanish/OrdinalModel.json

add "relativeTo" and "offset" into other languages as well.
Their values will be an empty string in other languages(expect English).
English totally support this function now.

Add Ordinal attributes into other languages

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/parsers/BaseNumberParser.java
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/EnglishNumeric.java
JavaScript/packages/recognizers-number/src/number/parsers.ts
JavaScript/packages/recognizers-number/src/resources/englishNumeric.ts
Patterns/English/English-Numbers.yaml
Python/libraries/recognizers-number/recognizers_number/number/parsers.py
Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py
Specs/Number/English/NumberModel.json
Specs/Number/English/NumberRangeModel.json

Query: more than half people came here
expected result: "half" by itself could be tagged and resolved to 0.5

[EN NumberRange] Cannot recognize "more than half" (#1173)

---

.NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs

Currently, only English is considered to support the Subtype field in the resolution in the Number Recognizer. This proposed PR changes the implementation to allow for more languages to be added, once they support this field. Besides English, I have added Swedish to the list of languages supporting subtypes.

Update definition and handling of subtype support for a language in Number recognizer

---

Python/libraries/recognizers-number/recognizers_number/number/japanese/__init__.py
Python/libraries/recognizers-number/recognizers_number/resources/__init__.py

After publishing **_Recognizers-Text-Number_** project to **PyPI** and installed it locally, we noticed that Japanese resources were missing in the installation.
- Add init file in Number Japanese to import extractors and parsers to the project.

Add import of Japanese resources in Recognizers-Number project

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
Patterns/English/English-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json

Fix: [EN DateTimeV2] Dates separated from year by connector (in) are not properly recognized #1566

Fix cases like "on 26 june to 28 june in 2020" #1566

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimeAltExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimeZoneUtility.cs
Specs/DateTime/English/DateTimeModelComplexCalendar.json

Modify the method that DatetimePeriod handling the timeZone to same method as TimePeriod. 
This PR replaces #1611.

Fix cases like "thursday morning est" where timezone is tagged, but not parsed in resolution

---

Python/.pre-commit-config.yaml
Python/build.ci.cmd
Python/requirements.txt
Python/tests/requirements.txt

There are many files that do not comply with [PEP 8](https://www.python.org/dev/peps/pep-0008/) on the Python side.
We suggest adding [autopep8 ](https://pypi.org/project/autopep8/) and [flake8](http://flake8.pycqa.org/en/latest/) to the repository. This tool lets us easily fix style errors by just running a command. 
We used [pre-commit](https://pre-commit.com/) to create a pre-push hook, and using the resources provided by pre-commit: [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) and [autopep8](https://github.com/pre-commit/mirrors-autopep8).
1. Move `requirements.txt` to the root of the Python folders
2. Add autopep8, flake8 and pre-commit to the `requirements.txt`
3. Add `.pre-commit-config.yaml` to define the pre-push hook
4. Add to `build.ci.cmd` the installing …

[Python] Add pre-push hook

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/NumberWithUnitRecognizer.cs
Patterns/Italian/Italian-NumbersWithUnit.yaml
Specs/NumberWithUnit/Italian/DimensionModel.json

Cleaned and reviewed version of #1618. 
Two test cases skipped related to "l" being falsely recognized as a unit while in the input it is a preposition. 
l'amministrazione -> l' -> l
l'autostrada -> l' -> l

[.NET] Italian Dimension support

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDatePeriodExtractor.java
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json

Fix cases like "from three thirty to four thirty"  which would be wrong extracted in DatePeriodExtractor.
**NOTE**: This PR is a temporary fix, and MatchYearPeriod code will be refactored later.

Fix  wrong recognition for  "from three thirty to four thirty"

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Italian/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/EnglishNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/ItalianNumberWithUnitExtractorConfiguration.cs
Patterns/English/English-NumbersWithUnit.yaml
Patterns/Italian/Italian-NumbersWithUnit.yaml
Specs/NumberWithUnit/English/DimensionModel.json
Specs/NumberWithUnit/Italian/DimensionModel.json

Add AmbiguityFiltersDict contains "'" filter in English and Italian.
Fix cases like "i ' m tried", 'm' should not be recognized.

[.NET] Add unit "'" filter in English and Italian

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
Patterns/English/English-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json

Fix cases like "11:30 am to 12:30 december 27th", "30 December" would be wrong recognized
Also fix cases like "$12 december 27th"

[DateTime] Fix wrong recognition for "12:30 December 27"

---

Python/libraries/datatypes-timex-expression/datatypes_timex_expression/english/__init__.py
Python/libraries/datatypes-timex-expression/datatypes_timex_expression/english/english_timex_convert.py
Python/libraries/datatypes-timex-expression/datatypes_timex_expression/english/english_timex_relative_convert.py
Python/libraries/datatypes-timex-expression/datatypes_timex_expression/english/timex_constants.py

Merge after #1707 
Based on `Microsoft.Recognizers.Text.DataTypes.TimexExpression`, we migrated 
English folder with their respectives classes: TimexConstants, TimexConvert, and TimexRelativeConvert.
Porting of the English modules: `english_timex_ convert`,`english_timex_relative_convert`, and `timex_constants`.
Find each file’ details below:
**timex_constants** file
- days
- months
- date_abbreviation
- hours
- seasons
- weeks
- day_parts
**english_timex_convert** file
- english_convert_date
- convert_time
- convert_duration_property_to_string
- convert_timex_duration_to_string
- convert_duration
- convert_date_range
- convert_time_range
- convert_date_time
- convert_date_time_range
- convert_timex_to_string
- convert_timex_set_to_string
**english_relative_convert** file
- get_date_day
- …

[Python] Timex migration – English classes

---

Python/libraries/datatypes-timex-expression/CreatePackage.cmd
Python/tests/datatypes/test_time.py
Python/tests/datatypes/test_timex.py
Python/tests/datatypes/test_timex_convert.py
Python/tests/datatypes/test_timex_date_helpers.py
Python/tests/datatypes/test_timex_format.py
Python/tests/datatypes/test_timex_helpers.py
Python/tests/datatypes/test_timex_parsing.py
Python/tests/datatypes/test_timex_range_resolver.py
Python/tests/datatypes/test_timex_relative_convert.py
Python/tests/datatypes/test_timex_resolver.py

Merge after #1708 
Based on Microsoft.Recognizers.Text.DataTypes.DataDrivenTests, we migrated the following tests modules: _TestTime_, _TestTimex_, _TestTimexConvert_, _TestTimexDateHelpers_, _TestTimexFormat_, _TestTimexHelpers_, _TestTimexParsing_, _TestTimexRangeResolve_, _TestTimexRelativeConvert_, and _TestTimexResolver_.
The following tests modules were migrated inside `tests/datatypes` folder: 
- test_time
- test_timex
- test_timex_convert
- test_timex_date_helpers
- test_timex_format
- test_timex_helpers
- test_timex_parsing
- test_timex_range_resolver
- test_timex_relative_convert
- test_timex_resolver
The whole migration includes **217 tests**. Considering these changes, the project's tree folder will be something like this:
Below, you can find all the tests running …

[Python] Timex migration – Tests classes

---

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/DoubleExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/FractionExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/IntegerExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/MergedNumberExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/NumberExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/NumberRangeExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/OrdinalExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Extractors/PercentageExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Parsers/TurkishNumberParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Parsers/TurkishNumberRangeParserConfiguration.cs
Patterns/Turkish/Turkish-Numbers.yaml
Specs/Number/Turkish/PercentModel.json

Follow up to #1653. 
9 passes 2 skips.
Issues: 
- written negative percentage, "-5%" actual "5%"
"minus five" is captured by BaseNumbers, but in Turkish, the order is different "eksi yüzde beş" directly translates to "minus percent five" since minus sign does not come before the number directly but comes before the number with percent,  it is not resolved. 
Explanation of modified localization: 
NumberWithSuffixPercentage can only be used with a (Num+Suffix)(Percent+Suffix), e.g. 210'un yüzdesi (per cent of 210). However, "yüzde 210" has the same meaning and more common than "210'un yüzdesi". Also, "yüzdesi" is mostly used as "percentage" and used with nouns more frequently than numbers, e.g. "kütle yüzdesi" (meaning "mass percentage").

[.NET] Turkish Numbers (Percent) support

---

.NET/Microsoft.Recognizers.Definitions.Common/Microsoft.Recognizers.Definitions.Common.csproj
.NET/Microsoft.Recognizers.Text.Choice/Microsoft.Recognizers.Text.Choice.csproj
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/Microsoft.Recognizers.Text.DataTypes.TimexExpression.csproj
.NET/Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.csproj
.NET/Microsoft.Recognizers.Text.Sequence/Microsoft.Recognizers.Text.Sequence.csproj
.NET/README.md
.NET/build.sh

**Status**
* It builds :)
* It can be imported as a .net assembly by the demo applications, compile with them and executed perfectly as far as I could try.
**Issues**
* Had to manually create the target platform on buildfiles for that purpose (sorry, I'm clueless with MSBuild)
* Could not make vstest run on macOS.
* Was only tested on macOS 10.13.2 and Arch Linux with kernel 4.14.4 (both with dotnet-sdk 2.1 and msbuild 15.4), so I don't really know how solid this is different environments.
Signed-off-by: Luiz Carlos Cavalcanti <cavalcanti.luiz@gmail.com>

Add build script for MacOS and Linux

---

Python/libraries/recognizers-choice/setup.py
Python/requirements.txt

This PR will resolve issue [#1739](https://github.com/microsoft/Recognizers-Text/issues/1739).
- Remove _Grapheme_ dependency from the _requirements.txt_
- Add  _Grapheme_ dependency into _setup.py_
- Add the following import _from recognizers_choice import ChoiceRecognizer_ into the _test_runner_choice_
- Run _pip install -e .\libraries\recognizers-choice_ to install the choice library among with the  missing _Grapheme_ dependency
- Run _pytests test_runner_choice_ from the tests folder 
You can find the whole process in the image below:

[Python] Include Grapheme as a dependency in recognizers_choice

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDatePeriodParserConfiguration.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json

This fixes #1742 and #923 
Currently it only supports .NET

[FR DateTimeV2] Fix wrong recognize of relative dateranges (#1742)

---

Python/libraries/recognizers-text/setup.py
Python/requirements.txt

Fix ISSUE #1740 
When running some test methods from a file with a reference to _recognizers-text_ after installing this package directly (i.e, by using the _pip install_ command instead of the _build.cmd_ file), and without having the `emoji` package installed in your environment, the next error will be prompted:
In order to fix this, it's necessary to add `emoji` as a requirement in the `setup.py` file.
For reproducing the current ISSUE, follow these steps without the changes performed in this PR:
1. Ensure that _emoji_ is not installed in your environment
1. Add a reference to _recognizers-text_ in, for example, _test_initialization_number_with_unit_recognizer.py_ file:
1. Manually install the _recognizers-text_ package using `pip install -e .\libraries\recognizers-text`
1. Run the …

[Python] Recognizers-text - Add emoji as required dependency

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
Specs/DateTime/English/DateTimePeriodParser.json
Specs/DateTime/Italian/DateTimePeriodParser.json
Specs/DateTime/Spanish/DateTimePeriodParser.json

The modification in ParseTimePeriod serves to correctly address cases such as "on Dec 9th between 8am and 2pm" so that both particles 'am' and 'pm' are extracted and associated to the corresponding time entities (originally only one particle was extracted and associated to both times causing errors in cases where the two particles differ)
The modification in MergeTwoTimePoints serves to take into account minutes when calculating the duration so that for example "from half past seven to 4pm of tomorrow" returns 'PT8H30M' (the original output was 'PT8H').
Spanish case is an example of this point it was returning PT8H instead of the correct PT8H30M

[.NET] DateTime suggested solution for BaseDateTimePeriodParser

---

JavaScript/.eslintrc.js

When applying the autofix, the indentation of certain places was incorrect (see PR#N). After some investigation, we found the rule to fix this.
A new rule was added that makes sure the indentation is the right one:
` 'indent': ['error', 4]`
**Pre lint:fix**
**With old rules**
**With new rule**

[JavaScript] Add an indentation rule to ESlint

---

.NET/Microsoft.Recognizers.Text.Number/Italian/Parsers/ItalianNumberParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs
Specs/Number/Italian/NumberModel.json
Specs/Number/Italian/OrdinalModel.json

Support for skipped cases:
[uno e mezzo] (one and a half)
[undicesimo] (eleventh)
The fix for the second pattern required a modification to BaseNumberParser (switching the order of Cardinal and Ordinal maps for Italian)

[.NET] Italian Number support for skipped cases

---

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs
Patterns/Turkish/Turkish-DateTime.yaml
Patterns/Turkish/Turkish-Numbers.yaml
Specs/DateTime/Turkish/DateExtractor.json
Specs/DateTime/Turkish/DateParser.json

DateExtractor : pass: 54 | fail: 2
DateParser: pass: 89 | fail: 3
Failing Cases:
- "dünden iki gün önce neredeydin" (where were you two days before yesterday?)
the structure of the sentence in Turkish is "yesterday two day before where were you?".
It is not supported because the method ExtractorDurationWithBeforeAndAfter only checks for the group "day" after the duration match "two day before".
- "Yarından itibaren üç hafta sonra uygun musun?" (Are you available three weeks from tomorrow?)
Same as above, 'Yarından' (tomorrow) appears before the duration match 'itibaren üç hafta sonra' (after three weeks from)
- "iki bin yılı Eylül'ün onunda" (on the tenth of September, two thousand)
similarly to the previous cases, here the year 'iki bin yılı' (two thousand) comes before the …

[.NET] Turkish DateTime Date support

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Patterns/German/German-DateTime.yaml

Adding the character m to the regular expression handling jeden Dienstag like the other propositions:
```
EachUnitRegex: !nestedRegex
def: (?<each>(jede(s|r|n|m)?|alle)(?<other>\s+andere(n)?)?\s*{DurationUnitRegex})
references: [ DurationUnitRegex ]
EachPrefixRegex: !simpleRegex
def: \b(?<each>(jede(r|n|s|m)?|alle)\s*$)
SetEachRegex: !simpleRegex
def: \b(?<each>(jede(r|n|s|m)?|alle)\s*)
```

correcting the recognition of the utterances like an jedem Dienstag (#1812)

---

.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Turkish/Parsers/TurkishNumberParserConfiguration.cs
Patterns/Turkish/Turkish-Numbers.yaml
Specs/Number/Turkish/NumberModel.json
Specs/Number/Turkish/OrdinalModel.json

Fixes to cases:
- "10.000tl", originally recognized as currency "10000tl", cardinal "10" and ordinal "10.". Now only recognized as currency.
- Added support for compound numbers (used informally) e.g. "onbinaltıyüz" ("on bin altı yüz" -> 10600)

[.NET] Turkish Number fixes

---

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseMergedExtractorConfiguration.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/ChineseDateTime.java
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts
JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts
Patterns/Chinese/Chinese-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py
Specs/DateTime/Chinese/DateTimePeriodParser.json
Specs/DateTime/Chinese/TimeParser.json
Specs/NumberWithUnit/Chinese/AgeModel.json

To fix the wrong extractions of "早" in "早稻田" and "晚" in "晚礼服".
Now the single word "早" and “晚” won't be recognized as an entity.

[CN DataTimeV2] Finalize bug fix for “早”, “晚”

---

JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_merged.py
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/DateTimeModelExperimentalMode.json
Specs/DateTime/English/MergedParser.json

- Simulate C# RightToLeft Regex option in JS & Py
- Enable some test.
TODO: It still not support some tests with "since" Mod in JS & Py

[JS Py DateTimeV2] Revise extractor for "after" "before"

---

.NET/build/package/README.txt

This issue happens in MacOS/Linux (#1809).

Workaround for copy failure if "/build/package" doesn't exist

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateTimeModel.json

[DE DateTimeV2] Extend recognition to support open ranges with "ab" and "bis" #1855

---

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
Patterns/Spanish/Spanish-DateTime.yaml

Fix to match Saturday in its two letter format 
Currently, it does not parse correctly when Saturday is written with two letters and its accent mark
E.g. query: `sá 9 feb 1991`
Before:
```json
{
"entity": "09 feb 1991",
"type": "builtin.datetimeV2.date",
"startIndex": 3,
"endIndex": 13,
"resolution": {
"values": [
{
"timex": "1991-02-09",
"type": "date",
"value": "1991-02-09"
}
]
}
}
```
After
```json
{
"entity": "sá 09 feb 1991",
"type": "builtin.datetimeV2.date",
"startIndex": 0,
"endIndex": 13,
"resolution": {
"values": [
{
"timex": "1991-02-09",
"type": "date",
"value": "1991-02-09"
}
]
}
}
```

Fix pattern for Spanish abbreviated Saturday format

---

.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Turkish.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDatePeriodParserConfiguration.cs
Specs/DateTime/Turkish/DatePeriodExtractor.json
Specs/DateTime/Turkish/DatePeriodParser.json

DatePeriodExtractor : pass: 192 | fail: 1
DatePeriodParser: pass: 173 | fail: 1
Failing case:
"Bu görev dünden 2 gün önce yapılmalıydı." 
This case corresponds to "This task should have been done more than 2 days before yesterday"
but it translates to "This task should have been done 2 days before yesterday"
and there is no meaningful way to express the concept of "more than" in Turkish in this sentence.
Other comments:
There is no difference between "in" and "within" in Turkish, both translate to "içinde", so the case
"[iki hafta içinde] bir toplantı ayarla" 
can be translated to both
"schedule a meeting [in two weeks]" and "schedule a meeting [within two weeks]".
Therefore, we added the result field to this case. 
The Date case 
"Aynı gün döneceğim" 
corresponding to "I'll go back the …

[.NET] Turkish DateTime DatePeriod support

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java
JavaScript/packages/recognizers-date-time/src/resources/englishDateTime.ts
JavaScript/packages/recognizers-date-time/src/resources/spanishDateTime.ts
Patterns/English/English-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py
Specs/DateTime/English/DateExtractor.json
Specs/DateTime/English/DateParser.json
Specs/DateTime/English/DatePeriodExtractor.json
Specs/DateTime/English/DatePeriodParser.json
Specs/DateTime/English/DateTimeModel.json

Fix #1894 
- support Date cases like 2019/sep/21 and 2019-sep-20.
- support DatePeriod cases like 2019/sep/21 to today.

[EN DateTimeV2] Add support for cases like 2019/sep/21

---

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDateTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/JapaneseDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/JapaneseDateTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/FullDateTimeParser.cs
.NET/Microsoft.Recognizers.Text/Extractors/Metadata.cs
JavaScript/packages/recognizers-date-time/src/dateTime/baseDateTime.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateTimeConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateTimePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/constants.ts
JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts
JavaScript/packages/recognizers-text/src/metaData.ts
Specs/DateTime/Chinese/DateTimeModel.json

Fixes #1885 in JavaScript. Add support case for "5天前", ”5小时后“ in JS.

[CN DateTimeV2 JS] Add support for relative cases like "5天前"

---

Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/Spanish/DateExtractor.json

Fix to match September in its three letter format

Fix pattern for Spanish abbreviated September format

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs
Specs/NumberWithUnit/English/CurrencyModel.json
Specs/NumberWithUnit/English/DimensionModel.json

- Fix cases like "1 $ 10 $" "$ 20,000.00 $ 37,305.97"
- Add a select method for curreny unit

[.NET | EN Currency] Fix currency cases with potential entity overlaps

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexFormat.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexRegex.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs

I've logged some previous PRs but was using the Regex directly - now I'm using the Resolver directly and seeing how it works - this is a more comprehensive PR, including a new unit Test. This deals with a
"2nd week in August" example scenario properly ("XXXX-08-W02").

Catering for a week-in-month scenario, eg. "XXXX-08-W02"

---

Python/libraries/datatypes-timex-expression/datatypes_timex_expression/english/english_timex_relative_convert.py
Python/libraries/datatypes-timex-expression/datatypes_timex_expression/timex_date_helpers.py
Python/tests/datatypes/test_timex.py

Issue #1940
- Ignore time when comparing dates
- Add `now` when recognizing present types
In order to test this issue, we created a small script using the repro steps from the original issue.

[TimexExpression] Modify TimexDateHelpers.date_part_equal() to fix Timex.to_natural_language() 

---

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_date.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/english/base_configs.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/french/base_configs.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/spanish/base_configs.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/utilities.py
Python/libraries/recognizers-text/recognizers_text/utilities.py

This PR ports the changes made on PR#1839 and PR#1936 for .NET to Python.
**MatchingUtil** 
- `get_ago_later_index` (logic changes) [#1936] using [#1839]
- `get_in_index` to `get_term_index` (rename for parity)
**AgoLaterUtil**
- `extractor_duration_with_before_and_after` (logic changes)  [#1839] + [#1936]
**DateTimeUtilityConfiguration**
- `@ property range_prefix_regex` (new property).
- `@property check_both_befor_after` (new property).
- `@property date_unit_regex` (new property).
- `extract_in_connector` update the logic to avoid issues when there is no match.

[Python] Port changes for Utilities (MatchingUtil and AgoLaterUtil) 

---

Python/libraries/resource-generator/lib/yaml_parser.py

According to the ISSUE #1963, the CheckBothBeforeAfter resource definition in the YAML file is set to `false`, but when the `resource-generator` is executed in Python, the property is set as `true`.
Python considers the following things to be `False`:
- None
- False
- Zero
- Empty sequences and mappings (strings, lists, tuples, dicts)
The current implementation tries to convert the string with the value `false` to a boolean, which ends up as `True` as it is a non empty string. 
To fix the issue, the method `from_yaml` from the class **Bool** was modified to return a value depending on the string (either `true` or `false`).

[Python] Modify yaml_parser.py to parse bools correctly 

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/EnglishDateTime.java
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateExtractor.json
Specs/DateTime/German/DateParser.json
Specs/DateTime/German/DateTimeModel.json

This fixes #1946 
- Revise a regex that led to this bug.
- Add test.

[DE DateTimeV2] Fix wrong result when Date entity  contains "sende"

---

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_merged.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/constants.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/english/merged_extractor_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/french/merged_extractor_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/spanish/merged_extractor_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/resources/english_date_time.py
Python/libraries/recognizers-number/recognizers_number/resources/chinese_numeric.py
Python/libraries/recognizers-number/recognizers_number/resources/english_numeric.py
Python/libraries/recognizers-number/recognizers_number/resources/french_numeric.py
Python/libraries/recognizers-number/recognizers_number/resources/japanese_numeric.py
Python/libraries/recognizers-number/recognizers_number/resources/portuguese_numeric.py
Python/libraries/recognizers-number/recognizers_number/resources/spanish_numeric.py

This PR ports the changes made on PR #1936 for .NET to Python.
**BaseMergedDateTimeExtractor**
- `try_merge_modifier_token` (logic changes) [#1936]
- `assign_mod_metadata` (to static method)
- `_filter_item` (to static method)
- `has_token_index` (to static method) and remove old duplicated version
**MergedExtractorConfiguration (and sublcasses)**
- `@property check_both_before_after` (new property)
**Constants**
- `HAS_MOD` (new constant)
**Resources**
- Update resources after last `resource-generator` change

[Python] Port the changes on BaseMergedExtractor 

---

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_dateperiod.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/dateperiod_extractor_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/english/dateperiod_extractor_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/french/dateperiod_extractor_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/spanish/dateperiod_extractor_config.py

This PR ports the changes made on PR #1884 PR #1936 for .NET to Python.
**BaseDatePeriodExtractor**
- `match_duration` (logic changes) [#1884] + [#1936]
- `__get_token_for_regex_matching` (new parameter and logic changes) [#1884]
- `merge_multiple_extractions` (logic changes) [#1884]
- `single_time_point_with_patterns` (logic changes) [#1884] + [#1936]
- `__extract_within_next_prefix` (new method) [#1884]
- `_match_within_next_affix_regex` (parameter changes) [#1936]
**DatePeriodExtractorConfig (and subclasses)**
- `property previous_prefix_regex` (new property)

[Python] Port the changes on BaseDatePeriodExtractor

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDatePeriodParser.java
JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_dateperiod.py
Specs/DateTime/English/DatePeriodParser.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/Turkish/DatePeriodParser.json

This fixes #1984 (.NET only)
- Make quarter Timex result generalized when no year contains.
- Add tests

[EN DateTime] Make Q1/Q2 result generalized (.NET)

---

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDurationExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiCommonDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Utilities/HindiDatetimeUtilityConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDurationParserConfiguration.cs
Patterns/Hindi/Hindi-DateTime.yaml
Specs/DateTime/Hindi/DurationExtractor.json
Specs/DateTime/Hindi/DurationParser.json

DateTimeModel: 34 passing, 50 failing.
Comments:
The case "मैं साढ़े 3 सेकंड के लिए बाहर रहुंगा" (I'll leave for 3 and a half seconds)
required a change to the base Extractor and Parser analogous to the ones implemented for Turkish because the modifier "and a half" precedes the number. The case has been added to DurationParser.json (originally, it was only in DurationExtractor.json)

[.NET] Hindi DateTime Duration support

---

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiSetExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiSetParserConfiguration.cs
Patterns/Hindi/Hindi-DateTime.yaml
Patterns/Hindi/Hindi-Numbers.yaml
Specs/DateTime/Hindi/DatePeriodExtractor.json
Specs/DateTime/Hindi/DatePeriodParser.json
Specs/DateTime/Hindi/SetExtractor.json
Specs/DateTime/Hindi/SetParser.json
Specs/DateTime/Hindi/TimeExtractor.json
Specs/DateTime/Hindi/TimeParser.json

Extractor: 26 passing, 1 failing;
Parser: 24 passing, 2 failing.
DateTimeModel: 42 passing, 42 failing.
Failing cases:
- "क्या मैं 09th मई को 2 रातों के लिए बुकिंग करवा सकता हूँ " ("Can I do a booking for the 09th of May for 2 nights?"). Hindi does not use plurals of weekdays such as "on Mondays" or "mornings", so these cases cannot be supported.
- "मैं हर दो दिन में जाऊँगा" (I'll leave each two days)
- "मैं हर तीन हफ्ते में जाऊँगा" (I'll leave every three week)
The above two cases are literally "I'll leave each in two days", so the entity "in two days" is processed as date instead of duration and gives a different result. We still have to find the best way to deal with them (a solution is to include "in" in the duration extraction, but this seems to break test cases in other sub-types, …

[.NET] Hindi DateTime Set support

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Dutch/NumberDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs
Patterns/Dutch/Dutch-DateTime.yaml
Patterns/Dutch/Dutch-Numbers.yaml
Specs/DateTime/Dutch/DateExtractor.json
Specs/DateTime/Dutch/DateParser.json

All test cases passes.
Notes:
Some test cases were updated due to ambiguous translations or when the corresponding English test case made use of some particular arrangement of words.
BaseDurationParser has been modified to take into account the case when "business day" is just one word ("werkdag" in Dutch).

[.NET] Dutch DateTime Date support

---

Specs/DateTime/Turkish/DatePeriodExtractor.json

- There is a case has merge issue and marked as NotSupported for now.

[.NET] Mark Turkish DateRange failed spec as NotSupported to unbreak build

---

.NET/Microsoft.Recognizers.Definitions.Common/BaseDateTime.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDateTimePeriodParserConfiguration.cs
Patterns/Base-DateTime.yaml
Specs/DateTime/English/DateTimePeriodExtractor.json
Specs/DateTime/English/DateTimePeriodParser.json

ParsePureNumberCases Incorrectly Detects Time Period When Time Period Is Part Of Hyphenated Date
When the regular expression is used to detect a time period it fails to ensure the time period detected was not actually a datetime that begins with either a month or a day.
12-04 for example looks like a time period, but the full text of it is actually 12-04-2019. 
Because of this the recognizer logic determines there is a time period and so then tries to see if it can find the date to which the time period belongs. This does find another date in the scenario outlined in 1981, and results in a completely incorrect recognizer result.
12-04-2019 6:00am until 12-05-2019 8:00pm is detected as
12:00pm until 4:00pm on the 5th of december 2019. It gets 12:00pm until 4:00pm from the 12-04 in the …

[* DateTimeV2] Fixes ranges incorrectly interpreted with dash-formatted dates

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs

This was actually raised in a StackOverflow question - see https://stackoverflow.com/questions/59615953/luis-test-tool-datetime-different-than-locally-resolved-datetime
Basically, the TimexResolver is ignoring if the timex has a "weekend" attached to it, to get the start and end of the period.

Fixing bug with "weekend" flag on Week in year, e.g. "2020-W02-WE"

---

.NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs
.NET/Microsoft.Recognizers.Text/Utilities/ResultsProcessor.cs
JavaScript/package-lock.json
JavaScript/package.json

- Adding class to Text library to process model results and allow indexing by text elements and not only at the character level;
- Bump handlebars version in js due to security alert.

Utils to change result indexing in .NET & bump of vulnerable js dependency

---

JavaScript/lerna.json
JavaScript/package-lock.json
JavaScript/package.json
JavaScript/packages/datatypes-date-time/package-lock.json
JavaScript/packages/datatypes-date-time/package.json
JavaScript/packages/recognizers-choice/package-lock.json
JavaScript/packages/recognizers-choice/package.json
JavaScript/packages/recognizers-date-time/package-lock.json
JavaScript/packages/recognizers-date-time/package.json
JavaScript/packages/recognizers-number-with-unit/package-lock.json
JavaScript/packages/recognizers-number-with-unit/package.json
JavaScript/packages/recognizers-number/package-lock.json
JavaScript/packages/recognizers-number/package.json
JavaScript/packages/recognizers-sequence/package-lock.json
JavaScript/packages/recognizers-sequence/package.json
JavaScript/packages/recognizers-text-suite/package.json
JavaScript/packages/recognizers-text/package.json

This PR solves the failing build for packages 1.3.0 on #1995 
To solve this, we updated lerna latest version and deleted` package.lock.json file` and ejecuted `build.ci.cmd` file it updated the package.lock.json.

[v2] Preparing for NPM packages 1.3.0 

---

.NET/Microsoft.Recognizers.Definitions.Common/Microsoft.Recognizers.Definitions.Common.csproj
.NET/Microsoft.Recognizers.Definitions.Common/YamlParser.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Microsoft.Recognizers.Text.DataDrivenTests.csproj
.NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.csproj

- Making sure unit tests run for both .NET framework targets;
- Updating YamlDotNet dependency;
- Preparing base Text package for .NET Core 3.0 to test build pipelines;
- Downgrading Microsoft.Extensions.Caching.Memory (temporarily).

Dependency changes and making unit tests run in both .NET framework targets

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexRangeResolve.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexRangeResolver.cs

For example T09, constrained to today or torrmow ("let's meet at 9").
Previously, when trying to resolve a TIMEX with just an hour (T09), nothing would be resolved when having specific date constraints.
Now datetimes are returned correctly with the time.
(When having non-specific range constraints, the same TIMEX expression (T09) would be returned, this is unchanged).
Unit tests included.
Fixes #1095

TimexRangeResolver now correctly handles a time with date constraints.

---

.NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.csproj
.NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.nuspec

3.* will wait as some consumers can't update yet. But this update will be needed for .NET Core 3+

Update nuget dependecy

---

Python/libraries/recognizers-number/recognizers_number/number/__init__.py
Python/libraries/recognizers-number/recognizers_number/number/chinese/parsers.py
Python/libraries/recognizers-number/recognizers_number/number/japanese/parsers.py
Python/libraries/recognizers-number/recognizers_number/number/parsers.py
Python/libraries/recognizers-number/recognizers_number/number/utilities.py

This aims to fix the issue [2035 ](https://github.com/microsoft/Recognizers-Text/issues/2035)**[Python | * Number] Number parser reduces the global precision of decimals** 
A utilities.py class was created in recognizers-number (matching that of other recognizers) containing a decorator that can be reused to set decimal precision without affecting the global context.
References to `getcontext().prec = 15` were also removed.

[Python] Add utilities file with decimal precision decorator (fix issue 2035)

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs
JavaScript/packages/datatypes-date-time/src/timexResolver.js
JavaScript/packages/datatypes-date-time/test/timexResolver.spec.js

I fixed invalid end date generation when timex resolution crosses year boundary for javascript platform by revising codes in javascript/packages/datetypes-date-time/src/timexResolver.js and added a test case in /src/test/timexResolver.spec.js.

 Fix invalid end date generation when timex resolution crosses year boundary for javascript platform

---

.NET/Build.CI.cmd
.NET/Microsoft.Recognizers.Definitions.Common/Arabic/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/TestNumber_Arabic.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestBase.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/TestModel.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimeParser.cs
Specs/Number/Arabic/NumberModel.json

- Adding new attribute to momentarily disable Resolution validation in tests (currently only in Numbers*);
- Enabling tests for Number and Percentage in Arabic;
- Build script now works with VS 2019.

Build/validation changes for VS2019 and in-progress new language support

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDatePeriodParserConfiguration.cs
Specs/DateTime/English/DateTimeModel.json

Fixes bug #2053 
- the fix required small changes to basecode
- added relevant test cases to DateTimeModel
(again, we noticed some failing test cases in Number module (it seems due to missing Arabic culture))

[.NET] English DatePeriod bug #2053 fix

---

Specs/Number/Arabic/NumberModel.json
Specs/Number/Arabic/NumberRangeModel.json
Specs/Number/Arabic/OrdinalModel.json
Specs/Number/Arabic/PercentModel.json

IgnoreResolution property is added to all the test cases that has been validated and where extractor is working fine.
- In Arabic we have the following
- Full pass: **18** (all these are negative test cases across all models which doesn't have a resolution)
- Extract pass: **163**
- Disabled: **88** ( Tests which are failing)
- Not-Supported By Arabic Language: **29**

[AR Numbers] IgnoreResolution added to re-enabled test specs

---

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/MergedParser.json
Specs/DateTime/French/MergedParser.json
Specs/DateTime/Hindi/MergedParser.json
Specs/DateTime/Italian/MergedParser.json
Specs/DateTime/Turkish/MergedParser.json

Fix the issue #2078 and more general issue.
Add a new filter to FilterAmbiguity function BaseMergedeDateTimeExtractor.cs.
Add test cases to DateTime/DateTimeModel.json and DateTimeModelComplexCalendar.json.
TODO: 
Refactor to remove this method and use the general ambiguity filter approach.

[.NET] Fix the incorrect extracting of date from number sequence (#2078)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
Patterns/English/English-Numbers.yaml
Specs/Number/English/NumberModel.json
Specs/NumberWithUnit/English/CurrencyModel.json
Specs/NumberWithUnit/English/DimensionModel.json

fix to issue #2112 
Added support for lakh and crore in English Number (and relevant test cases in Number and NumberWithUnit).
There are other larger numbers in the Indian numbering system (arab, kharab, nil,...), but we did not implement them for the following reasons: 
- "these are not commonly used and are unfamiliar to most speakers" (wikipedia)
- they could give ambiguity issues (arab, nil)

[EN Number] Add support for Indian numbering system entities (#2112)

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/OrdinalExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/NumberRecognizer.cs
Patterns/Korean/Korean-Numbers.yaml
Specs/Number/Korean/OrdinalModel.json

**PR Includes:**
- Relative Ordinal Extractor
- Ordinal Spec (51 Cases)
- Existing: 15
- New: 40 (Relative: 20, Ordinal: 16)

[KO Ordinal] Relative Ordinal Extractor and Spec

---

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs
Patterns/Hindi/Hindi-DateTime.yaml
Specs/DateTime/Hindi/TimeExtractor.json
Specs/DateTime/Hindi/TimeParser.json

Support for additional cases in Time (7 in TimeExtractor, 6 in TimeParser).
All new test cases pass.
One old case skipped (due to different sentence structure as pointed out in  #1983)

[.NET] Hindi DateTime Time enhancements 

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelExperimentalMode.json

Fix to issue #1789.
Added relevant test cases in DateTimeModel.
The result of the existing test case "Can I do a booking for the 09th of May for 2 nights?" has been modified to match the one from "Can I do a booking for the 09th of May for 2 days?"

[EN DateTimeV2] Support for ranges with "nights" (#1789)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/English/Extractors/DoubleExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/English/Extractors/IntegerExtractor.cs
Patterns/English/English-Numbers.yaml
Specs/Number/English/NumberModel.json
Specs/NumberWithUnit/English/CurrencyModel.json

Support for Indian numbering system in digits as requested in #2112.
Added test cases to NumberModel and CurrencyModel.
The digit notation "5,00,000" is not as common as the written form "5 lakh", but it is a government approved numbering system in India and is used, for example, in Indian transactions.

[EN Number] Add support for Indian numbering system in digits (#2112)

---

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs
Patterns/Hindi/Hindi-DateTime.yaml
Specs/DateTime/Hindi/DateTimeModel.json
Specs/DateTime/Hindi/DateTimePeriodExtractor.json
Specs/DateTime/Hindi/DateTimePeriodParser.json
Specs/DateTime/Hindi/MergedExtractor.json
Specs/DateTime/Hindi/MergedParser.json

Support for additional cases in DateTimePeriod (16 in Extractor and 18 in Parser).
The following old cases where updated in Merged because of ambiguity
in Extractor:
- "ये कल शाम 4 बजे से पहले है " 
- "ये कल 4pm के बाद है "
both can be translated as "next Tuesday before 12:00 p.m." and "before next Tuesday 12:00 p.m."
in Parser:
- "अगले मंगलवार 12:00 बजे से पहले कभी भी दिल्ली में दवाई की दूकान से जॉर्डन की दवाई ले लेना"
where the extracted text "अगले मंगलवार 12:00 बजे से पहले" can be translated as
"next Tuesday before 12:00 p.m." and "before next Tuesday 12:00 p.m."
Enabled passing cases in DataTimeModel (206 pass, 296 fail).

[.NET] Hindi DateTime DateTimePeriod enhancements

---

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs
Patterns/Hindi/Hindi-DateTime.yaml
Specs/DateTime/Hindi/DateExtractor.json
Specs/DateTime/Hindi/DateParser.json
Specs/DateTime/Hindi/DateTimeModel.json

Support for additional cases in Date (22 in Extractor and 23 in Parser).
Two old cases were updated:
- "मैंने कुछ महीने पहले किसे ईमेल किया था" (who did I email few month ago)
- "मैंने कुछ दिन पहले किसे ईमेल किया था" (who did I email a few day ago)
Reason is the word for "few" in these cases is ambiguous, so a more precise translation has been given (but both versions are still supported).
In DateTimeModel 208 pass, 283 fail.

[.NET] Hindi DateTime Date enhancements

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/NumberRangeExtractor.cs
Patterns/Korean/Korean-Numbers.yaml
Specs/Number/Korean/NumberModel.json
Specs/Number/Korean/NumberRangeModel.json

**Number Extractor (Integer Improvement)**
- Total Cases 244: (Extractor Passed - 226, Full Passed - 101, Skipped - 18)
- New Test Spec: Cases 135 (Extractor Passed - 128, Full Passed - 4, Skipped - 7)
- Integer 56: Extraction Passed-55, Skipped-1
- Fraction 58: Extraction Passed-58
- Decimal 9: Extraction Passed-9
- Power 2: Extraction Passed-2
- Negative 10 : Extraction Passed-4, Skipped-6
**Number Range Extractor**
- Total Test Cases 122: (Extractor Passed - 85, Full Passed - 64, Skipped - 37)
- Existing Cases 53: Extractor Passed - 26, Full Passed - 22, Skipped- 27
- New Cases 69: Extractor Passed - 59, Full Passed - 42, Skipped - 10
**Case input modified **"이 곱하기 십삼은 이십육이다"** to **"내가 가장 좋아하는 숫자는 이십육이다"**
**Reason:** Earlier input had 3 numbers …

[KO Number] Integer and NumberRange Coverage Improvement

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Dutch/Parsers/DutchNumberParserConfiguration.cs
Patterns/Dutch/Dutch-Numbers.yaml
Specs/Number/Dutch/NumberModel.json

Support for 19 previously not supported cases in Number.
The case "honderd en dertig vijfde" (one hundred and thirty fifths) requires additional work in order to be supperted, so it is still skipped for now.

[.NET] Dutch Number enhancements

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/NumberRangeExtractor.cs
Patterns/Korean/Korean-Numbers.yaml
Specs/Number/Korean/NumberModel.json
Specs/Number/Korean/NumberRangeModel.json
Specs/Number/Korean/OrdinalModel.json

- Specs
- NumberModel
- NumberRangeModel
- OrdinalModel
- Number Model Extractor
- Total Cases 243: (Extractor Passed - 229, Full Passed - 101, Skipped - 14)
- New Test Spec: Cases 135 (Extractor Passed - 134, Full Passed - 9, Skipped - 1)
- Integer 56: Extraction Passed-56
- Fraction 58: Extraction Passed-58
- Decimal 9: Extraction Passed-9
- Power 2: Extraction Passed-2
- Negative 10 : Extraction Passed-9, Skipped-1
- Number Range Model Extractor
- Total Test Cases 122: (Extractor Passed - 93, Full Passed - 64, Skipped - 29)
- Existing Cases 53: Extractor Passed - 26, Full Passed - 22, Skipped- 27
- New Cases 69: Extractor Passed - 66, Full Passed - 48, Skipped - 3
- Ordinal Model Extractor
- Total Test Cases 68: (Extractor Passed - 68, Full Passed - …

[KO Number] Coverage Improvement (Number, Ordinal, NumberRange) and Specs Update

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Dutch/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs
Patterns/Dutch/Dutch-DateTime.yaml
Patterns/Dutch/Dutch-Numbers.yaml
Specs/DateTime/Dutch/DateParser.json
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/Dutch/DurationExtractor.json
Specs/DateTime/Dutch/DurationParser.json

Added variations of test cases with abbreviations 'dgn' (dagen) and 'jr' (jaar).
Two cases were updated in DateParser because they used "couple of" instead of "few" which has a different resolution.
In DateTimeModel, 125 pass, 217 fail.

[.NET] Dutch DateTime Duration support

---

JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateTimePeriodConfiguration.ts
Specs/DateTime/Chinese/DateTimeModel.json

Fix issue #1882;
Change to get all match results of timeOfDayRegex in function matchNight of Chinese DateTimePeriodConfiguration in JS;
Add test case to Spec;

[CN DateTimeV2] Fix the issue where time of day merge was not working in JavaScript (#1882)

---

.NET/Microsoft.Recognizers.Definitions.Common/Arabic/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Arabic/Extractors/FractionExtractor.cs
Patterns/Arabic/Arabic-Numbers.yaml
Specs/Number/Arabic/NumberModel.json

- Specs
- NumberModel
- Number Model Extractor
- Total Cases 279: (Extractor Passed - 125, Full Passed - 37, Skipped - 154)
- New Cases 135: (Extractor Passed - 117, Full Passed - 29, Skipped - 18)
- Integer 48: Extraction Passed - 42, Full Passed - 6, Skipped - 6
- Fraction 56: Extraction Passed - 47, Full Passed - 12, Skipped - 9
- Decimal 9: Extraction Passed - 9
- Power 11: Extraction Passed - 8, Full Passed - 0, Skipped - 3
- Negative 11: Extraction Passed - 11, Full Passed - 11
**Some of the cases from earlier iteration that we added are modified. We identified some discrepancy in those cases and got re-corrected by Language Expert. Below are inputs that are modified.
- تسعين وخمس مائة أخماس من الوزن
- كان النتيجة مئة أجزاء من الف وخمسة
- واحد من …

[AR Number] Coverage Improvements and Spec Updates

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Models/AbstractNumberWithUnitModel.cs
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/extractors/NumberWithUnitExtractor.java
JavaScript/packages/recognizers-number-with-unit/src/numberWithUnit/extractors.ts
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/extractors.py
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/models.py
Specs/NumberWithUnit/Chinese/CurrencyModel.json

Fix the issue #568
Add codes for detecting conflicts to extract function of NumberWithUnitExtractor for all platforms
Add codes for solving conflicts when merging results to AbstractNumberWithUnitModel for .NET and Python
To improve the performance, add a length check for PrefixMatch and SuffixMatch in the if statement so that it will only check the cases that have prefix and suffix at the same time.  
Add test case to Specs

[CN Currency] Fix incorrect number extraction cases (#568)

---

.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDateParserConfiguration.cs
Patterns/Hindi/Hindi-DateTime.yaml
Patterns/Hindi/Hindi-Numbers.yaml
Specs/DateTime/Hindi/DatePeriodExtractor.json
Specs/DateTime/Hindi/DatePeriodParser.json
Specs/DateTime/Hindi/DateTimeModel.json
Specs/DateTime/Turkish/DateTimeModel.json

Support for additional cases in DatePeriod (59 in Extractor and 78 in Parser).
5 cases in Parser are failing due to the 'yesterday/tomorrow' ambiguity.
BaseDatePeriodExtractor has been modified to support "between... and..." cases when 'between' follows the datepoint.
This required to update 1 case in Turkish DateTimeModel to include 'between' in the text extraction.
In DateTimeModel: 236 pass, 255 fail.

[.NET] Hindi DateTime DatePeriod enhancements

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/ITimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimePeriodFunctions.cs
Patterns/Dutch/Dutch-DateTime.yaml
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/Dutch/DateTimeParser.json
Specs/DateTime/Dutch/DateTimePeriodExtractor.json
Specs/DateTime/Dutch/DateTimePeriodParser.json
Specs/DateTime/Dutch/TimePeriodParser.json

In Extractor all cases pass.
In Parser 6 cases are not supported.
Not supported cases are of the form: "laten we vroeg op de dinsdagochtend afspreken" (let's meet in the early-morning Tuesday) where 'early' (vroeg) and 'morning' (ochtend) are not contiguous. Alternative expressions have been added to the spec.
Following cases have been modified because they do not represent DateTimePeriod entities, are not grammatically correct or do not match the corresponding English Resolution. Original cases have been kept in the spec with updated resolution or moved to the Model.
Modified and moved to Model:
- ik ben vandaag weg tussen vijf en zeven
- ik ben op 1 januari weg van 5 tot 6
- Morgen ben ik weg tussen 3 en 4 uur ’s middags
- Morgen ben ik weg van half acht tot 4 uur ‘s middags
- Vandaag …

[.NET] Dutch DateTime DateTimePeriod

---

.NET/Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs

Even though this code is still uncommented, would be good to have this adapting the new way. Makes it easier to work on Dutch DateTime. :-)

[NL DateTimeV2] Change Dutch init in .NET to utilise BaseTimeOptions

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateExtractor.json
Specs/DateTime/German/DateParser.json
Specs/DateTime/German/DatePeriodExtractor.json
Specs/DateTime/German/DatePeriodParser.json
Specs/DateTime/German/DateTimeModel.json
Specs/DateTime/German/DateTimePeriodExtractor.json
Specs/DateTime/German/DateTimePeriodParser.json

Add support for german "übernächste" (particularly applicable to weeks like in "the week after next"), implementing #1854.

[DE DateTimeV2] DateTime support for "übernächste Woche"

---

.NET/Microsoft.Recognizers.Definitions.Common/Italian/NumbersDefinitions.cs
Patterns/Italian/Italian-Numbers.yaml
Specs/Number/Italian/NumberModel.json

Fixes instances of elided numbers being wrongly extracted (#2226).
For example 'settant' should be extracted only when occurring in compound numbers e.g. 'settantotto' (seventy-eight) or in elided form e.g. 'settant'anni' (seventy years).
Relevant test cases added to NumberModel.

[IT Number] fix String "tr" recognized as number zero (#2226)

---

.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishHolidayParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseHolidayParser.cs
Specs/DateTime/English/DateTimeModel.json

fix for issues pointed out in #2246. 
When the reference date is smaller than the holiday date for the reference year, 'next [holiday]' now returns the date for the reference year (instead of the date for the following year). Similarly for 'last [holiday].
Removed hard coded values from configuration file so that also other relative expressions such as 'previous(following) [holiday]' works correctly.

[EN DateTimeV2] Fix for relative Holidays to take reference date into account (#2246)

---

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Spanish.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishMergedParserConfiguration.cs
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/Spanish/DateTimeModel.json
Specs/DateTime/Spanish/DateTimeModelExperimentalMode.json

Added support for ranges like "de 2015" in Spanish (under Experimental mode) in analogy to the English case "from 2015" (#2210). 
Test case added to the new spec file DateTimeModelExperimentalMode.json

[ES DateTimeV2] Added support for "de 2015" as a date range under Experimental mode (#2210)

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs
Specs/DateTime/English/DateTimeModel.json

Fixed resolution for the first and second patterns pointed out in #2011. 
The resolution of the third pattern "end of this year" does not seem wrong (but as pointed out in #2232, there is a discrepancy in the start value respect to "end of 2016").
Also fixed analogous issue for patterns like "after the beginning of March".

[EN DateTimeV2] Fix for "end of" related bugs (#2011)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

Added support for expressions like "before the thirty-first day of the month" (#1836).
Relevant test cases added to DateTimeModel and modified existing case "Must deliver sixteen (16) units before the thirty-first day of the month." to fit the new resolution.
Should expressions like "I'll go back the twenty second day of June" also be supported?

[EN DateTimeV2] Properly resolve "before the thirty-first day of the month" as a single entity (#1836)

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/French/DateTimeModel.json

Fixed missing resolution for DateTimeRanges where Date precedes Time (e.g. "It will happen on the 17 between 2 and 4pm").
The issue has been reported in French, but other languages are affected too (observed also in English and Italian).
Relevant test cases added to EN and FR DateTimeModels.

[FR DateTimeV2] Fixed No resolution in DateTimeRange (#456)

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimeExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/ITimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishTimeExtractorConfiguration.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json

Fix to avoid extracting expressions like "3 heures" as time when preceded by "pour" or "durée de". The problem is "3 heures" is ambiguous in general and can also represent a time e.g. "il est 3 heures" (it is 3 o'clock).
Fix implemented only in .NET, test cases added to DateTimeModel.

[FR DateTimeV2] Fix to get hours duration (#450)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/English/Extractors/NumberExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberExtractor.cs
Patterns/English/English-Numbers.yaml
Specs/Number/English/NumberModel.json
Specs/Number/English/NumberRangeModel.json

Fix to issue #840 
Added relevant test cases to NumberModel.
2 test cases needed to be updated in NumberRangeModel:
- "The number is equals to 20000 in 1998"
- "The number is from 200 to 3000000 in 2008"

[EN Number] Fix wrong fraction extraction (#840)

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json

Fix for hours durations wrongly recognized as time when introduced by "pendant" (during) e.g. "pendant 2 heures" (#445).

[FR DateTimeV2] Fix for hours duration wrongly recognized (#445)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

removed "weekend" from UnspecificDatePeriodRegex used by FilterUnspecificDatePeriod in BaseMergedDateTimeExtractor in order to keep the extraction "weekend" when preposition is missing e.g. “dinner with mom weekend” (#2263).

[EN DateTimeV2] Fix for missing detection for "weekend" unless preposition is present (#2263)

---

.NET/Microsoft.Recognizers.Definitions.Common/German/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/German/Parsers/GermanNumberParserConfiguration.cs
Patterns/German/German-Numbers.yaml
Specs/DateTime/German/DateTimeModel.json
Specs/Number/German/NumberModel.json

Added support for compound fraction expressions like "anderthalb", "einundhalb", "zweieinhalb" (#2271).
The fix follows the solution implemented in Dutch for similar patterns. 
Test cases added to NumberModel and DateTimeModel.

[DE DateTimeV2] Added support for expressions like "anderthalb", "einundhalb", "zweieinhalb" (#2271)

---

.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateTimePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
Specs/DateTime/English/DateTimeModel.json

Fix for DateTimePeriods containing pure numbers (e.g. "between 7 and 9 last night") not being extracted (#2262).

[EN DateTimeV2] Fix for specific datetimeperiod phrase not extracted (#2262)

---

.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs
Specs/NumberWithUnit/English/DimensionModel.json

fix to first issue pointed out in #2037 ("12 ft 2 in" returning "12 ft 2", instead of the two separate entities)
added relevant test cases to DimensionModel

[* Unit] Fix unit extraction in utterances with compound entity (#2037)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

Added support for ranges like "from 2007 to the end of 2008" (#654).
Isolated occurrences of "the end of " + specific "year/month/week" seem to be already supported.
However, there is maybe an inconsistency in the parsed result when the extraction is recognized as daterange or duration.
For example:
"end of 2016"      -> "start": 2016-09-01
"end of this year" -> "start": 2016-07-01

[EN DatetimeV2] Added support for "the end of " in date period (#654)

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json

Added support for space separated dates in French e.g. '02 04 2009', '18 8 78' (#547).
These patterns are already implemented in German.

[FR DateTimeV2] Fix for handling space as date separator (#547)

---

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersDefinitions.cs
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/ChineseNumeric.java
JavaScript/packages/recognizers-number/src/resources/chineseNumeric.ts
Patterns/Chinese/Chinese-Numbers.yaml
Python/libraries/recognizers-number/recognizers_number/resources/chinese_numeric.py
Specs/Number/Chinese/NumberRangeModel.json

1. improve support recognize count unit behind “[多几]” as number range in Chinese like "十多万", "二十几亿". Refer to #2268 
> This part is only supported in c sharp.
Due to `OneNumberRangeMoreRegex3` limit matching the end `[万亿]` pattern, the previous model can't recognizer the count unit behind “[多几]”.
So we reopen the limitation in this pattern.

[ZH NumberRange] Improve support for “*[多几][千万]” in Chinese (#2268)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishMergedParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishMergedParserConfiguration.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/DateTimeModelExperimentalMode.json
Specs/DateTime/English/MergedExtractor.json
Specs/DateTime/English/MergedParser.json

Moved support for ranges like "from 2015" from Standard to Experimental mode in analogy with Spanish behaviour (#2287).
Added pattern "from 2015 and 2016"  to PotentialAmbiguousRangeRegex (FromToRegex) to avoid considering 'from' a modifier in this case.
Updated affected test cases in DateTimeModel and moved the originals to DateTimeModelExperimentalMode.

[EN DateTimeV2] Fixed inconsistency between English and Spanish in handling "from" and issue with list (#2287)

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateTimeModel.json

Expression "am Morgen" previously extracted as Date is now correctly recognized as TimePeriod (#2298).

[DE DateTimeV2] Fixed support for expression "am Morgen" (#2298)

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateTimeModel.json

Added support for expressions like "Vormittagszeit, Mittagszeit, Spätabends, Spätnachmittags, nach Mitternacht, vor Mitternacht, Mitternacht" (#2294).

[DE DateTimeV2] Added support for several time expressions (#2294)

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateExtractor.json
Specs/DateTime/German/DateTimeModel.json

Fixed issue #2291. The problem was due to a duration pattern wrongly included in the German DateRegexList and it is not observed on other languages.

[DE DateTimeV2] Fixed extraction of time expressions like "in 3 Wochen" (#2291)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/CurrencyExtractorConfiguration.cs
Patterns/English/English-NumbersWithUnit.yaml
Specs/NumberWithUnit/English/CurrencyModel.json

Added 'usd' to CurrencyPrefixList in order to solve issue #1850. 
Should other currencies be added to the list?
Test case added to CurrencyModel.

[* Currency] Fix for currency 'USD' not recognized when used before value (#1850)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Number/LongFormTestConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/English/Parsers/EnglishNumberParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/INumberParserConfiguration.cs
Patterns/English/English-Numbers.yaml
Specs/Number/English/NumberModel.json
Specs/NumberWithUnit/English/CurrencyModel.json

added support for fractional round numbers (in EN .NET) e.g. 'half million', 'quarter million', 'two thirds billion'... (#1934).
Test cases added to NumberModel and CurrencyModel.

[EN Number/Currency] Support for "half million" (#1934)

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java
JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_merged.py
Specs/DateTime/English/DateTimeModel.json

Ported fixes from PR #2247 to Java, JavaScript and Python (#2309).
Enabled test cases in DateTimeModel.

[EN DateTime V2] Fixed resolution for "by the end of" in Java, JavaScript, and Python (#2309)

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/German/DateTimeModel.json

Fix to issue #2334. 
The behaviour of the extractor has been conformed to the English one. 
But, should we modify it to extract "jeden Tag um 19:13 Uhr" as a single entity? This happens already when the time entity is at the end of the utterance (e.g. "Ich gehe jeden Tag um 3 Uhr Nachmittags").

[DE DateTimeV2] Fixed set and time being incorrectly mixed during recognition (#2334)

---

.NET/Microsoft.Recognizers.Definitions.Common/BaseNumbers.cs
.NET/Microsoft.Recognizers.Definitions.Common/Dutch/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/French/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/German/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Italian/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Swedish/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Turkish/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs
Patterns/Base-Numbers.yaml
Patterns/Dutch/Dutch-Numbers.yaml
Patterns/English/English-Numbers.yaml
Patterns/French/French-Numbers.yaml
Patterns/German/German-Numbers.yaml
Patterns/Hindi/Hindi-Numbers.yaml
Patterns/Italian/Italian-Numbers.yaml
Patterns/Portuguese/Portuguese-Numbers.yaml
Patterns/Spanish/Spanish-Numbers.yaml
Patterns/Swedish/Swedish-Numbers.yaml
Patterns/Turkish/Turkish-Numbers.yaml
Specs/Number/Dutch/NumberModel.json
Specs/Number/English/NumberModel.json
Specs/Number/French/NumberModel.json
Specs/Number/German/NumberModel.json
Specs/Number/Italian/NumberModel.json
Specs/Number/Portuguese/NumberModel.json
Specs/Number/Spanish/NumberModel.json

Added support for single character fractions (¼½¾⅐⅑⅒⅓⅔⅕⅖⅗⅘⅙⅚⅛⅜⅝⅞) in English (#2347).

[EN Number] Added support for vulgar fractions (#2347)

---

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_merged.py
Specs/DateTime/English/DateTimeModel.json

Ported .NET solution for issue #2243 to Python.
The test case "I am feeling sick around 1pm" is still unsupported in Python because there is an inconsistency between the two platforms:
- In .NET, the entity type is always modified to its corresponding range-type independently of the modifier (so for "around 1pm", the type "time" changes to "timerange")
- In Python, only 'before', 'after' and 'since' modifiers modify the type (so for "around 1pm", the returned type remains "time")

[EN Python DateTimeV2] Added support for text like "from around 1pm" (#2243)

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDateTimePeriodParserConfiguration.cs
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_datetimeperiod.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_timeperiod.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/english/datetimeperiod_parser_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/english/timeperiod_parser_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/french/datetimeperiod_parser_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/french/timeperiod_parser_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/spanish/datetimeperiod_parser_config.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/spanish/timeperiod_parser_config.py
Specs/DateTime/English/DateTimeModel.json

- Fixed datetimerange start range ignoring 'pm' in expressions like  "Tuesday at 2:00 - 2:30 pm" (#2330) in Python and .NET.
- Ported method ParseSpecificTimeCases to Python to avoid discrepancies in TimePeriodParser results between the two platforms.

[Python/.NET | EN DateTimeV2] Fixed datetimerange start range ignoring pm (#2330)

---

.NET/Microsoft.Recognizers.Text.Number/Swedish/Extractors/CardinalExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Swedish/Extractors/IntegerExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Swedish/Extractors/NumberExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Swedish/Extractors/OrdinalExtractor.cs

Existing number extractors have been upgraded to use the CachedNumberExtractor where applicable. They should now be aligned w/ the English extractor implementations.

[SV Number] Performance upgrade (cache implementation)

---

.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Parsers/FrenchDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Parsers/HindiDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Parsers/ItalianDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/IDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Parsers/TurkishDateParserConfiguration.cs
Specs/DateTime/English/DateTimeModel.json

Added support for pattern [Duration] + "before/after" + [Holiday], e.g. "1 week before Christmas", "two months after Easter"... (#2295).

[EN DateTimeV2] Added support for duration-relative calculations for Holidays (#2295)

---

JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/english/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/french/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/spanish/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_dateperiod.py
Specs/DateTime/English/DateTimeModel.json

Added support for years spelled out as words (e.g. "two thousand twenty") in DatePeriod in Javascript and Python (#2332).

[JavaScript/Python | EN DateTime V2] Fixed missing resolution for years spelled out as words (#2332)

---

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/extractors/BaseDatePeriodExtractor.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDatePeriodParser.java
Patterns/Spanish/Spanish-DateTime.yaml
Patterns/Turkish/Turkish-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_dateperiod.py
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2372.
Modified DatePeriod to avoid matching FutureRegex in the afterStr of Duration extractions since FutureSuffixRegex already does that (and some expressions in FutureRegex only work as prefixes).
Also, added checker in the parser to avoid modifying the resolution when InConnector is ambiguous and can indicate both a precise point or a range (e.g. in Spanish and Turkish).
Some test cases have been updated to comply with their English counterparts (keeping also the originals):
- "El primero de 2000 fue un día especial para mí." (January first 2000 was a special day for me) -> "El primero de enero de 2000 fue un día especial para mí." ("primero de 2000" does not represent a date in Spanish)
- Cases with "esta tarde" (this afternoon) -> "este pasado mediodia"

[ES DateTimeV2] Fixed Spanish DateRange extraction issues (#2372)

---

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDurationParserConfiguration.cs
JavaScript/packages/recognizers-date-time/src/resources/chineseDateTime.ts
Patterns/Chinese/Chinese-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/chinese_date_time.py
Specs/DateTime/Chinese/DateTimeModel.json
Specs/DateTime/Chinese/DurationExtractor.json
Specs/DateTime/Chinese/DurationParser.json

Fixed recognizing of combined duration like "8天20小时" in Chinese .NET (#2384).
Added test cases.

[ZH DateTimeV2] Supported recognition of combined durations like "8天20小时"(#2384 )

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanDatePeriodParserConfiguration.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateExtractor.json
Specs/DateTime/German/DateTimeModel.json

Fix to issue #2374.
One test case moved from DateExtractor to DateTimeModel because it does not seem to represent a date: "Ich komme nächstes Jahr wieder." (I'll come again next year)

[DE DateTimeV2] Fixed terms about years (last year, this year) not recognized correctly (#2374)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishSetParserConfiguration.cs
Patterns/English/English-DateTime.yaml
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2400.
The pattern "primera semana" is not currently supported, also in English "first week" is not recognized (but instead "week 1"/"semana 1" is extracted). Should I add support for the pattern?

[ES DateTimeV2] Fix date periods/ranges inconsistently recognized (#2400)

---

JavaScript/packages/recognizers-date-time/src/dateTime/chinese/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/constants.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/dateperiod_parser.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/constants.py
Specs/DateTime/Chinese/DatePeriodExtractor.json
Specs/DateTime/Chinese/DatePeriodParser.json
Specs/DateTime/Chinese/DateTimeModel.json

Fixed recognizing "年代" like "九十年代” in python and JavaScript (#742).
Added test cases.

[ZH DateTimeV2] Fixed recognizing "年代" year-range/decade in Python/JavaScript (#742)

---

.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/FullDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/DateContext.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/utilities.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/date_parser.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/merged_parser.py
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/utilities.py
Specs/DateTime/Chinese/DateParser.json
Specs/DateTime/Chinese/DateTimeModel.json

1. Modify the output of Feb 29th according to the reference date. 
2. Filter invalid futureresolution or pastresolution.
3. If they are both invalid, output "not resolved".
4. Added test cases.

[ZH DateTime V2] Fixed the output of invalid day like "2/29/2019" and "2/30"

---

.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/FullDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/DateContext.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs
Specs/DateTime/Dutch/DatePeriodParser.json
Specs/DateTime/English/DateParser.json
Specs/DateTime/English/DatePeriodParser.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/French/DateTimeModel.json
Specs/DateTime/German/DateTimeModel.json
Specs/DateTime/Hindi/DatePeriodParser.json
Specs/DateTime/Hindi/DateTimeModel.json
Specs/DateTime/Italian/DateTimeModel.json
Specs/DateTime/Japanese/DateTimeModel.json
Specs/DateTime/Portuguese/DateTimeModel.json
Specs/DateTime/Spanish/DatePeriodParser.json
Specs/DateTime/Spanish/DateTimeModel.json
Specs/DateTime/Turkish/DatePeriodParser.json
Specs/DateTime/Turkish/DateTimeModel.json

In EN/FR/DE/HI/IT/JA/PT/ES/TR:
Modify the output of Feb 29th according to the reference date.
Support to recognize date period contains invalid date like 2/29 - 3/1.    
Generate future/past timexes separately if the case has no specific year. 
Added test cases.

[.NET DateTime V2] Fixed the output of invalid day like "2/29/2019" and "2/30" in all languages

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/french/extractors/FrenchDateExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/french/extractors/FrenchMergedExtractorConfiguration.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/resources/FrenchDateTime.java
Patterns/French/French-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/resources/french_date_time.py
Specs/DateTime/French/DateTimeModel.json

1. Filter ambiguity.
2. Correct "NotSupported" tags in French DateTimeModel since the full stop is included in the extracted text (even if the extractor returns the correct match).

[Java | FR DateTimeV2] Correct regex definition and add ambiguity filter

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexProperty.cs

Fix the culture problem of parsing Timex Durations with Decimal values. #1528
All timexes should use only '.' as canonical separator and parsing should work in any culture.
Add unit test to make sure it works in different culture settings.

[TimexExpression] Fix parsing Timex in different cultures in TimexResolover (#1528)

---

Java/README.md

Related to #2253 
The Java's README doesn't contain the content to install the Recognizers.
- Add `Installation` sub-bullet in the README
- Define how to install core Recognizer's features
- Define how to install numbers Recognizer's features
- Define how to install numbers with units Recognizer's features
- Define how to install datetime Recognizer's features
- Define how to install choice Recognizer's features
We validated the changes rendering the document manually and comparing it with the C# [README](https://github.com/microsoft/Recognizers-Text/blob/master/.NET/README.md).
_Before vs After_
_List of the current Recognizers_

[Java] Add Recognizers dependencies in README

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/Constants.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConstantsEnglish.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConvertEnglish.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/Microsoft.Recognizers.Text.DataTypes.TimexExpression.xml
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexDateHelpers.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexFormat.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexHelpers.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexProperty.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexRegex.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexValue.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs

Support merged timex of duration/datetimerange like "PT1H30M", "(2020-06-04T15,2020-06-04T17:30,PT2H30M)".(#1515, #1923, #2110)
Fix time addition of start/end in duration/timerange. (#1530)
Add constants of TimexExpression.
Support Invariant Culture in parsing.
Add unit test.

[TimexExpression] Support merged timex of duration/datetimerange like "PT1H30M" (#1515, #1530, #1923, #2110)

---

Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/models/AbstractNumberModel.java
Java/tests/src/test/java/com/microsoft/recognizers/text/tests/number/NumberTest.java

Fixes #2254
There is a disparity on the generation of the `ModelResult`, specifically the `end` property, which needs to be decreased by 1. See [C#](https://github.com/microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs#L79) and [Java](https://github.com/microsoft/Recognizers-Text/blob/master/Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/models/AbstractNumberModel.java#L57). Also, [JavaScript](https://github.com/microsoft/Recognizers-Text/blob/e56e3a7fc82aeeb3979ce2c3c61d20a25f4261d3/JavaScript/packages/recognizers-number/src/number/models.ts#L94) follows the behavior of C#.
- Decrease the `end` property of `ModelResult` by 1
These changes were validated using the PR #2439.
_Parity of …

[Java][Number] Decrease end property of ModelResult by 1

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/Constants.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConstantsEnglish.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConvertEnglish.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexRelativeConvertEnglish.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexFormat.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexHelpers.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexInference.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexProperty.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexRegex.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexResolver.cs

Fix timex without specified year/month like "XXXX-XX-06", "XXXX-02-02".
Return future/past resolutions according to reference date.
Add test cases.
Support week related timex like "XXXX-WXX-1", "XXXX-11-WXX-4-4"(#2456).
Support datetimerange with fuzzy timex like "XXXX-10-25TAF"(#2318), "(XXXX-04-05T10,XXXX-04-05T11,PT1H)"(#1513), "XXXX-WXX-1TMO"(#1560)

[TimexExpression] Fix timex without specified year/month like "XXXX-XX-06"

---

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DataDrivenTests/DateTime/TestDateTime_Japanese.cs
Patterns/Japanese/Japanese-DateTime.yaml
Specs/DateTime/Japanese/DateTimeModel.json
Specs/DateTime/Japanese/HolidayExtractor.json

All test cases pass. 
The extraction of the case "明日清明だけどどこ行く？" has been modified because it was wrongly pointing to "明日" (tomorrow) instead of the holiday "清明" (Qingming).

[JA DateTimeV2] Holiday extractor refinements

---

.NET/Microsoft.Recognizers.Definitions.Common/German/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/GermanNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Parsers/GermanNumberWithUnitParserConfiguration.cs
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/german/extractors/GermanNumberWithUnitExtractorConfiguration.java
Java/libraries/recognizers-text-number-with-unit/src/main/java/com/microsoft/recognizers/text/numberwithunit/german/parsers/GermanNumberWithUnitParserConfiguration.java
Patterns/German/German-NumbersWithUnit.yaml
Specs/NumberWithUnit/German/CurrencyModel.json
Specs/NumberWithUnit/German/DimensionModel.json

Fix to issue #2494 in .NET. 
Solution applied also in Java, but an additional problem appears there with non-spaced connectors (i.e. "12 - Pfund" is recognized correctly but "12-Pfund" is not).
Test cases added to German DimensionModel and CurrencyModel.

[DE Unit/Currency] Support for hyphen-connected unit expressions (#2494)

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchSetExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseSetExtractor.cs
Patterns/Dutch/Dutch-DateTime.yaml
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/Dutch/SetExtractor.json
Specs/DateTime/Dutch/SetParser.json

In SetExtractor, all test cases pass.
In SetParser, 2 cases fail: 
"Laten we vrijdag om de week afspreken" and "Laten we vrijdag om de andere week afspreken" which correspond to "Every other Friday" in English. The different structure of the Dutch expression (literally "Friday every other week") prevents these cases to be parsed in the current implementation.
A few cases have been modified in SetExtractor and the original spec moved to DateTimeModel:
- "Ik zal vertrekken om 09:00 's ochtends" -> "Ik ga weg iedere ochtend om 9 uur" (I leave every morning at 9am)
- "Ik zal vertrekken 's ochtends om 9" -> "Ik ga weg om 9 uur iedere ochtend" (I leave at 9am every morning)
In the above two cases, the original sentences do not represent Set entities but Time.
- "Ik zal elke maandag vertrekken …

[.NET] Dutch DateTime Set support

---

.NET/Microsoft.Recognizers.Definitions.Common/Arabic/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Hindi/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Turkish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs
Patterns/Arabic/Arabic-DateTime.yaml
Patterns/Dutch/Dutch-DateTime.yaml
Patterns/English/English-DateTime.yaml
Patterns/French/French-DateTime.yaml
Patterns/German/German-DateTime.yaml
Patterns/Hindi/Hindi-DateTime.yaml
Patterns/Italian/Italian-DateTime.yaml
Patterns/Portuguese/Portuguese-DateTime.yaml
Patterns/Spanish/Spanish-DateTime.yaml
Patterns/Turkish/Turkish-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

Fixed extraction of dates with two-digit years in the range [30,40) (e.g. 12/12/35) (#2493).
As suggested, these ambiguous patterns are resolved to both values 1935-12-12 and 2035-12-12.
Test cases added to EN DateTimeModel.

[* DateTimeV2] Resolving 2-digit year mentions (#2493)

---

Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimexUtility.java

Fixes #2548
Fixes arbitrary differences in order found when retrieving elements from the output of [BaseMergedDateTimeParser::dateTimeResolution](https://github.com/microsoft/Recognizers-Text/blob/master/Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java#L435), which created a disparity against the same output in C# and JavaScript.
We changed the type of the [res](https://github.com/microsoft/Recognizers-Text/blob/master/Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseMergedDateTimeParser.java#L441) variable to [LinkedHashMap](http://docs.oracle.com/javase/6/docs/api/java/util/LinkedHashMap.html), since with the original type …

[Java][DateTime] Fix arbitrary order in parsed elements

---

.NET/Microsoft.Recognizers.Definitions.Common/Arabic/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Arabic/Parsers/ArabicTimeParserConfiguration.cs
Patterns/Arabic/Arabic-DateTime.yaml
Specs/DateTime/Arabic/TimeExtractor.json
Specs/DateTime/Arabic/TimeParser.json

TimeExtractor: 74 pass, 0 fail.
TimeParser: 39 pass, 35 only resolution, 0 fail.
Some of the duplicate test cases that were previously removed have been reintroduced with variations.
Test cases modified in TimeExtractor:
- "الساعة الثامنة و 30 دقيقة" ( missing "it's" "إنها ") -> "إنها الساعة الثامنة و 30 دقيقة" (It's 30 mins past eight)
- "الساعة السابعة والنصف بعد الظهر" (missing "it's" "إنها ") -> "إنها الساعة السابعة والنصف بعد الظهر" (It's half past seven afternoon)
- "سأعود في الحاديه عشر" (Correct the Arabic writing of number 11 "الحادية عشرة") -> "سأعود في الحادية عشرة" (I'll be back 11ish)
- "سأعود الحاديه عشر" (Correct the Arabic writing of number 11 "الحادية عشرة") -> "سأعود الحادية عشرة" (I'll be back 11-ish)
- "منتصف.الليل" (uncommon to use "." between two words in Arabic …

[.NET] Arabic Time support

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/GermanHolidayParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/HolidayParserGer.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateTimeModel.json

Fix to issue #2573.
Added support (and test cases) for the holidays in the list https://www.schulferien.org/deutschland/feiertage/ not already covered by the German Recognizer.

[DE DateTimeV2] Improvements to Holiday coverage in German (#2573)

---

.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2597.
Test cases added to Spanish DateTimeModel.

[ES DateTimeV2] Fixed 'mi próximo' incorrecly resolves to a date (#2597)

---

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
Patterns/Portuguese/Portuguese-DateTime.yaml
Specs/DateTime/Portuguese/DateTimeModel.json

Fix to issue #2601.
Test case added to Portuguese DateTimeModel.

[PT DateTimeV2] Fixed 'dia' followed by digits is resolved incorrectly (#2601)

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDateExtractor.cs
Patterns/French/French-DateTime.yaml
Patterns/Portuguese/Portuguese-DateTime.yaml
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json
Specs/DateTime/Portuguese/DateTimeModel.json
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2605.
Modified handling of WeekDayAndDayOfMonthRegex in NumberWithMonth to allow extraction of patterns where the day number precedes the weekday like in the french case "le 25 Mardi".
Test cases added to French and Portuguese DateTimeModel.

[PT, FR DateTimeV2] Fixed incorrectly splitting weekday from date (#2605)

---

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Japanese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Korean/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/BaseCJKDurationExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/ICJKDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/JapaneseDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Korean/Extractors/KoreanDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Korean/Parsers/KoreanCommonDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDurationParser.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/IntegerExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Korean/Extractors/KoreanNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/NumberWithUnitParser.cs
Patterns/Chinese/Chinese-DateTime.yaml
Patterns/Japanese/Japanese-DateTime.yaml
Patterns/Korean/Korean-DateTime.yaml
Patterns/Korean/Korean-Numbers.yaml
Patterns/Korean/Korean-NumbersWithUnit.yaml
Specs/DateTime/Korean/DurationExtractor.json
Specs/DateTime/Korean/DurationParser.json

Extractor: 34 pass, 0 fail.
Parser: 22 pass, 13 only extraction, 0 fail.
Ported method ImplicitDuration from BaseDateExtractor to support cases like "all day", "half day", "next day"... not covered in CJK implementation.

[.NET] Korean Duration support

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Korean/Extractors/KoreanDateExtractorConfiguration.cs
Patterns/Korean/Korean-DateTime.yaml
Specs/DateTime/Korean/DateExtractor.json
Specs/DateTime/Korean/DateParser.json

Extractor: 194 pass, 2 fail.
Parser: 87 pass, 102 only extraction, 2 fail.
Failing cases (both in Extractor and Parser):
- "너는 지금부터 한 달에 두 번씩 일요일마다 시간 괜찮니? " (Are you available two sundays from now?), it literally translates to "Are you available twice per month on Monday from now?".
- "너는 후에 두 번의 월요일에 시간 괜찮니?" (Are you available two monday later?), it literally translates to "Are you available on this coming two Monday after this?".
The problem is there is no correspondence for these expressions ("two sundays from now", "two monday later") in Korean and the two inputs as they are do not make sense.
A few inputs were updated because not grammatically correct or because containing date patterns not used in Korean:
In DateExtractor: 
Date separator not used in Korean:
- "4.22에 돌아갈게요" -> …

[.NET] Korean Date support

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs
Specs/DateTime/Dutch/MergedParser.json
Specs/DateTime/English/DateTimeModel.json

Fix to issue #2617.
Updated affected test cases in Dutch and English.

[* DateTimeV2] Fixed duration patterns wrongly normalized/resolved when number is missing (#2617)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

Fix to issue #2625.
"Nighttime" is now resolved to the range "00:00-08:00". 
Should it instead be resolved as "night" ("20:00-00:00")? Or, by symmetry with "daytime" ("08:00-18:00"), as "20:00-06:00"? (However, this last option would require to move the pattern from TimePeriod to DateTimePeriod)

[EN DateTimeV2] Fixed "in the daytime" extracted but not resolved (#2625)

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/DateTimeRecognizer.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimeParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
Patterns/Dutch/Dutch-DateTime.yaml
Specs/DateTime/Dutch/DateParser.json
Specs/DateTime/Dutch/DateTimeExtractor.json
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/Dutch/DateTimeParser.json
Specs/DateTime/Dutch/DurationExtractor.json
Specs/DateTime/Dutch/DurationParser.json
Specs/DateTime/Dutch/TimeExtractor.json
Specs/DateTime/Dutch/TimeParser.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/Hindi/DateTimeModel.json

352 pass, 29 fail.
Most of the ambiguous test cases with 'voor' have been updated to be resolved as 'before' instead of 'for'. 
Exceptions are: 
- Duration patterns with 'all' (e.g. 'all year') where the 'for' interpretation seems more appropriate (e.g. 'for the whole year' vs 'before the whole year'). In this case 'voor' has been included in the Duration extractions.
- 2 points ranges (still failing) where the 'before' interpretation does not make sense e.g. 'before between 2015 and 2018' ('voor tussen 2015 en 2018').
The resolution of test cases whose meaning does not match the English counterparts has been updated and new test cases have been added to better match the English inputs. 
For example:
- "Ik ben aanstaande september weg" -> "Ik ben deze september weg" (I'll be out this …

[.NET] Dutch DateTimeModel initial support

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDatePeriodParser.java
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/utilities/TimexUtility.java
Specs/DateTime/Chinese/DateTimeModel.json
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/DateTimeModelExperimentalMode.json
Specs/DateTime/Hindi/DateTimeModel.json
Specs/DateTime/Japanese/DatePeriodParser.json
Specs/DateTime/Spanish/DateTimeModel.json
Specs/DateTime/Turkish/DatePeriodParser.json
Specs/DateTime/Turkish/DateTimeModel.json

Fix to issue #2586.
Updated affected test cases in Chinese, English, Hindi, Japanese, Spanish and Turkish specs.

[* DateTimeV2] Fixed reference year incorrectly assigned to Timex in DatePeriod patterns (#2586)

---

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimePeriodFunctions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/TimexUtility.cs
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/timePeriodConfiguration.ts
Patterns/Japanese/Japanese-DateTime.yaml
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/chinese/timeperiod_parser.py
Specs/DateTime/Chinese/DateTimeModel.json
Specs/DateTime/Chinese/TimePeriodParser.json
Specs/DateTime/Japanese/TimePeriodExtractor.json
Specs/DateTime/Japanese/TimePeriodParser.json

Extractor: 56 pass, 0 fail.
Parser: 64 pass, 0 fail.
No input has been modified.
Modified BaseCJKTimePeriodParser to add "start"/"end" mods for cases like "early/late morning" as in standard implementation.
Modified method Handle in TimePeriodFunctions to support patterns like "from 11 to 3 morning" (with desc only in the second term). Originally, only patterns like "from 11 morning to 3" (with desc only in the first term) was supported.

[.NET] Japanese TimePeriod support

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDateTimePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchMergedExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchDateTimePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDateTimePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseTimePeriodParser.cs
Patterns/Dutch/Dutch-DateTime.yaml
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/Dutch/DateTimePeriodParser.json
Specs/DateTime/Dutch/DurationExtractor.json
Specs/DateTime/Dutch/DurationParser.json
Specs/DateTime/Dutch/MergedParser.json

Original specs: 385 pass, 2 fail.
Total specs: 552 pass, 179 fail.
The 2 failing cases involve time zones which are not supported for now.
PotentialAmbiguousRangeRegex has been enabled and implemented to help disambiguate patterns with 'voor'. 
Consequently, including 'voor' into duration patterns was no longer necessary and it has been reverted.
Handling of cases involving the limit time '12' has been modified in TimePeriod so that expressions like '10 to 12 in the morning' are parsed as (T10,T12) instead of (T22,T00).
Modified test cases:
- "Ik ga de 15e, 20:00 terug" -> "Ik ga op de 15e, 20:00 terug" (I'm going back on the 15th, 20:00), without preposition 'de 15e' cannot be extracted as date (same as in English 'the 15th' -> 'on the 15th').
- "ik ben vandaag weg tussen vijf en zeven" …

[.NET] Dutch DateTimeModel refinements

---

.NET/Microsoft.Recognizers.Definitions.Common/German/NumbersDefinitions.cs
Java/libraries/recognizers-text-number/src/main/java/com/microsoft/recognizers/text/number/resources/GermanNumeric.java
Patterns/German/German-Numbers.yaml
Python/libraries/recognizers-number/recognizers_number/resources/german_numeric.py
Specs/Number/German/NumberModel.json

"fünfzehn" was added to the `TenToNineteenIntegerRegex` for german. This was used to regenerate constant defintions for C#, Java and Python. Tests for "fünfzehn" as well as ""fünfzehntausend" were added to NumberModel.json.
I tested the "fünfzehn" example in each of the programming languages:
- DotNet: Worked.
- Python: Worked but I needed to [uncomment the German number recognizer in the number_recognizer.py](https://github.com/microsoft/Recognizers-Text/blob/34643228bf91175faeab636f43cb8c4d45c75ff9/Python/libraries/recognizers-number/recognizers_number/number/number_recognizer.py#L55)
- Java: Did not work. In fact, it seems like any number with non-english characters did not work. (including Zwölf and dreißig). Is this a known issue?
closes #2710

[DE Number] Added "fünfzehn" to German-numbers (TenToNineteenIntegerRegex)

---

Python/libraries/datatypes-timex-expression/datatypes_timex_expression/timex_helpers.py
Python/tests/datatypes/test_timex_resolver.py

* Timex like '(2021-01-01,2021-07-01,P6M)' is now resolved correctly
* Added a testcase for `last 6 months` in test_timex_resolver.py module

[TimexLib] Months daterange duration resolver fix

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Arabic/Extractors/ArabicDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishTimeExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDurationExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/IDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Hindi/Extractors/HindiDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Italian/Extractors/ItalianDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Extractors/SpanishDurationExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Turkish/Extractors/TurkishDurationExtractorConfiguration.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelCalendarMode.json

Fix to issue #2681 in .NET.
Test cases added to DateTimeModel and DateTimeModelCalendarMode.
One test case disabled because the pattern "three night" is extracted as Duration. This could be addressed in a separate issue.

 [EN DateTimeV2] fixed "one morning" incorrectly extracted as 1:00 AM (#2681)

---

.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
Patterns/Portuguese/Portuguese-DateTime.yaml
Specs/DateTime/Portuguese/DateTimeModel.json

Fix to issue #2751
Test cases added to PT DateTimeModel.

 [PT DatetimeV2] Fixed year not recognized when month is spelled-out and "de" is omitted (#2751)

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/French/Extractors/FrenchDateTimePeriodExtractorConfiguration.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json

Fix to issue #2708
Test case added to French DateTimeModel.

 [FR DateTimeV2] Fixed misses dates that are surrounded by specific words. (#2708)

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexDateHelpers.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexRelativeConvert.cs
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexDateHelpers.cs

Fix to issue #2744.
As commented in the code, a better solution would be to use ISOWeek.GetWeekOfYear, 
but it seems unavailable (even if it is supported in .NET Core 3.1 and .NET Standard 2.1).

[.NET TimexLib] Fixed ISO week number erros (#2744)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BasePercentageParser.cs
Patterns/English/English-Numbers.yaml
Specs/Number/English/PercentModel.json

Fix to issue #2702 in EN.
Test cases added to PercentModel.

[* Number] Fixed for consistency with Units, "%", "percent", and "percentage" should also be tagged as entity (#2702)

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
Java/libraries/recognizers-text-date-time/src/main/java/com/microsoft/recognizers/text/datetime/parsers/BaseDatePeriodParser.java
Java/samples/simple-console/src/main/java/com/microsoft/recognizers/text/samples/simpleconsole/Sample.java
JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts
Python/libraries/recognizers-date-time/recognizers_date_time/date_time/base_dateperiod.py
Specs/DateTime/English/DateTimeModel.json

There are two issues that can be identified in #2689 for the inputs "last week of this month" and "last week of the month". 
- Firstly, the resolution timex refers to the week 'W05', which the issue states is an "invalid" week. However, when going through the code, this seems to be an intentional design decision where any "last" week of the month will always return with a W05. This is stated in the [following docstring](https://github.com/microsoft/Recognizers-Text/blob/bf8eb3c78146e4559e1b3189073691dab897cda8/.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs#L2211). 
- However, I noticed that this behavior is not consistent in Python and JavaScript (the output is W04). We should decide on which behavior is correct and ensure consistency (perhaps as a separate …

[EN DateTimeV2] "last week of this month" resolving to previous month

---

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/NumbersDefinitions.cs
Patterns/Chinese/Chinese-Numbers.yaml
Specs/Number/Chinese/NumberModel.json
Specs/Number/Chinese/PercentModel.json
Specs/NumberWithUnit/Chinese/DimensionModel.json

Fix to issue #2667 (following python [solution](https://github.com/17000cyh/Recognizers-Text/commit/6b6ea617c42eba3d82a471d3cd090d3151f50db1) by @17000cyh).
Test cases added to NumberModel, PercentModel, DimensionModel.

 [ZH Number] Fixed negative decimal such as "负1.1" 、"负0.2千米"、"负3.9%" can't be recognized (#2667)

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json

[FR DatetimeV2] Fixed year not recognized when month is spelled-out and "de" precedes the year (#2771)

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/DoubleExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs
Patterns/Korean/Korean-Numbers.yaml
Specs/Number/Korean/NumberModel.json

A few inputs have been modified e.g. 
- "조 번째" -> "일조 번째" (one trillion). "조 번째" alone does not mean "trillion" it needs to be preceded by a number.
- "180.25ml의 액체", "180ml 의 액체", "29km의 길". A space has been added between the number and the unit in order to reproduce the behavior of the corresponding English cases.

[KO Number] Korean Number refinements

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

[EN DateTime V2] Fixed not all phrases of a form [day abbreviation][number] (e.g. "Mon 13th") are consistently recognized in .NET (#2803)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

Fix to issue #2736.
Note: "mornings" is now treated as Set but "in the mornings" is still parsed as TimeRange because some test cases expect such resolution.

[EN DateTimeV2] Fixed "tuesday afternoons" returns null resolution dictionary (#2736)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
Patterns/English/English-Numbers.yaml
Specs/Number/English/NumberModel.json
Specs/Number/English/OrdinalModel.json
Specs/Number/English/OrdinalModelSuppressExtendedTypes.json

Fix to issue #2826 and #2690.
Test cases added to NumberModel.

[EN Number] Fixed "a current" or similar phrases determined as ordinal detected as a number fraction (#2826)

---

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersWithUnitDefinitions.cs
Patterns/Japanese/Japanese-Numbers.yaml
Patterns/Japanese/Japanese-NumbersWithUnit.yaml
Specs/NumberWithUnit/Japanese/CurrencyModel.json

54 cases pass; 3 cases fail.
Failing cases:
- "人民元八千元", "人民元五十元": The unit is split around the number but NumberWihUnitExtractor explicitly prevents to extract both prefix and suffix units for Currency to avoid other issues.
- "金融市場で運用する資金運用事業を合わせた財投総額も過去最大の同二％減の四十九兆九千五百九十二億円となっている。": NumberExtractor does not correctly extract the large number.
Modified cases:
- A typo, '憶' instead of '億' has been corrected in a few inputs.
- "東芝の再編はもう一万憶が必要、取引銀行に借り入れを申請した。"  -> "東芝の再編はもう一万億円が必要、取引銀行に借り入れを申請した。", missing expected unit '円'.

[JA Currency] Currency refinements

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Extractors/BaseNumberRangeExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/NumberRangeExtractor.cs
Patterns/Korean/Korean-Numbers.yaml
Specs/Number/Korean/NumberRangeModel.json

Some resolutions have been modified because the input meaning differed from the corresponding English spec. New test cases have been added to better match the originals (when not already present).
List of modified test cases:
- "이 숫자는 20과 30 사이에 있다." "(20,30)" -> "[20,30)" (original: "The number is between 20 and 30." "[20,30)")
- "그는 십등에서 십오등 사이에 위치했다." "(10,15)" -> "[10,15)" (original: "He ranks between the tenth and the fifteenth." "[10,15)")
- "그는 열 번째에서 열다섯 번째 사이에 위치했다." "(10,15)" -> "[10,15)" (original: "He ranks between the tenth and the fifteenth." "[10,15)")
- "그는 마이너스 십점에서 십오점 사이의 점수를 얻었다." "(-10,15)" -> "[-10,15)" (original: "He scores between negative ten and fifteen." "[-10,15)")
- "그는 삼십 세 이상이다." "(30,)" -> "[30,)" (original: "His age is no less than …

[KO Number] Korean NumberRange refinements

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Korean/Extractors/NumberRangeExtractor.cs
Patterns/Korean/Korean-Numbers.yaml
Specs/Number/Korean/NumberRangeModel.json

"X 과 같거나 최소 Y" can be translated to "is X or at least Y" or "is equal to X or at least Y". 
In English, "is X or at least Y" returns one result, "at least Y", and "is equal to X or at least Y" returns 2 results, "equal to X" and "at least Y".
Now in Korean, "X 과 같거나 최소 Y" also returns 2 results: "X 과 같" (equal to X) and "최소 Y" (at least Y).

[KO Number] Korean NumberRange fixed extraction of pattern 'is 30 or at least 30'

---

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Korean/Parsers/KoreanDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDurationParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDateParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDurationParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/ICJKDurationParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/DurationParsingUtil.cs
.NET/Microsoft.Recognizers.Text.Number/Japanese/Extractors/IntegerExtractor.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Chinese/Extractors/ChineseNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Extractors/JapaneseNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Korean/Extractors/KoreanNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Utilities/CommonUtils.cs
Patterns/Japanese/Japanese-DateTime.yaml
Patterns/Japanese/Japanese-Numbers.yaml
Specs/DateTime/Japanese/DurationExtractor.json
Specs/DateTime/Japanese/DurationParser.json

- Moved common methods IsLessThanDay and ParseInexactNumberUnit from BaseDurationParser to DurationParsingUtil.
- Moved ExpandHalfSuffix (used in CJK languages) from ChineseNumberWithUnitExtractor to CommonUtils in NumberWithUnit.
Changes to specs:
- Added the character '間' to the extracted text when missing (間 indicates a duration and can be translated as 'during').
- Patterns involving 'couple' (e.g. "I'll be away for a couple of days.") are rendered in Japanese using 'few|some' because there is no equivalent of 'couple'. The resolution has therefore been updated accordingly (P2D -> P3D).

[JA DateTimeV2] Duration refinements

---

Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/number_with_unit_recognizer.py
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/parsers.py
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/spanish/parsers.py
Specs/NumberWithUnit/Spanish/CurrencyModel.json

- Using BaseMergedUnitParser and BaseMergedUnitExtractor for es-es CurrencyModel.
- Update __get_number_value to return number_value in format based on culture instead of general format.
- 
With this change, CurrencyModel for es-es will use **_BaseCurrencyParser_** and **___merged_compound_units_** (for extraction) 
and be able to resolve fractional units like "15 dolares y 15 centavos por favor" , "Son 25 dolares 50 por libra"
Resolved value is formatted to culture-based format with changes to function **___get_number_value_**

[Python] Fix parsed values format in number with unit (es-es)

---

Patterns/Portuguese/Portuguese-DateTime.yaml
Patterns/Portuguese/Portuguese-NumbersWithUnit.yaml
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/number_with_unit_recognizer.py
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/portuguese/parsers.py
Specs/DateTime/Portuguese/TimeParser.json
Specs/NumberWithUnit/Portuguese/CurrencyModel.json

Update Portuguese datetime regex for SuffixAfterRegex, so it does not match on a period at the end of a datetime input. eg "11:55."
Update Portuguese NumbersWithUnit CompoundUnitConnectorRegex, so that compound sentences for currency will resolve eg "15 dólares e 15 centavos, por favor"

Update Portuguese datetime and Numbers with unit regex

---

.NET/Microsoft.Recognizers.Definitions.Common/Korean/NumbersDefinitions.cs
Patterns/Korean/Korean-Numbers.yaml
Specs/Number/Korean/NumberModel.json

Fix to issue #2863. 
Test case added to NumberModel.
The problem is '일' is ambiguous and is used in many expressions where it does not represent a number. 
We had already encountered the issue in the past and tried to address it by adding some conditions to the regexes, but it is likely that there are still patterns where it is wrongly extracted.

[KO Number] Fixed incorrect extraction of number from datetime mention (#2863)

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimex.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConvertEnglish.cs

The `TimexProperty.ToString()` english conversion of DateTime strings returns the wrong ordinal for days 11-13. In English, ordinals 1 through 3 have special suffixes - 1st, 2nd, 3rd - _except_ on 11-13, where the suffixes are 11th, 12th, 13th.
Fixes #2895

[EN .NET] Fix Timex to string conversion of english ordinals 11-13

---

.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimex.cs
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/English/TimexConvertEnglish.cs

This fixes the conversion to string of DateTimeRange Timex types such as`"(2022-03-15T16,2022-03-15T18,PT2H)"` to not assume there's a part of day in the `TimexProperty` object when there isn't one.
Fixes #2893

[EN .NET] Fix TimexProperty.ToString() to handle DateTimeRanges properly

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersWithUnitDefinitions.cs
Patterns/English/English-NumbersWithUnit.yaml
Specs/NumberWithUnit/English/CurrencyModel.json

Fix to issue #2858.
Test cases added to CurrencyModel.

[*|EN Currency] Fixed 'ALL' is picked up as a currency (#2858)

---

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs
Patterns/Japanese/Japanese-Numbers.yaml
Specs/Number/Japanese/NumberModel.json
Specs/NumberWithUnit/Japanese/CurrencyModel.json

Fix to issue #2922.
Test cases added to JP NumberModel and CurrencyModel.

[Number JP] Fix recognizing kanji 零[rei] zero (#2922)

---

.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Japanese/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Text.Number/Japanese/Extractors/NumberExtractor.cs
.NET/Microsoft.Recognizers.Text.Number/Japanese/Parsers/JapaneseNumberParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseCJKNumberParser.cs
Patterns/Japanese/Japanese-Numbers.yaml
Patterns/Japanese/Japanese-NumbersWithUnit.yaml
Specs/Number/Japanese/NumberModel.json
Specs/NumberWithUnit/Japanese/CurrencyModel.json

Fix to issue #2923.
Added support for hiragana numbers (integer).
Test cases added to NumberModel and CurrencyModel.

[JA Number] Extend number recognition to include Kana along with existing Kanji and Arabic numerals (#2923)

---

.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseMergedDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKMergedDateTimeParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/MergedParserUtil.cs
Specs/DateTime/Chinese/DateTimeModel.json
Specs/DateTime/Chinese/DateTimeModelExperimentalMode.json

Fix to issue #2557.
Moved common methods in BaseMergedDateTimeParser and BaseCJKMergedDateTimeParser to MergedParserUtil. 
In this way, the modifiers "since" and "until" produce the same results in English and Chinese.
Moreover, test cases referring to the Lunar calendar in Chinese are now labelled with the tag "isLunar":
- "农历2015年十月初一"
- "正月三十"
- "2015年十月初一早上九点二十" ????
- "神龙二年正月初一"
- "雍正四年大年三十"
Updated affected test cases in Chinese DateTimeModel and DateTimeModelExperimentalMode.

[ZH DateTimeV2] Fixed handling of modifiers "since" and "until" in CJK implementation (#2557)

---

.NET/Microsoft.Recognizers.Definitions.Common/Swedish/NumbersWithUnitDefinitions.cs
Patterns/Swedish/Swedish-NumbersWithUnit.yaml
Specs/NumberWithUnit/Swedish/CurrencyModel.json

Fix to issue #2891.
Test cases added to CurrencyModel.

[SV Currency] Fix ATT recognized as a currency unit in the wrong context (#2891)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/NumbersWithUnitDefinitions.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Chinese/Extractors/ChineseNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Dutch/Extractors/DutchNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/English/Extractors/EnglishNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/BaseMergedUnitExtractor.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/INumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Extractors/NumberWithUnitExtractor.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/French/Extractors/FrenchNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/German/Extractors/GermanNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Hindi/Extractors/HindiNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Italian/Extractors/ItalianNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Japanese/Extractors/JapaneseNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Korean/Extractors/KoreanNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Parsers/BaseCurrencyParser.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Portuguese/Extractors/PortugueseNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Spanish/Extractors/SpanishNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Swedish/Extractors/SwedishNumberWithUnitExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Turkish/Extractors/TurkishNumberWithUnitExtractorConfiguration.cs
Patterns/English/English-NumbersWithUnit.yaml
Patterns/Portuguese/Portuguese-NumbersWithUnit.yaml
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/english/extractors.py
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/extractors.py
Python/libraries/recognizers-number-with-unit/recognizers_number_with_unit/number_with_unit/utilities.py
Specs/NumberWithUnit/English/CurrencyModel.json
Specs/NumberWithUnit/Portuguese/CurrencyModel.json
Specs/NumberWithUnit/Portuguese/DimensionModel.json

Fix to issue #2882
- Modified base code to support “Value Currency Multiplier” (e.g. 75 USD milhoes) in PT and EN
- Modified base code to better handle cases like "15 USD 50" (-> 15.50 USD) and "15 USD50" (-> 50 USD).
Test cases added to DimensionModel and CurrencyModel in PT and EN.

[PT Unit|Currency] Fix bugs reported from Speech (#2882)

---

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Japanese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Korean/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseSetExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/BaseCJKSetExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/ICJKSetExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Extractors/JapaneseSetExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Japanese/Parsers/JapaneseSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Korean/Extractors/KoreanSetExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Korean/Parsers/KoreanSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseSetParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKSetParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/ICJKSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/SetHandler.cs
Patterns/Chinese/Chinese-DateTime.yaml
Patterns/Japanese/Japanese-DateTime.yaml
Patterns/Korean/Korean-DateTime.yaml
Specs/DateTime/Japanese/SetExtractor.json
Specs/DateTime/Japanese/SetParser.json
Specs/DateTime/Japanese/TimePeriodParser.json

In DateTimeModel 204 pass, 358 fail.
Modified test cases:
- Japanese does not use plural for days and time of days ("sundays", "mornings"...), so inputs corresponding to these patterns have been corrected to use "each/every":
- 午前9時に出発する。 -> 各午前9時に出発する。("I'll leave mornings at 9am" -> "I'll leave each mornings at 9am")
- 午前9時に出発する。 -> 毎午前9時に出発する。("I'll leave on mornings at 9am" -> "I'll leave every mornings at 9am")
- 毎週日曜日に出発する。 -> 各週日曜日に出発する。("I'll leave on Sundays" -> "I'll leave each Sunday")
- 毎晩9時に出発する。 -> 各晩9時に出発する。("I'll leave every night at 9" -> "I'll leave each night at 9"): duplicate
- Corrected wrong resolution of weekdays in some test cases:
- 毎週月曜日午前9時 (I'll leave every Monday at 9am): XXXX-WXX-7T09 -> XXXX-WXX-1T09
- 毎週日曜日午後八時 (I'll leave every Sunday …

[JA DateTimeV2] Set refinements

---

.NET/Microsoft.Recognizers.Definitions.Common/English/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/NumbersDefinitions.cs
Patterns/English/English-Numbers.yaml
Patterns/Spanish/Spanish-Numbers.yaml
Specs/Number/English/NumberModel.json
Specs/Number/Spanish/NumberModel.json
Specs/Number/Spanish/OrdinalModel.json

Fix to issue #2888.
Test cases added to EN NumberModel and ES NumberModel and OrdinalModel.

[ES Number] Missing support for a few units and abbreviations (#2888)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Extractors/PortugueseDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Portuguese/Parsers/PortugueseSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishHolidayParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Spanish/Parsers/SpanishSetParserConfiguration.cs
Patterns/English/English-DateTime.yaml
Patterns/Portuguese/Portuguese-DateTime.yaml
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/Italian/DateTimeModel.json
Specs/DateTime/Portuguese/DateTimeModel.json
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2890.
Test cases added to EN, PT, ES DateTimeModels.
Did not add support for pattern "7 del próximo domingo a la tarde" because it is ambiguous ("Jornada 7 del próximo domingo", "Torneo de Fútbol 7 del próximo domingo", "Las máximas se mantendrán entre los 13 grados de este jueves y los 7 del próximo domingo"...). 
Added support for the less ambiguous patterns "a las 7 del...", "7h del...", "7 horas del..."

[ES DateTimeV2] Fix misc bugs generated from Speech (#2890)

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs
Patterns/French/French-DateTime.yaml
Patterns/Portuguese/Portuguese-DateTime.yaml
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/French/DateTimeModel.json
Specs/DateTime/German/DateTimeModel.json
Specs/DateTime/Italian/DateTimeModel.json
Specs/DateTime/Portuguese/DateTimeModel.json
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2945.
Test cases added to EN and NL DateTimeModels. 
The other languages were not affected because they do not use the mechanism responsible for the issue.

[* DateTimeV2] Fix "before" no longer recognized in multi mentions like "from 2010 to 2018 or before 2000" (#2945)

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Portuguese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Spanish/DateTimeDefinitions.cs
Patterns/Dutch/Dutch-DateTime.yaml
Patterns/English/English-DateTime.yaml
Patterns/German/German-DateTime.yaml
Patterns/Italian/Italian-DateTime.yaml
Patterns/Portuguese/Portuguese-DateTime.yaml
Patterns/Spanish/Spanish-DateTime.yaml
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/English/DateTimeModelCalendarMode.json
Specs/DateTime/English/DateTimeModelComplexCalendar.json
Specs/DateTime/English/DateTimeModelExperimentalMode.json
Specs/DateTime/English/DateTimeModelExtendedTypes.json
Specs/DateTime/English/DateTimeModelSplitDateAndTime.json
Specs/DateTime/French/DateTimeModel.json
Specs/DateTime/German/DateTimeModel.json
Specs/DateTime/Italian/DateTimeModel.json
Specs/DateTime/Portuguese/DateTimeModel.json
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2850 in NL|EN|FR|DE|IT|PT|ES
Test cases added to DateTimeModels.

 [* DateTimeV2] Fix date range (without year) is processed as a single Date with Year (#2850)

---

.NET/Microsoft.Recognizers.Definitions.Common/Dutch/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Dutch/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Extractors/DutchDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchHolidayParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchSetParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Dutch/Parsers/DutchTimePeriodParserConfiguration.cs
Patterns/Dutch/Dutch-DateTime.yaml
Patterns/Dutch/Dutch-Numbers.yaml
Specs/DateTime/Dutch/DateTimeModel.json

Fix to issue #2898.
Pattern 4 (Replacing 1 with een in “week 1” is not detected, also the expression “Het gebeurde door een tijdsverschil van een seconde” both “eens” are resolves to the number 1 while only the latter is a number.) has not been addressed because "week one" is not supported by design also in English and 'een' number is indistinguishable from 'een' article.
Test cases added or enabled in DateTimeModel.

[NL DateTimeV2] Fix multiple issues from speech across date/time sub-types (#2898)

---

JavaScript/packages/recognizers-date-time/src/dateTime/baseMerged.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/dateTimeConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts
Specs/DateTime/Chinese/DateTimeModel.json

Addressing comments from PR #2593.
Added support for 'isLunar' tag in Javascript (ZH).
Added support for mods 'before', 'after', 'since' in Javascript (ZH) (mod 'until' is not supported in JS standard implementation).
Test cases enabled in Chinese DateTimeModel.

[Javascript] Refinements from issue #2557

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.xml
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateExtractor.json
Specs/DateTime/English/DateParser.json
Specs/DateTime/English/DateTimeModel.json

1. Reading text correctly when the date and month are not written without a space, such as 29Feb.
2. Added support to recognize "tmrw" as date.

[EN DateTimeV2] Improving recognition of informal dates

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Italian/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDurationExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseMergedDateTimeExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseTimeExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/BaseCJKDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/CJK/BaseCJKMergedDateTimeExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/ExtractResultExtension.cs
Patterns/English/English-DateTime.yaml
Patterns/Italian/Italian-DateTime.yaml
Specs/DateTime/Dutch/DateTimeModel.json
Specs/DateTime/English/DateTimeModel.json
Specs/DateTime/French/DateTimeModel.json
Specs/DateTime/German/DateTimeModel.json
Specs/DateTime/Italian/DateTimeModel.json
Specs/DateTime/Portuguese/DateTimeModel.json
Specs/DateTime/Spanish/DateTimeModel.json

Fix to issue #2960.
(Pushed on top of #2983 to take into account refactoring implemented there)
Also, moved method FilterAmbiguity to ExtractResultExtension since is used in multiple entities.
Test cases added to EN DateTimeModel.

[* DateTimeV2] Fixed I case of YYYY entry presence in the parsed text the recognizer sometimes outputs incorrect results (#2960)

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/German/Extractors/GermanDateExtractorConfiguration.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateTimeModel.json

[DE DateTimeV2] Fixed German date recognition inconsistent if containing ordinal numbers as words (#2985)

---

.NET/Microsoft.Recognizers.Definitions.Common/German/DateTimeDefinitions.cs
Patterns/German/German-DateTime.yaml
Specs/DateTime/German/DateTimeModel.json

Added support for 'en' suffix as for comment in #3001.

[DE DateTimeV2] Added support for 'en' suffix in German date containing ordinal numbers as words (#2985)

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Definitions.Common/Hindi/NumbersDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Utilities/DateContext.cs
Patterns/English/English-DateTime.yaml
Patterns/Hindi/Hindi-Numbers.yaml
Specs/DateTime/English/DateTimeModel.json
Specs/Number/Hindi/OrdinalModelSuppressExtendedTypes.json

Fix to issue #2905.
Modified methods MergeTwoTimePoints in Base DatePeriod Extractor/Parser to support cases where one of the date points is an ordinal number.
Fixed issue in Hindi where "पहले" (first) was wrongly extracted from "से पहले" (before).
Test cases added to EN DateTimeModel.

[EN DateTime V2] Added support for cases like "April ninth through 15th" (#2905)

---

.NET/Microsoft.Recognizers.Definitions.Common/BaseDateTime.cs
Patterns/Base-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

Fix as for [comment](https://github.com/microsoft/Recognizers-Text/pull/2992#discussion_r919874202) in PR #2992.
Test cases added to EN DateTimeModel.

[* DateTimeV2] Removed extraction of expressions like '1:1' as time

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
JavaScript/packages/recognizers-date-time/src/dateTime/baseDatePeriod.ts
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/english/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/french/datePeriodConfiguration.ts
JavaScript/packages/recognizers-date-time/src/dateTime/spanish/datePeriodConfiguration.ts
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DateTimeModel.json

Fix to issue #2656 in .NET and JavaScript.
Did not tackle the pattern in Number because it does not seem wrong to extract "two quarters" as fraction. 
I can find expressions that use it, e.g. "the last two quarters of the book are dedicated to it".

[EN DateTimeV2] Fixed incorrect parsing of period mentions like 'last two quarters' (#2656)

---

Python/libraries/recognizers-text/recognizers_text/utilities.py
Python/libraries/recognizers-text/setup.py

Modified  Python\libraries\recognizers-text\recognizers_text\utilities.py in accordance with the changes in the latest emoji package (version 2.0.0).
Changed the **UNICODE** import to **demojize** as UNICODE was deprecated in **emoji==2.0.0**. Made changes to the is_emoji function in  Python\libraries\recognizers-text\recognizers_text\utilities.py in accordance with the demojize import.
Updated the requirements in setup to emoji==2.0.0

[Python] Update dependency to latest emoji pkg

---

.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/TimexParsing.cs

Converting sets to string has a failing unit test on "SP" or "every spring". Parsing DateTime expressions relies on the fact that presence of "T" and "P" always indicates time and period respectively. There is an exception and that is the string "SP" that indicates "spring" and not the reserved character "P" in the iso8601 standard.

[EN DateTimeV2] Fixing failing timexlib unit test

---

.NET/Microsoft.Recognizers.Text.Choice/Microsoft.Recognizers.Text.Choice.csproj
.NET/Microsoft.Recognizers.Text.DataDrivenTests/Microsoft.Recognizers.Text.DataDrivenTests.csproj
.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests.csproj
.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression/Microsoft.Recognizers.Text.DataTypes.TimexExpression.csproj
.NET/Microsoft.Recognizers.Text.DateTime/Microsoft.Recognizers.Text.DateTime.csproj
.NET/Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.csproj
.NET/Microsoft.Recognizers.Text.NumberWithUnit/Microsoft.Recognizers.Text.NumberWithUnit.csproj
.NET/Microsoft.Recognizers.Text.Sequence/Microsoft.Recognizers.Text.Sequence.csproj
.NET/Microsoft.Recognizers.Text/Microsoft.Recognizers.Text.csproj
.NET/Samples/BotBuilder/BotBuilderRecognizerBot.csproj
.NET/Samples/RecognizerFunction/RecognizerFunction.csproj
JavaScript/packages/datatypes-date-time/package-lock.json

- Updating some packages to address the Azure OneBranch component governance errors.
- Adding the packages metadata to the .csproj files. This was needed so that the dotnet pack command that will be used in the new onebranch pipeline adds the same metadata that the packages contain today.

[Infra] Fixing component governmence vulnarabilities and OneBranch changes

---

JavaScript/packages/recognizers-choice/package.json
JavaScript/packages/recognizers-number/package.json
JavaScript/packages/recognizers-sequence/package.json

Bumps packages which only depend on recognizers text and updates the version of the dependency used to 1.3.1
Ran build and test successfully in parent Javascript directory:
Successful Build
Successful Test

Bump choice sequence and number package versions

---

JavaScript/packages/recognizers-date-time/package.json

Bump the npm version for recognizers date time.
Also bump the dependencies version accordingly.
Ran npm install, npm run build and npm run test locally
successful build
successful test

Bump npm version for recognizers date time

---

JavaScript/packages/recognizers-date-time/package.json
JavaScript/packages/recognizers-date-time/src/dateTime/chinese/mergedConfiguration.ts

Fix npm build for recognizers datetime and bump the npm version for recognizers date time.
Testing
Ran npm install, npm run build and npm run test locally
successful build
successful test

Fix build failure for recognizers date time

---

.NET/Microsoft.Recognizers.Text.Number/Microsoft.Recognizers.Text.Number.xml
.NET/Microsoft.Recognizers.Text.Number/Parsers/BaseNumberParser.cs
Specs/Number/English/NumberModel.json
Specs/Number/English/NumberModelExperimentalMode.json

Fix wrong resolution for some fractions, scenario as below.
“two hundred and fifty-four hundredths” -> 200.54 (correctly found)
“two and fifty-four hundredths” -> 0.0037037037… (it calculates (2 / 54) div by 100) instead of 2.54

Fix wrong resolution for some fractions

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateExtractor.json
Specs/DateTime/French/DateParser.json
Specs/DateTime/French/DateTimeModel.json

Fix 2 years ago in French not recognized.
"il y a deux ans" e.g. "two years ago" is not being detected in French.

Fix 2 years ago in French not recognized

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
.NET/Samples/SimpleConsole/Program.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DatePeriodExtractor.json
Specs/DateTime/English/DatePeriodParser.json
Specs/DateTime/English/DateTimeModel.json

Support for longer span date time as below.
- for x weeks/days from today/tomorrow/specific date
- for x weeks/days, from today/tomorrow/specific date

[EN DateTimeV2] Support for longer span date time

---

.NET/Microsoft.Recognizers.Definitions.Common/English/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Constants.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Extractors/EnglishDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/English/Parsers/EnglishDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Extractors/BaseDatePeriodExtractor.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/BaseDatePeriodParser.cs
Patterns/English/English-DateTime.yaml
Specs/DateTime/English/DatePeriodExtractor.json
Specs/DateTime/English/DatePeriodParser.json
Specs/DateTime/English/DateTimeModel.json

There were 3 commits that were not merged in. 
Preparing release of 1.8.9 by adding 3 more commits as part of this change.

Cherry pick commits for new changes

---

Python/libraries/recognizers-date-time/recognizers_date_time/date_time/utilities.py
Python/libraries/recognizers-number/recognizers_number/number/extractors.py

Fix 2 Python syntax warnings as below.
/usr/local/lib/python3.10/site-packages/recognizers_date_time/date_time/utilities.py:552: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
bias = 0[0]
/usr/local/lib/python3.10/site-packages/recognizers_number/number/extractors.py:37: SyntaxWarning: "is" with a literal. Did you mean "=="?
if source is None or len(source.strip()) is 0:

Fix 2 Python syntax warnings

---

.NET/Microsoft.Recognizers.Text.Number/Models/AbstractNumberModel.cs
Specs/Number/French/NumberModel.json

Add support for French number sub type in resolution as below.
"Results": [
{
"Text": "3",
"TypeName": "number",
"Resolution": {
**"subtype": "integer",**
"value": "3"
},
"Start": 0,
"End": 1
}

Support French number sub type

---

.NET/Microsoft.Recognizers.Text.DateTime/German/Parsers/HolidayParserGer.cs

Fix occasionally NullReferenceException in German DateTimeModel test when input is tag der Arbeit, the test and message as below.
Test:
Microsoft.Recognizers.Text.DateTime.Tests.TestDateTime_German DateTimeModel 
Message: 
Test method Microsoft.Recognizers.Text.DateTime.Tests.TestDateTime_German.DateTimeModel threw exception: 
System.ApplicationException: Input: "Tag der Arbeit, ersten Weihnachtsfeiertag, zweiten Weihnachtstag" ---> System.NullReferenceException: Object reference not set to an instance of an object.

[DE DateTimeV2] Fix occasionally NullReferenceException in German DateTimeModel test when input is tag der Arbeit

---

.NET/Samples/SimpleConsole/Program.cs

Adding support for changing input language for SimpleConsole app.
Input the language index to select the language, input "switch" to switch to another language.

Adding support for changing input language for SimpleConsole app

---

.NET/Microsoft.Recognizers.Definitions.Common/BaseEmail.cs
Patterns/Base-Email.yaml
Specs/Sequence/English/EmailModel.json

Fix email address not be recognized when there are some Chinese characters in the sentence.
Originally, the recognizer cannot recognize the email address "test@test.com" in sentence "1邮件地址test@test.com", now fix it.

[ZH Email] Fix email address not be recognized when there are some Chinese characters in the sentence.

---

.NET/Microsoft.Recognizers.Definitions.Common/Chinese/DateTimeDefinitions.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDateExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Extractors/ChineseDatePeriodExtractorConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDateParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Chinese/Parsers/ChineseDatePeriodParserConfiguration.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDateParser.cs
.NET/Microsoft.Recognizers.Text.DateTime/Parsers/CJK/BaseCJKDatePeriodParser.cs
Patterns/Chinese/Chinese-DateTime.yaml
Specs/DateTime/Chinese/DateExtractor.json
Specs/DateTime/Chinese/DateParser.json
Specs/DateTime/Chinese/DatePeriodExtractor.json
Specs/DateTime/Chinese/DatePeriodParser.json
Specs/DateTime/Chinese/DateTimeModel.json

Support Chinese week day after/before two weeks, the week/weekend before last, below are examples.
- 下下周一（Monday after two weeks）
- 上上周日 (Sunday before two weeks) 
- 上上周末（The weekend before last）
- 上上周（The week before last）

[ZH DateTimeV2] Support Chinese week day after/before two weeks, the week/weekend before last

---

.NET/Microsoft.Recognizers.Definitions.Common/French/DateTimeDefinitions.cs
Patterns/French/French-DateTime.yaml
Specs/DateTime/French/DateTimeModel.json
Specs/DateTime/French/DurationExtractor.json
Specs/DateTime/French/DurationParser.json

Fix the issue of 'duration' in French being parsed as a time.
In French, "2 heures" (two hours) can be used in different contexts, mainly for telling time and indicating duration.
For example, "2 heures" in "dure 2 heures" was originally detected as time "02:00", it is incorrect, it should be a 2 hours duration.

[FR DateTimeV2] Fix the issue of 'duration' in French being parsed as a time
